Alfresco/Aikau

l10n.properties
This is the configuration file to support the Dev Env localisation tools updates r435. See mirror of tools at: https://github.com/davidcognite/alfresco-localisation-tools
=> L10N: Add project specific config file.

aikau-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
his issue wasn't in Sprint 2 but I wanted to get this pushed into develop asap in order for Tutorial 1 (which is part of Sprint 1) to work... currently isn't working because the public repos aren't configured.
=> AKU-100: Ensure Aikau project works outside of Alfresco network

tutorial/chapters/Tutorial3.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-104
=> AKU-104: Moving tutorial 3 into GitHub

tutorial/chapters/Tutorial1.md
This is a minor change to the command to build a new client using the Maven Archetype. The change ensures that the latest (non-snapshot) version available is used.
=> Updated command to use Maven Archetype to ensure latest release is used.

aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/documentlibrary/SitesListTest.js, aikau/src/test/resources/alfresco/forms/controls/SimplePickerTest.js, aikau/src/test/resources/alfresco/menus/AlfCheckableMenuItemTest.js, aikau/src/test/resources/alfresco/preview/PdfJsPreviewTest.js, aikau/src/test/resources/config/Suites.js
Reviewed failing unit tests (on Vagrant) and fixed/quarantined so that we get a clean test run.
=> Fixes to failing unit tests on Vagrant

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-108 which requested the capability to set forms by publishing a payload.
=> AKU-108: Added ability to set form value via publication

aikau/.gitattributes
Add binary extensions config to .gitattributes file
=> Fix line endings (contd.)

aikau/src/main/resources/alfresco/header/Title.js, aikau/src/main/resources/alfresco/html/Heading.js, aikau/src/test/resources/alfresco/html/HeadingTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Heading.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Heading.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Heading.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Heading.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-102 as well as making a minor correction to the previous fix for AKU-103. It adds a unit test for the widget.
=> AKU-102, AKU-103: Localization updates

aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
Add the response to MockXhr logging when using the XHR mock during testing
=> MockXhr response logging

aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css
Update MockXhr logging to fix bugs discovered when using in another test
=> Update MockXhr logging to fix bugs discovered when using in another test

aikau/src/test/resources/alfresco/forms/controls/ComboBoxTest.js, aikau/src/test/resources/alfresco/layout/BasicLayoutTest.js, aikau/src/test/resources/alfresco/menus/AlfMenuBarToggleTest.js
I've fixed up the 3 unit tests that were being reported as failing on Chrome.
=> Fixed unit tests that were failing on Chrome

aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/alfresco/preview/PdfJsPreviewFaultsTest.js, aikau/src/test/resources/config/Suites.js
More fixes for failing tests and updates to use best practices
=> Fixes for failing tests

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf.xml, aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/templates/LiveSearch.html, aikau/src/main/resources/alfresco/header/templates/LiveSearchItem.html, aikau/src/main/resources/alfresco/header/templates/SearchBox.html, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js, aikau/src/test/resources/testApp/WEB-INF/surf.xml, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SearchBoxMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/pdf_docs_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/pdf_people_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/pdf_sites_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/site_docs_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/site_more_docs_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/site_people_search.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/site_sites_search.json
Re-created from https://github.com/Alfresco/Aikau/pull/84 due to merge conflicts
This PR addresses https://issues.alfresco.com/jira/browse/AKU-140. In order to add in a test it was necessary to perform some refactoring of the SearchBox code to ensure that it worked independently of Share and added some configuration to make it more abstract. Then the fix was applied and the unit test updated.
=> AKU-140: Search scope issues

aikau/src/main/resources/alfresco/services/DialogService.js
This addresses: https://issues.alfresco.com/jira/browse/AKU-151.  Need to be really careful with these types of optimizations in the future.
=> AKU-151: Corrected logic tweaking that has broken DialogService layout

aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js
This PR fixes up some of the test failure introduced in 1.07 and 1.0.8 development
=> Fixed test problems

aikau/ReleaseNotes.md
These are the draft release notes for 1.0.8... AKU-33 is a pending change
=> Release notes for 1.0.8

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-160 and https://issues.alfresco.com/jira/browse/AKU-161 which correct minor mistakes introduced in earlier commits
=> AKU-160, AKU-161: BaseFormControl corrections

aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
I'm not sure how I managed to get passing tests the first time (because I did run them before submitting) but on a recent test run I got some errors and have added corrections to test properly! I'd set the wrong attribute in the test page and have modified the test to ensure consistency, also addressed another FireFox issue in that it wasn't clicking the radio button properly
=> AKU-161: Corrections to previous committed tests

aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js, aikau/src/test/resources/alfresco/core/PublishPayloadMixinTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/PublishPayloadMixin.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-149
=> AKU-147: Added allowances for missing data in built payloads

aikau/src/test/resources/alfresco/forms/controls/DocumentPickerSingleItemTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DocumentPickerSingleItem.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DocumentPickerSingleItem.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DocumentPickerSingleItem.get.js
Test showing the singleItemMode failing, as per https://issues.alfresco.com/jira/browse/AKU-168
=> Failing Test for bug in PickedItems widget in singleItemMode.

aikau/src/main/resources/alfresco/pickers/PickedItems.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-168
=> AKU-168: Fixes single item picker selection mode

pom.xml
Added the "maven-compiler-plugin" to ensure that the correct version of Java is used.
=> Issue-116: Configured maven-compiler-plugin

aikau/src/test/resources/reporters/AikauReporter.js
Add timing information to the new reporter and tighten up a couple of formatting issues in the output.
=> Add timing information to new reporter

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-182
=> AKU-182: Updated archetype surf.xml 

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/renderers/css/Property.css, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/reporters/AikauReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-159 which is a request for the ability to truncate Property renderers. It also includes updates to the output of the AikauReporter.
=> AKU-159: Property renderer that truncates text

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/basic.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/basic.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-184
=> AKU-184: Ensure DND items and dropped items labels are localized

aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js
typeof returns a string, so the old if statement always returned true...
=> Fix processInstanceTokens so typeof check works as expected

aikau/src/main/resources/alfresco/dnd/Constants.js, aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/additional-config.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/basic.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/form-modelling.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/modeller.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/nested.get.desc.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-190
=> AKU-190: Updates to support single source item selection

aikau/src/main/resources/alfresco/dnd/Constants.js, aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-189
=> AKU-189: Updates to support drag and drop single use mode

aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/webscript-libs/dnd-models/forms.lib.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/additional-config.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/modeller.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-188
=> AKU-188: Hide edit button on DND items unless requested

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/css/AlfFilteredList.css, aikau/src/main/resources/alfresco/lists/i18n/AlfFilteredList.properties, aikau/src/test/resources/alfresco/lists/FilteredListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FilteredListMockService.js
This addresses https://issues.alfresco.com/jira/browse/AKU-192
=> AKU-192: Added support for list filtering

aikau/src/main/resources/alfresco/logo/css/Logo.css
This fixes https://issues.alfresco.com/jira/browse/AKU-217
=> AKU-217: Correction to margins for Logo 

aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/java/org/alfresco/aikau/UnitTestList.java, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js, aikau/src/test/resources/alfresco/documentlibrary/SitesListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SitesList.get.js
I've made some further updates for https://issues.alfresco.com/jira/browse/AKU-192 to support URL hash and pagination behaviour as well as making use of the capabilities in the unit test index page.
=> Update index page to support filtering

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/DragAndDropItemsListView.js, aikau/src/main/resources/alfresco/dnd/templates/DragAndDropItemsListView.html, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/list-of-items.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/list-of-items.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/list-of-items.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-191.
=> AKU-191: Creation of a DND items list view

aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/main/resources/alfresco/renderers/_JsNodeMixin.js, aikau/src/main/resources/alfresco/renderers/_XhrActionsMixin.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/SimpleWorkflowService.js, aikau/src/main/resources/alfresco/services/actions/i18n/SimpleWorkflowService.properties, aikau/src/test/resources/alfresco/services/actions/SimpleWorkflowTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/SimpleWorkflow.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/SimpleWorkflow.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/SimpleWorkflow.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SimpleWorkflowMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SimpleWorkflow/Response.json
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-196 and https://issues.alfresco.com/jira/browse/AKU-197
=> AKU-196, AKU-197: Simple workflow appove/reject actions

aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js
This PR addresses a few minor issues I encountered when trying out the DocLib library files on a standalone Aikau client. This was something of a prelude to the work that will be done for https://issues.alfresco.com/jira/browse/AKU-226. I've run a full unit test to verify that these are non-harmful changes
=> Document Library fixes

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SelectTestOptions.js
This PR addressses https://issues.alfresco.com/jira/browse/AKU-220
=> AKU-220: Ensure dynamic option form controls retain value

aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/main/resources/alfresco/services/LoggingService.js, aikau/src/test/resources/alfresco/logging/DebugLogTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/logging/DebugLog.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/logging/DebugLog.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/logging/DebugLog.get.js
Update LoggingService to use new widget and tweak highlight/click behaviour of log rows
=> AKU-158: Add horizontal scrolling to subscription log

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/renderers/Size.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-231
=> AKU-230: Updates to Date renderer

aikau/src/grunt/_config.js, aikau/src/grunt/watch.js, aikau/src/main/resources/alfresco/documentlibrary/views/css/AlfDetailedViewItem.css, aikau/src/main/resources/alfresco/layout/VerticalReveal.js, aikau/src/main/resources/alfresco/layout/css/VerticalReveal.css, aikau/src/main/resources/alfresco/layout/templates/VerticalReveal.html, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/EditableComment.js, aikau/src/main/resources/alfresco/renderers/css/PublishAction.css, aikau/src/main/resources/alfresco/renderers/i18n/CommentsList.properties, aikau/src/main/resources/alfresco/renderers/i18n/EditableComment.properties, aikau/src/main/resources/alfresco/renderers/templates/EditableComment.html, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/VerticalReveal.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/CommentsList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/CommentsList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/CommentsList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CommentsListMockService.js
Addresses most of the issues in [AKU-227](https://issues.alfresco.com/jira/browse/AKU-227). Some of the issues will be moved into separate stories, as they are more appropriately dealt with separately.
=> AKU-227: CommentsList improvements

pom.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-235
=> AKU-235: Switch to 5.0.d Surf artifacts

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js
This is a second attempt at fixing https://issues.alfresco.com/jira/browse/AKU-220. The issue with the previous fix was that I did not verify that the value was actually being set correctly. However, the updated test verifies the correct value on form post.
=> AKU-220: Ensure that pubSub options have correct value set

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-239
=> AKU-239: Update BaseFormControl to ensure empty arrays are considered

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/i18n/ContentService.properties, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CreateContentMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-195
=> AKU-195: Add support for inline edit properties

aikau/src/main/resources/alfresco/documentlibrary/AlfSitesList.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedViewItem.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/main/resources/alfresco/renderers/Comments.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/EditableComment.js, aikau/src/main/resources/alfresco/services/CommentService.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/galleryViewTest.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/CommentsList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CommentsListMockService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-243. I've made some updates to try and make some of the configuration attributes be consistently named. I've fixed some JSHint issues along the way and added better JSDoc where appropriate and updated the unit test to cover the main features of the CommentsList and its associated widgets.
=> AKU-243: Added sorting and pagination to CommentsList

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js
Continuing on from #198, this pull request fixes a small bug in the DebugLog where arrays were being converted into objects and also reduces the occasions when the results dropdown can become disconnected from the main widget. It also fixes some minor Firefox-only testing bugs.
=> AKU-238: MultiSelectInput (further tweaks)

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfCheckableMenuItem.get.desc.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-250.
=> AKU-250: Ensure initial view selection

aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryView.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-257
=> AKU-254: Ensure selection click event is stopped

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/FormControlValidationMixin.js, aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/main/resources/alfresco/forms/controls/TextBox.js, aikau/src/main/resources/alfresco/forms/controls/i18n/FormControlValidationMixin.properties, aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-271 and https://issues.alfresco.com/jira/browse/AKU-272 to make some overdue updates to the NumberSpinner to make it production ready.
=> AKU-271 and AKU-272: NumberSpinner updates

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfTabContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-279. I've removed the JSHint errors from the code, added the missing capabilities, rewritten the existing unit test to the expected style and added a new test that loosely mirrors the use case requested by the Integrations team.
=> AKU-279: TabContainer updates

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-275
=> AKU-275: Ensure button "disabled" attribute is set correctly

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf.xml, aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/core/UrlUtils.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/renderers/_ItemLinkMixin.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/alfresco/services/actions/NodeLocationService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentListTest.js, aikau/src/test/resources/alfresco/services/actions/NodeLocationTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/NodeLocation.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/NodeLocation.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/NodeLocation.get.js, aikau/src/test/resources/testApp/WEB-INF/surf.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-203. This isn't quite complete pending work on AKU-162 (for link creation) so this service will be updated when link creation is supported.
=> AKU-203:Document locate action

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/NavigationServiceMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-281.
=> AKU-281: NavigationService postToPage update

tutorial/chapters/Tutorial1.md, tutorial/chapters/UsingRemoteRepository.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-291
=> AKU-291: Update Tutorial 1 with remote Repo config instructions

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/test/resources/alfresco/renderers/PublishingDropDownMenuTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PublishingDropDownMenuMockService.js
Also adds tests for existing status handlers.
=> AKU-295: Add support for cancelling a request triggered by publishingDropDownMenu

aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocumentList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-289
=> AKU-289: Ensure that PublishingDropDownMenu options are set in list

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/core/PubQueue.js, aikau/src/main/resources/alfresco/core/PubSubLog.js, aikau/src/main/resources/alfresco/services/LoggingService.js
This addresses https://issues.alfresco.com/jira/browse/AKU-284.
=> AKU-284: Error handling and logging updates

aikau/src/main/resources/alfresco/services/ActionService.js
This PR addresses some faulty logic that I introduced in the previous fix for AKU-282
=> AKU-319: Correction to previous fix for AKU-282

tutorial/chapters/Tutorial11.md
I've updated this tutorial chapter so that an important update isn't scrolled off the screen.
=> AKU-311: Tutorial update on pagination

tutorial/chapters/Tutorial2.md
I just updated the reference in the tutorial
=> The config section is now on line 103, I just updated the reference

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/ListRenderer.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FullDocLib/documents.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-330 to provide the ability to scroll to a specific item in a list. Given the lack of UX input I've not made any attempt to provide visual indication as the current Share Document Library does - this can potentially be added in later.
=> AKU-330: Updates to lists to support scrolling to specific item

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/services/CrudServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CrudServiceMockXhr.js
Also adds support to CrudService for it.
=> AKU-317: adds prevent cache support to serviceXhr

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumb.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/AlfTagFilters.js, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumb.css, aikau/src/main/resources/alfresco/renderers/actions/UploadNewVersion.js, aikau/src/main/resources/alfresco/services/CommentService.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/alfresco/renderers/ActionsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/actions/UploadNewVersion.get.js
Just spent a bit of time working through the current Document Library to make sure we hadn't regressed anything and took the opportunity to tidy a few things up.
=> Current Document Library evaluation and updates to ensure it all works

aikau-archetype/src/main/resources/archetype-resources/pom.xml, aikau/pom.xml, aikau/tomcat/context.xml
Can be invoked with the "run" profile: "mvn integration-test -Prun"
Issue raised in AKU-334
=> Add support for running with an embedded Tomcat instead of Jetty.

aikau/package.json
**Revision updates:**
- [grunt-contrib-jshint](https://github.com/gruntjs/grunt-contrib-jshint) (Validates files with JSHint)
- *0.11.1 -> 0.11.2*
- [grunt-jsdoc](https://github.com/krampstudio/grunt-jsdoc) (Generate JSDoc using grunt)
- *0.6.2 -> 0.6.7*
- [grunt-shell-spawn](https://github.com/cri5ti/grunt-shell-spawn) (Run shell commands including background processes)
- *0.3.2 -> 0.3.8*
- [jsdoc](https://github.com/jsdoc3/jsdoc) (Code documentation)
- *3.3.0-beta-3 -> 3.3.1*
**Minor updates:**
- [load-grunt-tasks](https://github.com/sindresorhus/load-grunt-tasks) (Auto-load grunt tasks)
- *3.1.0 -> 3.2.0*
- [time-grunt](https://github.com/sindresorhus/time-grunt) (Display execution time of grunt tasks)
- *1.1.0 -> 1.2.1*
**Major updates:**
- …
=> Update npm dependencies

.gitignore, aikau-archetype/.gitignore, aikau/.gitignore, aikau/src/main/resources/alfresco/misc/AlfTooltip.js, aikau/src/test/resources/alfresco/misc/AlfTooltipTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/misc/AlfTooltip.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-365. These changes come from https://github.com/Alfresco/Aikau/pull/295 but I've checked out Ray's branch and then cherry picked the commits onto a new branch to remove the unwanted master release commits.
=> AKU-365: Improvements and Fixes to AlfTooltip

aikau/pom.xml, aikau/src/test/resources/alfresco/preview/PdfJsPreviewFaultsTest.js
This PR addresses some failing PDF tests that started failing as a result of https://github.com/Alfresco/Aikau/pull/289. I've also made some additional improvements to the unit tests to remove some of the calls to sleep.
=> Fixed failing PDF related unit tests

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/forms/controls/css/CheckBox.css, aikau/src/main/resources/alfresco/forms/controls/templates/BaseFormControl.html, aikau/src/main/resources/alfresco/menus/css/AlfMenuBar.css, aikau/src/test/resources/alfresco/forms/controls/TextBoxTest.js
Left-to-right field row rendering. Minor font size improvements for Alfresco Share consistency.
Layout changes only - no functional modifications.
=> Form CSS improvements. 

aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
A bug has been found which could potentially be causing a loop in the code.
=> AKU-373: Autosave bug

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SearchList.get.js
This fixes up the test failures caused by the previous PR for https://issues.alfresco.com/jira/browse/AKU-66
=> AKU-66: SearchListTest updates

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/forms/controls/css/Select.css
Minor dialog form control styling improvements - round 2
Consistent padding
Less harsh validation message (removal of bold)
Addition of ":" after each label in dialog
=> Dialog form controls styling improvements

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/css/CoreWidgetProcessing.css, aikau/src/main/resources/alfresco/layout/Twister.js, aikau/src/main/resources/alfresco/layout/css/Twister.css, aikau/src/main/resources/alfresco/node/Metadata.js, aikau/src/main/resources/alfresco/node/MetadataGroups.js, aikau/src/main/resources/alfresco/node/css/Metadata.css, aikau/src/main/resources/alfresco/node/templates/Metadata.html, aikau/src/main/resources/alfresco/node/templates/MetadataGroups.html, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/alfresco/node/MetadataGroupsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/node/Metadata.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/node/Metadata.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/node/Metadata.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/node/Metadata.get.properties, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/previews/Audio.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-359 and provides initial widgets for rendering metadata properties on nodes.
=> AKU-359: Initial metadata rendering implementation

aikau/src/test/resources/alfresco/services/UserServiceTest.js
This is a fix (albeit not a great one) for the current failure on the UserService test.
=> Temp fix (for another year) for the User Service test

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/FullScreenMixin.js, aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreview.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreviewPlugin.js, aikau/src/main/resources/alfresco/preview/PdfJs/PDFFindController.js, aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js, aikau/src/main/resources/alfresco/preview/PdfJs/css/PdfJs.css
This PR provides some general tweaks for the next release of Aikau running in Share. Primarily a lot of this focuses on the Aikau PDF.js preview plugin working reliably.
=> Tweaks in preparation for 502RC

aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.js
This PR definitely corrects some errors in the DND code and will hopefully resolve https://issues.alfresco.com/jira/browse/AKU-380 (although I've not been able to reproduce it in the test application).
=> AKU-380: Drag and drop updates

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/services/LoggingService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-385 to ensure that pubSub logging is also filtered along with the other log requests.
=> AKU-375: Logging service updates to filter pubSub logging

aikau/src/main/resources/alfresco/core/_EventsMixin.js, aikau/src/main/resources/alfresco/services/InfiniteScrollService.js, aikau/src/main/resources/alfresco/util/functionUtils.js
This addresses issue [AKU-376](https://issues.alfresco.com/jira/browse/AKU-376) which talks about the nearBottom() test failing for specific elements. The logic has been reworked on this test so that it should hopefully work fine now.
=> AKU-376: InfiniteScrollService

aikau/src/main/resources/alfresco/forms/Form.js
This fixes the current form and hash form unit test failures.
=> Fixed form test failures

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/default.site.configuration.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf-config/configurations/aikau.sample.configuration.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf-config/themes/theme_1-theme.xml, aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/css/StripedContent.css, aikau/src/main/resources/alfresco/logo/css/Logo.css, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLib.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.js
I've worked through the process of creating a new client so that we can showcase some of the recent updates and found the following issues that needed to be resolved
=> Improved client creation experience

aikau/src/main/resources/alfresco/dashlets/Dashlet.js, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/main/resources/alfresco/dashlets/templates/Dashlet.html, aikau/src/test/resources/alfresco/dashlets/DashletTest.js
=> Fix dashlet overflow bugs

aikau/src/main/resources/alfresco/forms/controls/Picker.js, aikau/src/main/resources/alfresco/forms/controls/SitePicker.js, aikau/src/main/resources/alfresco/forms/controls/i18n/SitePicker.properties, aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/main/resources/alfresco/pickers/SitePicker.js, aikau/src/main/resources/alfresco/pickers/i18n/SitePicker.properties, aikau/src/test/resources/alfresco/forms/controls/SitePickerTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SitePicker.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SitePicker.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SitePicker.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/DocumentPickerTestService.js
This addresses issue [AKU-398](https://issues.alfresco.com/jira/browse/AKU-398) which requests the creation of a dedicated SitePicker control.
=> AKU-398: Add a Site Picker

aikau/src/main/resources/alfresco/html/HR.js, aikau/src/main/resources/alfresco/html/css/HR.css, aikau/src/main/resources/alfresco/html/templates/HR.html, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This addresses issue [AKU-367](https://issues.alfresco.com/jira/browse/AKU-367) which requests the creation of an HR widget and is tested by implementing it in the BaseForm test page.
=> AKU-367: Create HR widget

aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js
Update the JSDoc for _PublishPayloadMixin to list potential payload types.
=> Update JSDoc for _PublishPayloadMixin

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/UploadButton.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/documentlibrary/i18n/UploadButton.properties, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/Cell.css, aikau/src/main/resources/alfresco/menus/AlfMenuBarItem.js, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/_ItemLinkMixin.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/CommentsList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-410 in providing the necessary updates to support the dashlet code attached to that JIRA ticket.
=> AKU-410: Updates required for dashlet prototype

aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/logging/DebugLogTest.js
This addresses issue [AKU-18](https://issues.alfresco.com/jira/browse/AKU-18) and implements enabling/disabling of publications and subscriptions individually and also allows filtering by topic.
=> AKU-18: Update DebugLog to make it more useful for testing

aikau/src/main/resources/alfresco/logging/DebugLog.js
Erroneous tag was prevent JSDoc build
=> Fix JSDoc error

aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js
Update ContentService test to add Upload button as well as converting ContentService test page to use DebugLog and make certain selectors less fragile.
=> Update ContentService test to add Upload button

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentFilters.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSitesList.js, aikau/src/main/resources/alfresco/documentlibrary/QuaddsList.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/FilteringSelect.js, aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/menus/AlfDynamicMenuBar.js, aikau/src/main/resources/alfresco/preview/PdfJs/DocumentView.js, aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js, aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js, aikau/src/main/resources/alfresco/services/TagService.js
This addresses issue [AKU-425](https://issues.alfresco.com/jira/browse/AKU-425), which is about resolving all of the highest-priority issues on Sonar. This has been done by fixing JSHint bugs in all files [highlighted by Sonar] and additionally fixing specific bugs mentioned but not picked up by JSHint.
A full test-suite was run successfully before submitting this pull-request.
=> AKU-425: Resolve Sonar Blocker and Critical Issues

aikau/src/main/resources/alfresco/notifications/css/AlfNotification.css, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js
Add missing notification test and restore accidentally removed "position: relative" rule in Notification CSS
=> Missing notification test

aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js
Update Breadcrumb tests to use DebugLog
=> Update Breadcrumb tests to use DebugLog

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfCreateContentMenuItemMixin.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/main/resources/alfresco/services/UploadService.js
Manually tested in MyAlfrescoFiles. Works with upload button, drag onto folder, drag onto document list, create folder.
=> Update response scoping in Core and some Services

aikau/src/main/resources/alfresco/menus/AlfMenuBar.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-456
=> AKU-456: Hover on focused menu bar opens menu drop-downs

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses issue [AKU-458](https://issues.alfresco.com/jira/browse/AKU-458) which notes that the MultiSelectInput cannot be disabled.
=> AKU-458: MultiSelectInput cannot be disabled

aikau/src/test/resources/alfresco/renderers/SearchResultPropertyLinkTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SearchResultPropertyLink.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SearchResultPropertyLink.get.js
This is a follow up PR for https://issues.alfresco.com/jira/browse/AKU-453 to correct a unit test.
=> AKU-453: Test correction

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLib.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-462 to make some improvements with issues that were reported against the My Alfresco Files client based on the doclib.lib.js library. Most of the other issues have been resolved in the current sprint, but this tidies a few other things up.
=> AKU-462: General DocLib related updates

aikau/src/main/resources/alfresco/documentlibrary/i18n/AlfDocumentFilter.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-496 to update a filter label
=> AKU-496: Updated All Documents filter description

aikau/src/main/resources/lib/pdfjs/compatibility.js, aikau/src/main/resources/lib/pdfjs/pdf.js, aikau/src/main/resources/lib/pdfjs/pdf.worker.js
PDF test pages pass - usual source changes made to ensure can still compress with YUI compressor.
NOTE: Alfresco Share also upgraded to 1.1.125 for 5.1
=> PDFjs upgrade to 1.1.125 release

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/forms/controls/css/NumberSpinner.css, aikau/src/main/resources/alfresco/forms/controls/css/Select.css, aikau/src/main/resources/alfresco/header/css/SearchBox.css
This deals with [AKU-452](https://issues.alfresco.com/jira/browse/AKU-452) in adding some further updates around the project CSS to deal with other consequences of changes to defaults.less button variables
=> AKU-452: Aikau buttons update (further updates)

aikau/src/main/resources/alfresco/forms/controls/templates/MultiSelect.html
The label and control were not tied by ID.
=> Accessibility fix - MultiSelect control missing ID

aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/_MultiItemRendererMixin.css, aikau/src/main/resources/alfresco/renderers/css/Actions.css, aikau/src/main/resources/alfresco/renderers/css/Property.css, aikau/src/test/resources/alfresco/lists/views/layouts/RowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListView.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-498
=> AKU-498: Add configurable focus highlight support

aikau/src/main/resources/alfresco/css/less/defaults.less
Update the button colours as per [AKU-520](https://issues.alfresco.com/jira/browse/AKU-520)
=> AKU-520: Change new buttons colour

aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/ListMockService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/ListMockXhr.js
This PR prepares to address issue [AKU-525](https://issues.alfresco.com/jira/browse/AKU-525), however we are still waiting for further reproduction steps. In the meantime, the test page and test class have been updated and a discovered bug has been fixed.
=> AKU-525: AlfHashList loading - Update and fix HashList test page

aikau/src/main/resources/alfresco/services/SearchService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-527
=> AKU-527: allow search APIs to be configured.

aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css
This is a correction to the PR for https://issues.alfresco.com/jira/browse/AKU-528
=> Added missing semi-colon

aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css
Resetting styling that was incorrectly changed as part of the link updates (https://issues.alfresco.com/jira/browse/AKU-528)
=> Another correction to MultiSelectInput

aikau/src/main/resources/alfresco/documentlibrary/i18n/AlfDocumentFilter.properties, aikau/src/main/resources/alfresco/services/i18n/UserService.properties, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js
This PR updates some localization properties based on recommendations from the User Assistance Team.
=> Updates as recommended by the User Assistance Team

aikau/package.json, aikau/src/grunt/coverage.js, aikau/src/test/resources/alfresco/TestCommon.js
This PR addresses some issues that were preventing code coverage data being collected as well as improving the logging.
=> Fixed code coverage issues and improved debug logging

aikau/src/main/resources/alfresco/menus/AlfMenuGroup.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-577 which is an IE9 specific issue found in the Alfresco Share 4.2 codebase. This is a simple port of the fix that has been applied in a 4.2 service pack
=> AKU-577: Port MNT fix from 4.2 codebase

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js
This PR is another attempt to resolve https://issues.alfresco.com/jira/browse/AKU-559. I've used a promise to ensure that we don't attempt to reference widgets until they're actually available.
=> AKU-559: Use promise to ensure filter widgets are available when requested

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-583 to add support for performing an additional publication after a tab is added to the AlfTabContainer.
=> AKU-583: Add support for "publishOnAdd" to AlfTabContainer

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/alfresco/forms/FormFieldFocusOrderTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormFieldFocusOrder.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormFieldFocusOrder.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormFieldFocusOrder.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-604. In truth I was not able to reproduce the failure in a unit test (although I was able to see it on an RM implementation with the French locale) however the change I've added should ensure the problem is resolved and the test added does the appropriate check.
=> AKU-604: Ensure first element in form is focused

aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js, aikau/src/test/resources/alfresco/core/ObjectProcessingMixinTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ObjectProcessingMixin.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ObjectProcessingMixin.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ObjectProcessingMixin.get.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/ObjectProcessingMixinButton.js
Avoid recursion errors in ObjectProcessingMixin. Full test suite run and passed.
=> Avoid recursion errors in ObjectProcessingMixin

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/core/CoreXhrTest.js, aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/alfresco/layout/TwisterTest.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/alfresco/renderers/actions/DeleteActionTest.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/lib/lodash/lodash.compat.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/CoreXhr.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/CoreXhr.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/CoreXhr.get.js, aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This addresses issue [AKU-612](https://issues.alfresco.com/jira/browse/AKU-612), and adds the `Accept-Language` header to all XHR requests. Additionally, it updates the MockXhr capabilities to improve the testing of mocked XHR calls.
=> AKU-612: Accept-Language header should be sent with all XHR requests

aikau/src/main/resources/alfresco/renderers/i18n/PublishingDropDownMenu.properties, aikau/src/main/resources/alfresco/search/i18n/AlfSearchList.properties
This PR addresses the changes requested by the user assistance team for recent message updates.
=> Updates to recent message changes from the user assistance team

aikau/src/main/resources/alfresco/core/topics.js
This update to the JSDoc was suggested in this comment (https://github.com/Alfresco/Aikau/commit/767fd5e7ce161d9da7262d1f77ce2622735c4526#commitcomment-13684342) on a previous commit.
=> JSDoc Update to topics

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/documentlibrary/views/css/AlfFilmStripView.css, aikau/src/main/resources/alfresco/lists/ItemSelectionMixin.js, aikau/src/main/resources/alfresco/renderers/GalleryThumbnail.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/renderers/css/GalleryThumbnail.css, aikau/src/main/resources/alfresco/renderers/css/MoreInfo.css, aikau/src/main/resources/alfresco/renderers/css/Selector.css, aikau/src/main/resources/alfresco/renderers/css/Thumbnail.css, aikau/src/test/resources/alfresco/documentlibrary/DocumentSelectorTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocumentSelector.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-626 to ensure that thumbnails have some highlighting when selected (if requesting to track selection).
=> AKU-626: Added select highlighting on thumbnails

aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-637
=> AKU-637: Prevent draggable nodes in film strip view

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SearchList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-648
=> AKU-648: Override itemKeyProperty in AlfSearchList

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/services/LoginService.js, aikau/src/test/resources/alfresco/core/CoreXhrTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/CoreXhr.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/AuthMockXhr.js
Added authenticationFailureCallback concept to coreXHR for 401 requests with an optional function handler.
Updated LoginService to use the handler.
Updated test page and added Mock service to generate a 401 for testing.
=> Added authenticationFailureCallback concept to coreXHR

aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/AlfFilmStripViewDocument.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/DocumentCarousel.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/FilmStripView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-638 to make it possible to configure the height of the AlfFilmStripView.
=> AKU-638: Previewer height in film strip

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/test/resources/alfresco/forms/controls/DocumentPickerTest.js
This PR is a follow up to the https://issues.alfresco.com/jira/browse/AKU-647 PR to fix bugs found in a full regression test.
=> AKU-647: Update to fix bugs revealed in full regression test

aikau/src/main/resources/alfresco/forms/controls/templates/BaseFormControl.html
This PR addresses https://issues.alfresco.com/jira/browse/AKU-679
=> AKU-679: Remove superfluous title attributes from BaseFormControl template

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/forms/controls/Picker.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/main/resources/alfresco/pickers/Picker.js, aikau/src/main/resources/alfresco/pickers/SingleItemPicker.js, aikau/src/main/resources/alfresco/upload/UploadHistory.js, aikau/src/main/resources/alfresco/upload/UploadTarget.js, aikau/src/test/resources/alfresco/core/RenderFilterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/RenderFilter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-681 to provide the ability to perform token substitution in renderFilter configuration.
=> AKU-681: RenderFilter updates

aikau/resources/grunt/coverage.js
Added a "-" that was missing from the previous code coverage collection PR
=> Added missing "-" from previous PR

aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/test/resources/alfresco/search/NoHashSearchingTest.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/NoHashSearching.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SearchMockService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SearchMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchService/suggestions.json
This PR is the merge from the 1.0.39.1 hotfix release branch into develop. The origina changes have been reviewed once (https://github.com/Alfresco/Aikau/pull/671) but this merge request should be reviewed and approved.
=> AKU-693: Ensure options provided by ServiceStore handle correct scoping

tutorial/chapters/Tutorial17.md
This addresses #675 to correct a mistake in a tutorial
=> Tutorial correction

aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/RenderAppendixSentinel.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/test/resources/alfresco/lists/views/AddableViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AddableViews.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AddableViews.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AddableViews.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/GeneralDataMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/TaggingMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-674 to make it possible to create and "appendix" rendering within a list view.
=> AKU-674: List view appendix rendering

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-702 to remove a superfluous line of code.
=> AKU-702: Removed superfluous line of code

aikau/src/main/resources/alfresco/forms/controls/css/PushButtonsControl.css
AKU-682: PushButtons control Firefox bug - Update CSS to fix bug
=> AKU-682: PushButtons control Firefox bug - Update CSS to fix bug

aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/test/resources/alfresco/upload/UploadTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/Upload.get.js, aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-695
=> AKU-695: Cancel partial upload

aikau/src/main/resources/alfresco/services/ActionService.js
This addresses [AKU-724](https://issues.alfresco.com/jira/browse/AKU-724) and fixed the incorrect function name.
=> AKU-724: Function name error

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/SimplePanel.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/main/resources/alfresco/layout/css/SimplePanel.css, aikau/src/main/resources/alfresco/layout/templates/AlfSideBarContainer.html, aikau/src/main/resources/alfresco/util/domUtils.js, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfSideBarContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/SimpleSideBarContainer.get.js
Fix issue [AKU-707](https://issues.alfresco.com/jira/browse/AKU-707) by repairing and refining the height-resizing code for the sidebar and main area in the AlfSidebarContainer. Also includes some tweaks to the SimplePanel widget. Tests updated and full test suite run successfully.
=> AKU-707: AlfSideBarContainer height problems

aikau/src/main/resources/alfresco/header/SearchBox.js
Factored out the logic for processing of individual data item types (documents, sites, people) into individual overridable methods. This will allow extensions of the component to handle potentially different API results in a more flexible way i.e. not assume the structure of the response is the same for all possible and future APIs.
No functionality has changed, related tests pass and tested against Share 5.1 to ensure LiveSearch performs as expected.
=> Factored out the processing of data items from result processing loops in SearchBox.

aikau/src/main/resources/alfresco/documentlibrary/i18n/_AlfDndDocumentUploadMixin.properties, aikau/src/main/resources/alfresco/forms/i18n/Form.properties, aikau/src/main/resources/alfresco/services/i18n/CloudSyncService.properties, aikau/src/main/resources/alfresco/services/i18n/UploadService.properties, aikau/src/test/resources/alfresco/forms/controls/DisablingSubmitFormTest.js
These are changes to localization messages suggested by the User Assistance team
=> Suggested localization changes from the User Assistance team

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/search/FacetFilters.js, aikau/src/main/resources/alfresco/search/css/FacetFilter.css, aikau/src/main/resources/alfresco/search/templates/FacetFilter.html, aikau/src/test/resources/alfresco/search/FacetFiltersTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/FacetFilters.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-703 to make it possible to make the facet filters have a "full width" click area through configuration.
=> AKU-793: Facet filter config

aikau/src/main/resources/alfresco/forms/controls/ComboBox.js, aikau/src/test/resources/alfresco/forms/controls/ComboBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ComboBox.get.js
This PR adds placeHolder support to the alfresco/forms/controls/ComboBox widget.
=> AKU-742: Added placeHolder to ComboBox

aikau/src/main/resources/alfresco/core/i18n/TemporalUtils_nl.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-754
=> AKU-754: Dutch specific NLS correction

aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html
This addresses [AKU-774](https://issues.alfresco.com/jira/browse/AKU-774) and fixes the filtering in the DebugLog.
=> AKU-774: DebugLog event filtering not working

aikau/src/main/resources/alfresco/menus/AlfDropDownMenu.js
This PR is a further change for https://issues.alfresco.com/jira/browse/AKU-766. This needs to be merged to develop in order to verify against a snapshot build (it is not possible to fix in unit tests).
=> AKU-766: Protect against Firefox specific iframe problems

aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/buttons/DropDownButton.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/buttons/DropDownButton.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/buttons/DropDownButton.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/buttons/DropDownButton.get.properties, aikau/src/main/resources/alfresco/buttons/DropDownButton.js, aikau/src/main/resources/alfresco/buttons/css/DropDownButton.css, aikau/src/main/resources/alfresco/buttons/templates/DropDownButton.html, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/buttons/DropDownButtonTest.js, aikau/src/test/resources/alfresco/buttons/DynamicPayloadButtonTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/DropDownButton.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/DropDownButton.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/DropDownButton.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/DropDownButton.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-676 to add the first iteration on a new alfresco/buttons/DropDownButton widget. Unit test and sandpit page are included.
=> AKU-676: Drop down button

aikau/src/main/resources/alfresco/lists/css/AlfList.css, aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-802 to correct list rendering alignment changes that were introduced during the list rendering refactor. A unit test has been added to replicate the reported error scenario and prevent regressions.
=> AKU-802: Correct list margins on rendered view

aikau/src/test/resources/alfresco/TestCommon.js
=> Revert "AKU-798: BrowserStack work"

aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/core/RenderFilter.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/core/RenderFilter.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/core/RenderFilter.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/webscripts/pages/core/RenderFilter.get.properties
This PR adds a new example page to the Sandpit application to try and provide some detailed coverage of how you can use renderFilter configuration.
=> RenderFilter Sandpit Example

aikau-sandpit-application/.gitignore, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/layout/css/StickyPanel.css, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css
This addresses [AKU-763](https://issues.alfresco.com/jira/browse/AKU-763) and LESSifies the CSS for the two widgets.
=> AKU-763: LESSify StickyPanel and UploadMonitor

aikau/src/main/resources/alfresco/html/Markdown.js
This PR provides some updates on the code review for #815 (that was accidentally merged to early)
=> Updates following code review

aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js
It's not nice when you copy sample and it does not work. :)
=> Fixed typo in the sample for HorizontalWidgets

aikau/src/main/resources/alfresco/lists/views/ListRenderer.js
This PR fixes a test failure encountered prior to the 1.0.54 release.
=> Fix failing FixedHeaderFooter scroll to test

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/FormControls.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/FormControls.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/FormControls.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/FormControls.get.properties
This PR adds a new page for the Sandpit application demonstrating some general form control capabilities.
=> Form Control Sandpit Example

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/_NavigationServiceTopicMixin.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This addresses [AKU-824](https://issues.alfresco.com/jira/browse/AKU-824), which originally came from a submitted PR (#800). It takes the code from the PR, refactors some JSDoc, and adds a unit-test for the changes. Full regression test completed.
=> AKU-824: Named window navigation

aikau/src/test/resources/alfresco/lists/LocalStorageFallbackTest.js
More work on [AKU-811](https://issues.alfresco.com/jira/browse/AKU-811). Fix BrowserStack test failures for Chrome and Firefox on Mac/Windows and IE11 on Windows.
Fixed in this PR: `LocalStorageFallbackTest`
=> AKU-811: Fix BrowserStack test failures (LocalStorageFallbackTest)

aikau/src/main/resources/alfresco/dialogs/i18n/AlfDialog.properties, aikau/src/test/resources/alfresco/services/DialogServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-841
=> AKU-841: Ensure that AlfDialog close button is localized

aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/main/resources/alfresco/renderers/css/PublishAction.css, aikau/src/main/resources/alfresco/renderers/templates/PublishAction.html, aikau/src/test/resources/alfresco/core/PublishPayloadMixinTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/PublishPayloadMixin.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-847
=> AKU-847: Ensure PublishAction honours label configuration

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/test/resources/alfresco/core/ClientPropRenderFilterTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ClientPropRenderFilter.get.js
=> AKU-863: Handle client properties in filterPropertyExists

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js
This addresses issue [AKU-855](https://issues.alfresco.com/jira/browse/AKU-855) whereby warnIfNotAvailable is not working for the Date renderer. Copied code from Property renderer and added appropriate test. Full suite run.
=> AKU-855: warnIfNotAvailable not working for Dates

aikau/.gitignore, aikau/src/test/resources/config/bamboo/Config.js, aikau/src/test/resources/config/bs/Config.js, aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js
Increase timeouts from previous "vm" ones.
=> BrowserStack testing config changes

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/documentlibrary/css/_AlfDndDocumentUploadMixin.css
- Add new less variables for the background / opacity of the dndHighlight elements
- Apply new less variables to _AlfDndDocumentUploadMixin.css to match existing UI
=> AKU-864 - Style change to UploadContainer

aikau/src/test/resources/alfresco/forms/controls/ValidationTest.js
This PR fixes a couple of failures introduced in the re-working of form validation unit tests.
=> AKU-838: Fix failing unit test from previous commit

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/SelectedListItemsExample.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/SelectedListItemsExample.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/SelectedListItemsExample.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/SelectedListItemsExample.get.properties, aikau/src/main/resources/alfresco/forms/controls/SelectedListItems.js, aikau/src/test/resources/alfresco/forms/controls/SelectedListItemsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/test-selectors/alfresco/renderers/Selector.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SelectedListItems.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SelectedListItems.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SelectedListItems.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-882 to provide a new form control that has the value of the items selected in the rendered list. This PR includes tests and Sandpit example
=> AKU-882: Adding alfresco/forms/controls/SelectedListItems

aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js
This PR addresses a minor JShint issue reported by Bamboo
=> Fix JSHint issue

aikau/src/main/resources/alfresco/services/actions/i18n/ChangeTypeService.properties, aikau/src/main/resources/alfresco/upload/i18n/UploadMonitor.properties, aikau/src/test/resources/alfresco/services/actions/ChangeTypeTest.js, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This PR addresses the comments raised by the docs team in #897 and #887
=> AKU-207, AKU-852: Message review updates

aikau/src/main/resources/alfresco/buttons/css/AlfButton.css, aikau/src/main/resources/alfresco/css/less/defaults.less
Add theme hooks for the margin and padding on alfresco-buttons-AlfButton and dijitButtonText to allow them to be manipulated with theme variables.
=> Add new theme hooks for AlfButton

aikau/src/main/resources/alfresco/services/NodePreviewService.js, aikau/src/test/resources/alfresco/services/NodePreviewServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NodePreviewService.get.js
This PR makes some further updates in relation to https://issues.alfresco.com/jira/browse/AKU-869 that update the preview PR #919 . An additional test has been added to verify the code path that was not previously being used.
=> AKU-869: Updates to NodePreviewService following manual testing

aikau/resources/grunt/_config.js, aikau/resources/grunt/preload.js, aikau/resources/grunt/testing.js
Create new grunt preload task to load all test pages once
=> Create new grunt preload task to load all test pages once

aikau/resources/grunt/preload.js
=> Fix JSHint errors

aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js, aikau/src/test/resources/intern_grid.js, aikau/src/test/resources/intern_local.js, aikau/src/test/resources/intern_sl.js
=> Add missing config

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js
It is a commonly held misconception that the DnD FileSystem API has a max limit of 100 items that can be processed per folder level:
See https://productforums.google.com/forum/#!topic/drive/8c-9XvbZDTE
Also https://github.com/owncloud/core/issues/19834
However! It appears it is in reality a slightly esoteric API pattern at fault, not a limitation as per the MDN docs on the subject:
"Continue calling readEntries() until an empty array is returned. You have to do this because the API might not return all entries in a single call."
Refactored the handling to perform the above change. Only affects Chrome folder DnD processing, and has been manually tested.
=> Improvements to folder DnD FileSystem API handling of many entries per folder.

tutorial/chapters/Tutorial6.md
This PR addresses #937 to correct Tutorial 6
=> Issue 937: Tutorial correction

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js
This fixes a JSHint error reported in the build
=> AKU-879: JSHint correction

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/layout/UploadContainer.js
This PR is an update to the previous PR for https://issues.alfresco.com/jira/browse/AKU-879 and addresses upload highlighting for the UploadContainer. It also refines the findScrollParent function to address specific SFS related issues.
=> AKU-879: Updates for UploadContainer DND upload highlighting

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js
Fixed issue with async callback counting.
Improved function names, improved comments and added log output for easier debug.
Tested manually with Chrome, FireFox and IE to validate folder and non-folder dnds.
=> Fixed issue with Chrome folder DnD processing after recent updates. 

aikau/src/main/resources/alfresco/forms/controls/MaskingTextBox.js
This fixes an error in the JSDoc
=> Fix JSDoc issue in MaskingTextBox

aikau/src/main/resources/alfresco/menus/i18n/AlfMenuBarSelectItems.properties, aikau/src/test/resources/alfresco/menus/AlfMenuBarSelectItemsTest.js
This PR requests changes recommended by the user assistance team
=> Updates from the user assistance team

aikau/src/main/resources/lib/pdfjs/compatibility.js, aikau/src/main/resources/lib/pdfjs/pdf.js, aikau/src/main/resources/lib/pdfjs/pdf.worker.js
All previewer unit test pages pass and manual tests of known problem documents all pass.
=> Upgrade to pdf.js-1.3.91 - latest PDF.JS release. 

aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/renderers/PublishPayloadMixinOnActionsTest.js, aikau/src/test/resources/alfresco/renderers/actions/CopyToActionTest.js, aikau/src/test/resources/alfresco/renderers/actions/DeleteActionTest.js, aikau/src/test/resources/alfresco/renderers/actions/ManageAspectsActionTest.js, aikau/src/test/resources/alfresco/renderers/actions/MoveToActionTest.js, aikau/src/test/resources/alfresco/renderers/actions/UploadNewVersionActionTest.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js
This PR fixes unit tests that were not updated in the course of fixing https://issues.alfresco.com/jira/browse/AKU-909.
=> AKU-909: Additional unit test fixes

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/test/resources/alfresco/renderers/DateLinkTest.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/alfresco/renderers/PropertyLinkTest.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/DateLink.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PropertyLink.get.js
This PR addresses https://issues.alfresco.com/jira/browse/MNT-15993 to ensure that the Date renderer (and extending modules) are appropriately encoded. The other Property related modules have been tested and had their unit tests updated to ensure protection against XSS style attacks
=> Property based encoding

aikau/src/main/resources/alfresco/menus/css/AlfMenuBarPopup.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js
This PR adddresses https://issues.alfresco.com/jira/browse/AKU-940 to make a CSS correction
=> AKU-940: Correct CSS for header menu items

aikau/src/test/resources/reporters/ConcurrentReporter.js
Update reporter to show timings for tests. Also some minor tweaks to the output formatting. A full test run was completed without any problems.
=> Testing timing/performance

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js
This addresses JIRA issue [AKU-969](https://issues.alfresco.com/jira/browse/AKU-969), which in turn is about addressing issue #1050 and using PR #1056 to do so, but adding appropriate unit tests.
=> AKU-969: Date renderer i18n

aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.properties
This PR makes some minor updates to the Document Library lib files to support a forthcoming blog post. Some missing properties files have been added and the default upload service has been switched to the FileUploadService
=> Document Library lib file updates

aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/test/resources/alfresco/core/ObjectProcessingMixinTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ObjectProcessingMixin.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ObjectProcessingMixin.get.properties, aikau/src/test/resources/testApp/js/aikau/testing/widgets/ObjectProcessingMixinButton.js
This addresses [AKU-971](https://issues.alfresco.com/jira/browse/AKU-971), which in turn is generated from issue #1059 and pull-request #1061, and adds appropriate tests for all the changes.
=> AKU-971: ObjectProcessingMixin converts array to string (plus enhancements)

aikau/src/test/resources/alfresco/lists/views/layouts/RowModelProcessingTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/RowModelProcessing.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/RowModelProcessing.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/RowModelProcessing.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-976 and provides unit tests for existing capabilities that already existed (but had been forgotten about!)
=> AKU-976: Added test for row model processing

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/main/resources/alfresco/forms/controls/PushButtonsControl.js, aikau/src/main/resources/alfresco/forms/controls/css/PushButtonsControl.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-947 to modify the PushButton styling. A new configuration option called "simpleLayout" has been provided to enable this new styling. As this is a purely cosmetic change the unit tests have not been updated (although the test page has). Existing unit tests still pass.
=> AKU-947: PushButton styling updates

aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js
This PR attempts to make improvements to tests that were unreliable on Firefox.
=> Improvements to unreliable tests

aikau/src/test/resources/alfresco/core/PageTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/MediaFilmStripViewTest.js, aikau/src/test/resources/alfresco/search/SearchSuggestionsTest.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js
This PR addresses some more intermittently failing tests (usually on Firefox) and makes some tweaks to get them passing more reliably.
=> More test fixes

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/main/resources/alfresco/services/UserService.js, aikau/src/main/resources/alfresco/util/urlUtils.js, aikau/src/test/resources/alfresco/services/UserServiceListsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceLists.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceLists.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceLists.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-1003 and https://issues.alfresco.com/jira/browse/AKU-1004 to update the UserService to support filtering, pagination and sorting. Unit tests have been added to verify the new capabilities.
=> AKU-1003: UserService updates

aikau-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf-config/themes/theme_1-theme.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/surf.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/js/acme/HelloWorld.js, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/js/acme/css/HelloWorld.css, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/js/acme/i18n/HelloWorld.properties, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/js/acme/templates/HelloWorld.html, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/js/readme.js
This PR makes some small changes to the Maven Archetype to provide an initial sample widget for reference.
=> Updates to the Maven Archetype to provide a sample widget

aikau/src/main/resources/alfresco/documentlibrary/AlfToolbar.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/services/UserService.js
This PR contains some useful improvements and fixes to the JSDoc for a number of widgets. Links have been fixed and examples have been provided.
=> Improvements to JSDoc

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/SortFieldSelect.js, aikau/src/main/resources/alfresco/lists/SortOrderToggle.js
This PR contains more JSDoc improvements for the AlfSortablePaginatedList, SortFieldSelect and SortOrderToggle widgets.
=> More JSDoc improvements

aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/documentlibrary/views/css/AlfGalleryView.css, aikau/src/main/resources/alfresco/documentlibrary/views/templates/AlfGalleryView.html, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/node/css/Metadata.css, aikau/src/main/resources/alfresco/services/LoggingService.js
This PR is a mixed bag of minor improvements that I noticed needed fixing when working through a demo scenario.
=> Improvements to JSDoc, styling and sort order handling

aikau/src/main/resources/alfresco/services/NavigationService.js
Update on #1143 to complete the fix on https://issues.alfresco.com/jira/browse/AKU-1017
=> AKU-1017: Second attempt at fixing download type actions

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/node/MetadataGroups.js, aikau/src/main/resources/alfresco/node/css/Metadata.css, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/main/resources/alfresco/services/UserService.js, aikau/src/main/resources/webscripts/forms-runtime-tester.get.js
This addresses:
* https://issues.alfresco.com/jira/browse/AKU-1034
* https://issues.alfresco.com/jira/browse/AKU-1029
* https://issues.alfresco.com/jira/browse/AKU-1030
* https://issues.alfresco.com/jira/browse/AKU-1032
In relation to ongoing forms runtime support. No tests added yet as this is still in proof-of-concept phase.
=> Forms runtime support updates

aikau/src/main/resources/alfresco/lists/views/layouts/css/CellContainer.css, aikau/src/main/resources/alfresco/lists/views/layouts/css/Grid.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1021 to address XD requirements raised by RM.
=> AKU-1021: Expanded cell updates

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/i18n/SearchBox.properties, aikau/src/main/resources/alfresco/header/templates/LiveSearch.html, aikau/src/main/resources/alfresco/header/templates/LiveSearchItem.html, aikau/src/test/resources/alfresco/header/SearchBoxTest.js
Add the ability to switch live-search context from Repository to Site when current 'site' is available.
Updating styling to match latest visuals.
Added tests to exercise changes.
=> SHA-1521 Ability to limit the Live search scope

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css
- restore changes that were made in this AKU issue as per RM-3298
=> AKU-945: Updated dialog form control layout [revert]

aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/CopyMove.get.js
This PR updates #1024 to correct and improve the CopyMoveService tests.
=> AKU-1068: Additional test correction

aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/UploadService.js
This is a further update to https://issues.alfresco.com/jira/browse/AKU-1080 to ensure that the UploadService continues to work.
=> AKU-1080: This update ensures that the UploadService works as expected.

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/services/DataListService.js, aikau/src/main/resources/alfresco/services/i18n/DataListService.properties, aikau/src/main/resources/webscript-libs/pages/datalists.lib.js, aikau/src/test/resources/alfresco/renderers/ThumbnailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Thumbnail.get.js
This PR provides an initial implementation of a DataListService. It is not production ready but included for evaluation purposes.
=> Initial drop of DataListService implementation.

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/LayoutMixin.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/main/resources/alfresco/forms/controls/FilePicker.js, aikau/src/main/resources/alfresco/services/DataListService.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/test/resources/alfresco/forms/InitialValuesTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/InitialValues.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/InitialValues.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/InitialValues.get.js
This PR relates to the ongoing work with Data Lists in relation to the FormsRuntimeService. It makes several updates to assist with this working correctly. A full regression test has been run, and additional unit tests add to verify the changes.
=> AKU-1014: Forms and service updates relating to DataLists

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/UserList.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/CellContainer.css, aikau/src/main/resources/alfresco/lists/views/layouts/css/Grid.css, aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/main/resources/alfresco/renderers/Toggle.js, aikau/src/main/resources/alfresco/renderers/templates/Toggle.html, aikau/src/main/resources/alfresco/services/UserService.js, aikau/src/main/resources/webscript-libs/pages/people.lib.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/UserList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/UserList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/UserList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UserMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/User/Following.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/User/Trashcan.json
This PR provides the people.lib.js file for easy rendering of a sample people finder page. There are various associated widget updates and a supporting unit test page.
=> People Page library files and associated updates

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/renderers/Item.js, aikau/src/main/resources/alfresco/renderers/templates/Item.html, aikau/src/main/resources/alfresco/services/BaseService.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/main/resources/alfresco/services/UserService.js, aikau/src/main/resources/webscript-libs/pages/people.lib.js, aikau/src/test/resources/alfresco/lists/views/GalleryViewFocusTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UserMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/User/Follows.json
This PR adds support for retrieving the details of an individual user via the UserService. There is no REST API for this, so instead it is necessary to make a filtered request for users and find the details of the user being sought.
=> Person page support

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/webscript-libs/pages/people.lib.js
This PR contains some tweaks to improve the people.lib.js import file - improvements include thumbnail previews and actions on recent content and better rendering of trashcan actions, as well as a fix for Grid resizing to ensure only immediate grid cells are resized.
=> People Lib Improvements

aikau/src/main/resources/alfresco/forms/css/ControlRow.css, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js
This PR updates the FormsRuntimeService to improve the layout handling when rendering forms, mapping the 2 and 3 column layouts into one or more ControlRows so they appear as expected.
=> AKU-1014: Improved layout handling in FormsRuntimeService

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/renderers/css/Property.css, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/search/CustomSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/CustomSearchResult.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1087 to provide support for highlighting sections of properties, specifically the AlfSearchResult. Unit tests have been updated to verify the change.
=> Feature/AKU-1087: property highlighting

tutorial/chapters/About.md
As suggested in this [issue](https://issues.alfresco.com/jira/browse/ALF-21755) this PR updates the tutorial about section to provide additional information for when things go wrong.
=> Update for when things go wrong

aikau/src/main/resources/alfresco/lists/ItemSelectionMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1093 to resolve the issue of the invert selection operation not working when the gallery view is the initially loaded view in search. The issue was essentially because multiple instances of widgets mixing the ItemSelectionMixin for the same Node were updating the other nodes - because there were multiple views, the widgets on the 2nd view would be changed before processing the invert option which would then switch them back.
=> AKU-1093: Invertion selection issues

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/html/Markdown.js, aikau/src/main/resources/alfresco/navigation/TreeStore.js, aikau/src/main/resources/alfresco/prototyping/Preview.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/js/aikau/testing/UnitTestService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/ListMockService.js
This PR addresses #1254 to update the dependencies of CoreXhr to include Core and to update those modules that were depending upon both CoreXhr and Core to just depend on CoreXhr.
=> Updates to CoreXhr module dependencies

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/search/css/AlfSearchResult.css, aikau/src/main/resources/alfresco/search/templates/AlfSearchResult.html, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1097 to make some style changes to AlfSearchResult and provide support for search term highlighting rendering.
=> AKU-1097: Search term highlighting updates

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/RadioButtons.js, aikau/src/test/resources/alfresco/forms/controls/RadioButtonsTest.js, aikau/src/test/resources/test-selectors/alfresco/forms/controls/RadioButtons.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/RadioButtons.get.js
This PR adds test selectors for RadioButtons and updates the unit tests to make use of them.
=> Added test selectors for RadioButtons

aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/Row.css, aikau/src/test/resources/alfresco/lists/views/layouts/RowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1101 to add support for click handling on Row. Unit tests have been updated.
=> AKU-1101: Support click events on Row

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/Tree.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/navigation/TreeStore.js, aikau/src/main/resources/alfresco/navigation/css/Tree.css, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/CloudSyncService.js, aikau/src/test/resources/alfresco/forms/controls/TreeTest.js, aikau/src/test/resources/alfresco/services/CloudSyncServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TreeField.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TreeField.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TreeField.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path1.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path2.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path4.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1109 to resolve bugs in the Cloud Sync action handling provided by Aikau.
=> AKU-1109:  cloud sync actions

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/imports/sandpit.lib.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/core/PublishPayloadProcessing.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/core/PublishPayloadProcessing.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/core/PublishPayloadProcessing.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/core/PublishPayloadProcessing.get.properties, aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/logging/DebugLog.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1122 to provide a new Sandpit page with detailed examples of how the publications work in Aikau.
=> AKU-1122: Publication Sandpit page

aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1131 to set the correct camel case label style on the Create Link button
=> AKU-1131: Create Link label update

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/ComboBox.js, aikau/src/main/resources/alfresco/forms/controls/FilteringSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/main/resources/alfresco/forms/controls/PushButtonsControl.js, aikau/src/main/resources/alfresco/services/OptionsService.js
This PR contains improvements to the JSDoc
=> JSDoc improvements

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR is a further update to the customization requirements for https://issues.alfresco.com/jira/browse/AKU-1130. This update ensures that additional customization data for creating and editing sites is included in create requests. The unit test has been updated
=> AKU-1130: Updated SiteService to include additional data

aikau/src/main/resources/alfresco/renderers/Toggle.js, aikau/src/test/resources/alfresco/renderers/ToggleTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Toggle.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Toggle.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Toggle.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1140 to fix an issue where a scoped Toggle renderer never gets a response. Unit tests have been added to prevent regressions.
=> AKU-1140: Fixed scoping issues on Toggle

aikau/src/main/resources/aikau/core/BaseWidget.js, aikau/src/main/resources/aikau/core/ChildProcessing.js, aikau/src/main/resources/aikau/lists/views/ListRenderer.js, aikau/src/main/resources/aikau/lists/views/ListView.js, aikau/src/main/resources/aikau/lists/views/layouts/MultiItemRendererMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js
This PR partially addresses https://issues.alfresco.com/jira/browse/AKU-1148 (and also https://issues.alfresco.com/jira/browse/AKU-1149 and https://issues.alfresco.com/jira/browse/AKU-1145) to incrementally make performance related improvements. Currently these changes are mostly confined to the non-backwards compatible "aikau" package. As a fully backwards compatible changes are still being worked on.
=> AKU-1148: First pass at performance enhanced list rendering

aikau/README.md
Adds a table to the distributed readme.md file listing all the 3rd party code used.
=> AKU-1153: 3rd party code table in readme

aikau/src/main/resources/alfresco/renderers/Thumbnail.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1164
=> AKU-1164: Defensive code around border thickness calculation

aikau/src/main/resources/alfresco/lists/views/layouts/Cell.js, aikau/src/test/resources/alfresco/documentlibrary/AlfDocumentActionMenuItemTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentActionMenuItem.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1165
=> AKU-1165: Cell width handling (non-strings with units)

aikau/src/main/resources/alfresco/menus/_AlfPopupCloseMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1167
=> AKU-1167: Added defensive code to work around MS Edge issue

aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/test/resources/alfresco/buttons/ButtonsTest.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/alfresco/lists/views/AlfListViewCaptionTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListViewCaption.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListViewCaption.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListViewCaption.get.js
This PR brings in a bug fix on AlfListView as well as new tests for features recently added to AlfBreadcrumb, AlfButton and AlfListView.
Fixes #1388 - wooo
=> RM-5774: Bug fix and new unit tests

aikau/package.json
Updated grunt-jsdoc dependency from 2.0.0 to 2.2.1
=> Npm dependecies update.

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/services/SearchService.js
Changed Unicode Characters for highlightPrefix and highlightPostfix to avoid sequences like %00 in URLs.
=> Fix/SHA-2197 Faceted Search

aikau/src/main/resources/alfresco/pickers/ContainerPicker.js
Added _removeHiddenViewModes method that filters the menu bar items which should be hidden.
=> MNT-19593: Fixed Move/Copy hidden view issue on faceted search

aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js
See Jira comment: https://issues.alfresco.com/jira/browse/MNT-18112?focusedCommentId=602415&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-602415 for investigation behind this request.
=> MNT-18112 - properly encoded wiki title string

aikau/src/main/resources/alfresco/preview/PdfJs/DocumentView.js
Remove page scroll value for the renderVisiblePages selection algorithm
(cherry picked from commit b64c0233a3babcfff58d86df79fb54a885fec458)
(cherry picked from commit 95e89added07a5fe2335060612fa697fc98ec89d)
=> MNT-21922 : Delay when render preview for farther down the faceted search

aikau/src/main/resources/alfresco/renderers/Selector.js
Added selectProperty to Aikau Selector component.
=> APPS-1026: Added selectProperty to Aikau Selector component

aikau-forms-runtime-support/pom.xml, pom.xml
-Upgrade transative dependencies
=> [MNT-22946] Upgrade spring - RCE databind jdk9
