aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/AlfFilmStripViewDocument.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/Carousel.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-21 which was reporting an error with the prototype film strip view unit test not working. A couple of issues were uncovered, firstly we need to configure in the external Aikau PDF.js previewer plugin (to remove any YUI/Share dependencies) and there was also another issue with clearing out the old previewer on folder navigation. This will need further investigation to address any possible memory leaks in that view, but for now the view is behaving as expected from the user point of view.
=> Fixes for issue

aikau/.jshintrc, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/InlineEditPropertyLink.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js
This pull request addresses https://issues.alfresco.com/jira/browse/AKU-71 which was created to address several usability and functional improvements to be made to the InlineEditProperty (and by extension the InlineEditPropertyLink) controls.
=> AKU-71: Improvements to InlineEditProperty(Link)

aikau/pom.xml, aikau/src/main/ReleaseNotes.txt
I've created an initial release notes file, we can iterate on the style and content in this and future sprints, but I just wanted to get something in place for the time being.
=> AKU-9: Add initial release notes file

aikau-archetype/src/main/resources/archetype-resources/pom.xml, aikau/pom.xml, pom.xml
This PR updates the pom.xml files to place dependencies on Surf libs that are publicly available on the Alfresco Nexus repository that support the standalone Aikau clients and the unit test server. This will make it possible to build a client using Maven without needing to clone and build the Aikau source code (after 1.0.3 is released)
=> AKU-73: Update pom.xml files to use public Surf artefacts

aikau/src/main/resources/alfresco/services/LogoutService.js
This addresses https://issues.alfresco.com/jira/browse/AKU-69 which addresses an issue where issuing the logout POST does not result in a redirect. This ensures that if the logout POST request is successful that a callback is in place to attempt to reload the page (the user authentication will have been removed so they will automatically be redirected). If redirection occurs via the original logout POST then the callback won't be on the page so there shouldn't be an additional reload (e.g. it won't reload the login page having already loaded it)
=> AKU-69: Ensure that LogoutService attempts to refresh the page

aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_de.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_es.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_fr.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_it.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_ja.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_nb.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_nl.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_pt_BR.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_ru.properties, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo_zh_CN.properties, l10n.properties
Strings that remain in English shouldn't be copied to locale specific files (it confuses the QA scripts and creates a maintenance burden) - if the strings don't need translating then the file should be added to the EXCLUDED_FILES list in l10n.properties instead.
I've removed empty files from the same directory, which aren't needed.
I've also intentionally removed the trailing slash on the end of the search path, which has no functional impact but does make the output prettier!
=> AKU-79: Correctly exclude files that shouldn't be translated

aikau/src/test/resources/intern.js, aikau/src/test/vagrant/setup.sh
Force browser versions to match specified ones & not blindly installing the latest.
FF still doesn't work, however, so I've set Intern to use Chrome (which does work with the specified versions).
Firefox and Selenium are still having issues, although there is a fix in progress. Once this ticket has been resolved I suggest you review Sel 2.45 and FF35 for compatibility: https://code.google.com/p/selenium/issues/detail?id=8390
=> AKU-80: Vagrant browser version review

aikau/.jshintrc, aikau/src/main/resources/alfresco/notifications/AlfNotification.js, aikau/src/main/resources/alfresco/notifications/css/AlfNotification.css, aikau/src/main/resources/alfresco/notifications/templates/AlfNotification.html, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This pull request addresses issues https://issues.alfresco.com/jira/browse/AKU-17 and https://issues.alfresco.com/jira/browse/AKU-42, which is about re-implementing notifications after the Aikau separation broke the link to the library that fulfilled the notifications, and also ensures that notifications appear above dialogs.
NOTE: It was not possible to test the z-index visibility using Intern/Selenium, so for the moment this has had to be tested manually.
=> AKU-17 & AKU-42: Implement notifications, and above dialogs

aikau/pom.xml, aikau/src/main/resources/extension-module/aikau-extension.xml
We're going to need this for 1.0.4 to go with Alfresco 5.0.1 updates. This update generates a new Surf extension module in the build which is configured to ensure that the latest version of Aikau that is found will be used. This means that it is only necessary to update pom.xml dependencies rather than re-configuring surf.xml files for each update.
=> Include extension module in Aikau JAR

aikau/.jshintrc
Update JSHint to allow empty blocks
=> Update JSHint to allow empty blocks

aikau/package.json, aikau/src/grunt/_config.js, aikau/src/grunt/linting.js
Add isolated tasks (i.e. not called by anything else) for performing JSHint on the project. Could be integrated into a build process in the future.
=> Add JSHint to project

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/CheckBox.js
This PR addresses an additional issue found when running 1.0.4-SNAPSHOT against 5.0.1 in that it was not possible to create a new search facet. The issue had been introduced as part of the XSS fix and will need an additional update in the 5.0.1 branch when the final 1.0.4 release is specified.
=> AKU-83: Update Checkbox to honour string to boolean conversion requests

aikau/pom.xml
This addresses issue https://issues.alfresco.com/jira/browse/AKU-97, whereby there's a need to ensure the _en.properties files are available for when English is not the default locale.
=> AKU-97: Add en localisation files during build

aikau/src/main/resources/alfresco/pickers/css/Picker.css
This issue addresses https://issues.alfresco.com/jira/browse/AKU-96 which refers to an aesthetics-only bug in IE. Creating an automated test for this is impractical, so it has been tested manually, before and after the commit, and passes manual testing.
=> AKU-96: Copy to form in IE has bug

README.md
This PR partially addresseshttps://issues.alfresco.com/jira/browse/AKU-77. The majority of the work has been done directly in the  Wiki, however this PR modifies the readme file to add a link to the criteria and removes the warning message at the start (as it's no longer true)
=> AKU-77: Updated read me to link to contribution acceptance criteria

aikau/src/main/resources/alfresco/forms/controls/ContainerPicker.js, aikau/src/main/resources/alfresco/forms/controls/Picker.js, aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/navigation/TreeStore.js, aikau/src/main/resources/alfresco/pickers/ContainerPicker.js, aikau/src/main/resources/alfresco/pickers/Picker.js, aikau/src/test/resources/alfresco/forms/controls/ContainerPickerTest.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/ContainerListPicker.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ContainerPicker.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/ContainerListPickerMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PathTreeMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/ContainerListPicker/DocumentLibrary.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/ContainerListPicker/RecentSites.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/ContainerListPicker/Site.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/PathTree/BudgetFiles.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/PathTree/DocumentLibrary.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/PathTree/Site.json
This issue addresses https://issues.alfresco.com/jira/browse/AKU-81. It swaps out the previously used "alfresco/pickers/ContainerListPicker" with an "alfresco/navigation/PathTree" to make it possible for root container in empty sites to be selected.
Additional updates to the PathTree include the ability to swap out names for descriptions when a node has the st:siteContainer aspect applied as well as the ability to filter specific paths via RegEx.
Unit tests have been added for the PathTree and the ContainerPicker widgets
=> AKU-81: Update Container Pickers to use PathTree

aikau/src/main/resources/alfresco/header/i18n/AlfSitesMenu.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-109. Just corrects a couple of typos that have been spotted.
=> ALF-109: Correcting typos in AlfSitesMenu

aikau/src/main/resources/alfresco/notifications/AlfNotification.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-105, where notifications for users joining a site were not correctly displaying. They now display properly and, when the notification hides, the page is automatically reloaded.
=> AKU-105: Site-join notification not displayed

aikau/src/main/resources/alfresco/header/SetTitle.js, aikau/src/main/resources/alfresco/header/Title.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.properties
Addresses https://issues.alfresco.com/jira/browse/AKU-103. Updated both the Title and SetTitle widgets to check for localized versions of supplied strings. Also added better support for document title prefixing. Updated the unit tests to conform to best practices and added unit tests for new features.
=> AKU-103: Updated title handling to be localized.

aikau/.gitattributes
Add a new .gitattributes file to force all line endings for the repo to be "lf". For more info, see https://help.github.com/articles/dealing-with-line-endings.
=> Fix line endings

aikau/src/grunt/shell.js, aikau/src/grunt/vagrant.js, aikau/src/main/resources/alfresco/core/ObjectProcessingMixin.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/SimplePicker.js, aikau/src/main/resources/alfresco/pickers/PickedItems.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/actions/ManageAspectsService.js, aikau/src/main/resources/alfresco/services/actions/i18n/ManageAspectsService.properties, aikau/src/test/resources/alfresco/forms/SingleTextFieldFormTest.js, aikau/src/test/resources/alfresco/forms/controls/DocumentPickerTest.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/ManageAspectsMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/ManageAspects/ConfiguredAspects.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/ManageAspects/UpdateSuccess.json
This addresses https://issues.alfresco.com/jira/browse/AKU-41 and adds support for handling Manage Aspects in Aikau. It also fixes up some failing unit tests and makes a minor adjustment to the Vagrant Grunt commands (because provisioning is required after starting the VM).
=> AKU-41: Add support for Manage Aspects action

aikau/src/main/resources/alfresco/lists/views/layouts/Cell.js, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/test/resources/alfresco/lists/views/layouts/RowTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.js
This PR address both https://issues.alfresco.com/jira/browse/AKU-101 and https://issues.alfresco.com/jira/browse/AKU-72 and updates the Cell and Row view layout widgets to allow additionalCssClasses (on the Row) and colspan (on the Cell) attributes to be set.
=> AKU-72, AKU-101: Updates to row and cell view layout widgets

README.md, aikau/src/main/ReleaseNotes.md
This PR updates the release notes for 1.0.6 (and adds the forgotten release notes for 1.0.5) as well as updating the main readme to provide links to the new setup instructions
=> Update release notes for 1.0.6

aikau/.gitignore, aikau/src/main/resources/alfresco/forms/controls/TextArea.js, aikau/src/main/resources/alfresco/forms/controls/TextBox.js, aikau/src/main/resources/alfresco/forms/controls/css/TextArea.css
This ensures default CSS (for border etc.) of TextArea is same as other HTML form controls such as TextBox and that additionalCssClasses can be used.
(attempt 2)
=> Added additionalCssClasses support to TextArea and default CSS requirements.

aikau/src/main/resources/alfresco/debug/WidgetInfo.js, aikau/src/main/resources/alfresco/debug/i18n/WidgetInfo.properties, aikau/src/main/resources/alfresco/debug/templates/WidgetInfo.html, aikau/src/test/resources/alfresco/debug/WidgetInfoTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/debug/WidgetInfo.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/debug/WidgetInfo.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/debug/WidgetInfo.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-127 to ensure that alt text is generated for WidgetInfo widgets. I've also added a unit test (sorry, tests start with "Test"... can't help myself!)
=> AKU-127: Added alt text for WidgetInfo and added a unit test

aikau/src/test/resources/alfresco/.jshintrc, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-13 and adds unit testing for the previous stacked dialogs work. Also, new .jshintrc file is added to deal with the fact that the tests run in a non-browser environment.
=> AKU-13: Add support for stacked dialogs

aikau/Gruntfile.js, aikau/package.json, aikau/src/grunt/shell.js, aikau/src/grunt/vagrant.js
Update Grunt to show time taken to complete tasks. Update Vagrant to tweak the "grunt vup" task and also to add a "grunt vrestart" task.
=> Tweaks to Grunt and Vagrant

aikau/src/main/resources/alfresco/lists/KeyboardNavigationSuppressionMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/EditableRow.js, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/test/resources/alfresco/lists/views/layouts/EditableRowTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/EditableRow.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/EditableRow.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/EditableRow.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-124 and adds a new widget and unit test that allows rows to be created with an edit mode that can be toggled into. This mode suppresses keyboard navigation handling to ensure that users can enter data into forms, etc.
=> AKU-124: Added alfresco/lists/views/layouts/EditableRow widget with unit test

aikau/.csscomb.json, aikau/src/grunt/http.js, aikau/src/grunt/shell.js, aikau/src/grunt/testing.js, aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/i18n/CrudService.properties, aikau/src/main/resources/alfresco/services/i18n/NotificationService.properties, aikau/src/test/resources/alfresco/services/CrudServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CrudServiceMockXhr.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-134 which highlights that there is no failure callback on the CrudService, meaning errors can be swallowed. Also includes a single-line (non-breaking) tweak to the CSSComb settings [optional CSS formatting plugin].
=> AKU-134: CrudService: failureCallback support

aikau/src/main/resources/alfresco/documentlibrary/AlfCreateContentMenuItem.js, aikau/src/main/resources/alfresco/documentlibrary/AlfCreateTemplateContentMenu.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/actions/CreateTemplateContentService.js, aikau/src/main/resources/alfresco/services/actions/i18n/CreateTemplateContentService.properties, aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/CreateContent.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CreateContentMockXhr.js
This addresses https://issues.alfresco.com/jira/browse/AKU-27 and adds support for the creation of nodes via folder templates. The behaviour mirrors the current behaviour in Alfresco Share in that the user is prompted to optionally provide overrides for the space template name, title and description. The create content unit test has been updated to test the new features.
=> AKU-27: Add support for folder template creation

aikau/src/main/resources/alfresco/html/Heading.js, aikau/src/test/resources/alfresco/html/HeadingTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Heading.get.js
This is an updated version of https://github.com/Alfresco/Aikau/pull/72 with the latest code from "develop" integrated.
Based on code for alfresco/html/Label that already does a similar job. Uses the standard subscriptionTopic channel and updates the text of the inner heading node.
=> Added dynamic update of label text to alfresco/html/Heading component

aikau/src/main/resources/alfresco/buttons/AlfDynamicPayloadButton.js, aikau/src/test/resources/alfresco/buttons/DynamicPayloadButtonTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/dynamicPayloadButton.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/dynamicPayloadButton.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/dynamicPayloadButton.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-142 and adds the missing unit test for the alfresco/buttons/AlfDynamicPayloadButton as well as adding in additional hash fragment supporting capabilities.
=> AKU-142: Updates to  AlfDynamicPayloadButton

tutorial/chapters/Contents.md
Contents page didn't link to the newly published tutorial chapters
=> Fix missing links to published chapters

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormDialogMockService.js
This addresses https://issues.alfresco.com/jira/browse/AKU-155. I hit a couple of test failures along the way due to an initial change I made to Core.js, which is why there are some JSHint related corrections to the PdfJs file. All unit tests passing though.
=> AKU-155: Added support for improved form dialog failure handling

aikau/src/main/resources/alfresco/header/css/SearchBox.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-164. It makes the SearchBox selector for setting height of menu items more specific to ensure that the correct height is maintained when the SearchBox is used inside the alfresco/header/Header layout widget.
=> AKU-164: Added more specific CSS selector to ensure that it "wins"

aikau/src/grunt/watch.js, aikau/src/main/resources/alfresco/header/Title.js, aikau/src/main/resources/alfresco/header/css/Title.css, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Title.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Title.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Title.get.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-150 where long site names caused display issues on narrow browsers. This has been implemented by permitting a new maxWidth property to be passed through to the alfresco/header/Title control.
=> AKU-150: Calendar display issues with long site name

aikau/src/main/resources/alfresco/forms/controls/HiddenValue.js, aikau/src/test/resources/alfresco/forms/controls/AutoSetTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/AutoSet.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-157 and ensures that the alfresco/forms/controls/HiddenValue form control can be set initially and via form value update. The unit tests have been updated to verify.
=> AKU-157: Updates to ensure that HiddenValue form control values can be set

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.properties
This issue addresses https://issues.alfresco.com/jira/browse/AKU-171 it seems like the fixed options already do go through NLS processing, but I've updated the test page to add a WebScript properties file and make use of it. The existing test case already validates that the label is correct.
=> AKU-171: Updated test page to use localization for fixed options

aikau/src/main/resources/alfresco/core/CoreXhr.js
Added developer warning when XHR defaultSuccessCallback called but no requestConfig.alfTopic has been set.
=> Added developer warning

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/header/templates/LiveSearch.html, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-172 and updates the alfresco/header/SearchBox widget to make it much more configurable. The unit test has been upated to verify the changes.
=> AKU-172: Updates to SearchBox to make it more configurable

aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-176 which reports that only non-form dialogs were honouring the contentWidth and contentHeight payload configuration. This has been fixed and the unit test updated to verify and prevent future regressions.
=> AKU-176: Ensure that form dialog honours contentWidth and contentHeight

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This takes over from https://github.com/Alfresco/Aikau/pull/126
This now at least functions for IE8 and IE9 (as well as sensible browsers) although it does look a bit poor at the moment, but unfortunately accessibility trumps styling. I think that we need to either not attempt styling via CSS for now. But I'd like this pulled and experimented with before the end of the sprint and we can then decide if there are better approaches to addressing this.
=> Dialog updates

aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedView.js, aikau/src/main/resources/alfresco/layout/VerticalReveal.js, aikau/src/main/resources/alfresco/layout/css/VerticalReveal.css, aikau/src/test/resources/alfresco/documentlibrary/views/AlfDetailedViewTest.js, aikau/src/test/resources/alfresco/layout/VerticalRevealTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/reporters/AikauReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/VerticalReveal.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/VerticalReveal.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/VerticalReveal.get.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-177 which is about making sure only one comments list opens on the page at once in the AlfDetailedView widget. It also contains a tweak to the VerticalReveal behaviour, and a new test for that widget.
=> AKU-177: Inline comments scoping

aikau/src/test/resources/alfresco/preview/PdfJsPreviewFaultsTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-180. I think that I've established that the cause of the intermittent failures was that the test was written in such a way that it relies on a specific time (500ms) being the correct delay between a faulty password being submitted and the password dialog being recreated. 
I've tried to improve this test by counting the number of request for dialogs to be created rather than whether or not the dialog is displayed at the precise moment its selected.
=> AKU-180: Pdf Preview Faults test

aikau/pom.xml, aikau/src/test/java/org/alfresco/aikau/UnitTestList.java, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/UnitTestList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/UnitTestList.get.json.ftl, aikau/src/test/resources/testApp/WEB-INF/config/web-application-config.xml
This addresses https://issues.alfresco.com/jira/browse/AKU-183. Rather than manually creating a page that would require updating, I've taken the approach of creating a Java backed WebScript to retrieve all the unit test WebScripts in the "/aikau-unit-tests" family.
Currently this new WebScript isn't supporting sorting or pagination, and many of the test page WebScripts will need to have their shortname and description fields updated. These are all outside of the scope of this issue though and can be addressed iteratively going forwards
=> AKU-183: Unit test page list page

aikau/src/main/resources/alfresco/services/LoggingService.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/config/grid/Config.js, aikau/src/test/resources/config/loc/Config.js, aikau/src/test/resources/config/sl/Config.js, aikau/src/test/resources/config/vm/Config.js, aikau/src/test/resources/intern_grid.js, aikau/src/test/resources/intern_local.js, aikau/src/test/resources/reporters/AikauReporter.js
This addresses issue https://issues.alfresco.com/jira/browse/AKU-3 which requires support for Selenium Grid testing our unit tests. The intern config for the grid has been updated, redundant properties have been removed from all testing code (e.g. bootstrapBaseUrl and moduleDeploymentBaseUrl), and the AikauReporter has been updated to handle Grid errors/output.
=> AKU-3: Update config to allow Selenium Grid testing

aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/java/org/alfresco/aikau/UnitTestList.java, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/UnitTestList.get.json.ftl, aikau/src/test/resources/testApp/index.jsp
These changes improve the initial unit test index page implemented for AKU-183 by sorting on WebScript shortname and providing pagination support.
=> Updated the unit test list service and page to support pagination

aikau/src/test/resources/alfresco/dnd/FormCreationTest.js
This fixes the DND test failing by using the keyboard to ensure that the target elements can be reached.
=> Fixed form creation DND test failure

aikau/src/main/resources/alfresco/header/css/Title.css
This addresses https://issues.alfresco.com/jira/browse/AKU-150. Unfortunately this is an issue where we really should have a Share specific title bar widget (that extends LeftAndRightWidgets) but unfortunately we've somewhat ended up with Share specific styling in the CSS. This definitely fixes the issue, but if I have time later in the sprint I might revisit and add a new title widget for use in Share and other clients. If not I'll raise an issue to address in a future sprint.
=> AKU-150: Updated CSS for title bar

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.properties
This addresses https://issues.alfresco.com/jira/browse/AKU-193. It looks like we were unnecessarily running the options through the message processing more than once which was double encoding localized values.
=> AKU-193: Fixed double encoding issue with form control options

aikau/src/grunt/_config.js, aikau/src/grunt/testing.js, aikau/src/grunt/watch.js, aikau/src/main/resources/alfresco/logging/css/SubscriptionLog.css, aikau/src/main/resources/alfresco/logging/templates/SubscriptionLog.html, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/test-page.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/unit-test-template.ftl, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css
* Updates and improvements to the layout of the test pages
* Add 10px padding to body
* Add caption to subscription log table
* Add background colour to MockXHR and Subscription log table headers
* Add new grunt task - "watchDev"
* Will detect changes to app code or test webscripts
* Updates the test app, clear all caches, and reloads open test pages
=> Testing updates (watch task, CSS)

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/pickers/ContainerListPicker.js, aikau/src/main/resources/alfresco/pickers/ContainerPicker.js, aikau/src/main/resources/alfresco/pickers/DocumentListPicker.js, aikau/src/main/resources/alfresco/pickers/Picker.js, aikau/src/main/resources/alfresco/pickers/SingleItemPicker.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties, aikau/src/test/resources/alfresco/forms/controls/ContainerPickerTest.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ContainerPicker.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/CopyMove.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/CopyMove.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/CopyMove.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CopyMoveServiceMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CopyMoveService/Copy.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CopyMoveService/Move.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-216 but also extracts the existing code from the ActionService so that it can be used independently and adds in unit tests that were previously missing.
=> AKU-216: Support Repo home configuration

aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-163.
I've added a new configuration attribute to AlfHashList called "mapHashVarsToPayload" which is configured to be true (the default is false for backwards compatibility) then any keys defined in the "hashVarsForUpdate" array that are found in the changed URL hash will automatically be added to the load data payload.
=> AKU-163: Update AlfHashList to map hash vars to load data payload

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-221. I've made the decision not to add a unit test for this fix because it is simply exposing configuration that is already supported by the underlying Dojo DND framework. There seems little value in adding an explicit test for it.
=> AKU-221: Prevent DragAndDropItems from accepting items

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/dnd/DroppedNestingItemWrapper.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-219 to ensure that nested single use items are re-instated when the nesting item is deleted. This also fixes keyboard navigation issues around adding single use items that were detected when fixing this issue.
=> AKU-219: Ensure that nested single use items are re-instated on deletion

aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-230 and ensures that the InlineEditProperty renderer can use the renderOnNewLine configuration without corrupting the location of the edit icon
=> AKU-230: Ensure renderOnNewLine works properly for InlineEditProperty

aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/main/resources/alfresco/forms/controls/utilities/UseServiceStoreMixin.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/MultiSelectInputTest/tags.json
Two issues I discussed with @MartinDoyleUK:
1) RegExp string injection is fragile if the string contains any RegExp special chars (e.g. brackets). I've fixed this to escape the string first
2) MultiSelectInput shouldn't require the matching result to start with the search term, so I've added an option to the service store to turn that off.
Tests included.
=> ServiceStore: Fixes RegExp error and adds search type option (used in MultiSelectInput)

aikau/src/main/resources/alfresco/services/CrudService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-245 to ensure that all messages generated by the CrudService get localized. I've not added a unit test for this as it seems superfluous and is likely to be covered by other unit tests (e.g. editing/deleting comments, etc)
=> AKU-245: Localize the CrudService messages

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/lists/ResultsPerPageGroup.js, aikau/src/main/resources/alfresco/menus/AlfMenuBarSelect.js, aikau/src/test/resources/alfresco/CodeCoverageBalancer.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js, tutorial/chapters/Tutorial11.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-242 and updates the alfresco/lists/Paginator widget to support configurable page sizes. Unit tests, JSDoc and JSHint fixes are included.
=> AKU-242: Paginator page size menu configuration

aikau-archetype/src/main/resources/archetype-resources/pom.xml
This should have been included in the previous PR for https://issues.alfresco.com/jira/browse/AKU-235
=> AKU-235: Update archetype pom.xml to use 5.0.d

aikau/src/main/resources/alfresco/core/JsNode.js, aikau/src/main/resources/alfresco/core/NodeUtils.js, aikau/src/main/resources/alfresco/renderers/SmallThumbnail.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/i18n/ActionService.properties, aikau/src/main/resources/alfresco/services/i18n/ContentService.properties, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CreateContentMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-232. I'm continuing to move actions out of the ActionService and into more appropriate services so that they can be easily called outside of the Document Library. I've made the fix originally required for the issue and added a unit test that was missing for the delete action (and a few JShint fixes along the way).
=> AKU-232: ActionService update and test

aikau/src/main/resources/alfresco/services/DialogService.js, tutorial/chapters/Tutorial7.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-225. I've updated the JSDoc to include all the appropriate properties of the payloads for both topics and provided examples of how to use them. Note the new approach to defining and linking events... I've discussed this with David W. and we've agreed this is the best way to move forwards with documenting the topics/payloads.
=> AKU-225: Update to JSDoc and tutorial for DialogService

aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css
This PR corrects the previous fix for https://issues.alfresco.com/jira/browse/AKU-230
=> AKU-230: Correction to InlineProperty renderOnNewLine fix

aikau/src/grunt/testing.js, aikau/src/grunt/watch.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css, aikau/src/main/resources/alfresco/forms/controls/templates/MultiSelect.html, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js, aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This addresses issue [AKU-238](https://issues.alfresco.com/jira/browse/AKU-238), which highlights that MultiSelect options are hidden when the control is inside a dialog. It has been fixed by moving the dropdown to be a body-level element with a higher-than-Dojo z-index (1000).
This pull request also includes updates to TestCommon, specifically a new session method to make querying the pub/sub log simpler, as well as minor tweaks to the Grunt config and the MockXHR log.
=> AKU-238: MultiSelectInput options are partially hidden if included in dialog

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/test/resources/alfresco/core/RenderFilterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/RenderFilter.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/RenderFilter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-268. It updates the renderFilter configuration to support "contains" and "containsAll" attributes so that it is possible to check arrays for one or all values. I've not updated the JSDoc this time because it's a mixin class and it would be slightly buried - I'll need to add a new tutorial chapter or write a blog post to document this in a useful way.
=> AKU-266: Updated renderFilter processing to handle array targets

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/services/ActionServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ActionService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ActionService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ActionService.get.js
This addresses issue [AKU-248](https://issues.alfresco.com/jira/browse/AKU-247) where an incorrect property path was meaning that selection changes were not being published, and adds tests for the appropriate methods in the ActionService. There are also some fixes to the DebugLog and the TestCommon method that uses it.
=> AKU-247: Selected items drop-down not enabled when options are selected

aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/main/resources/alfresco/services/RatingsService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/renderers/SocialRenderersTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SocialRenderers.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SocialRenderers.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SocialMockXhr.js
This PR addresses AKU-251 (and in part AKU-254) to support the adding and removal of favourites on an Aikau client that is independent of Share. Existing YUI/Share code dependencies have been removed and ported into the Aikau code base. The unit tests have been updated to include tests for both the PreferenceService and RatingsService and the doclib.lib.js has been updated to make it easier to get the list of services required for using the Document Library.
=> AKU-251: Update PreferenceService for favourites

aikau/src/main/resources/alfresco/services/actions/CreateTemplateContentService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-254 to make a couple of final tweaks to get templated content creation working. A request is published to refresh content after creation, and the folder url is set correctly.
=> AKU-254: Updates to create templated content

aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfSideBarContainer.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfSideBarContainer.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-253. As well as setting better defaults for the sidebar width in general (and in the document library) it updates how preferences are handled to ensure preferences are requested when the PreferenceService is created.
=> AKU-252: Update sidebar width and preference handling

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js
This addresses issue [AKU-248](https://issues.alfresco.com/jira/browse/AKU-248) which requires that changing a filter, category, tag or path on a paginated list should reset the list to page 1. It also adds a clear button to the DebugLog.
=> AKU-248: Selecting a filter doesn't reset page to 1

aikau/src/main/resources/alfresco/renderers/ReadOnlyTag.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js
This addresses issue [AKU-249](https://issues.alfresco.com/jira/browse/AKU-249), which requires a change to the payload of the `ReadOnlyTag#postCreate()` method and an update to its test.
=> AKU-249: Tag renderer doesn't set correct hash

aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js
This addresses issue [AKU-252](https://issues.alfresco.com/jira/browse/AKU-252) by changing the default width of the create content dialog and also adjusting the size of the XML editor to match the default HTML editor size.
=> AKU-252: Create content dialog isn't wide enough

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SocialRenderers.get.js, aikau/src/test/resources/testApp/js/aikau/testing/WaitForMockXhrService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SocialMockXhr.js
Updates to improve ensuring that mock XHR services are setup before creating widgets and services for the test.
In this case we need to create the PreferenceService once the mock XHR service is ready to accept the request that it immediately makes to get the user preferences.
=> Fix SocialRenderersTest

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/main/resources/alfresco/layout/SimplePanel.js, aikau/src/main/resources/alfresco/layout/templates/SimplePanel.html, aikau/src/main/resources/alfresco/services/LoggingService.js, aikau/src/main/resources/alfresco/services/UploadService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-273 to ensure that dialog body grows sensibly when content is progressively revealed. A max height is set based on the size of the view port and scroll bars are added when the content height exceeds it. There's still some further improvements that we can iterate on here in the future (such as repositioning) but this should be enough to satisfy the bug fix.
=> AKU-246: Resolve dialog size issues

aikau/src/main/resources/alfresco/forms/controls/Select.js, aikau/src/main/resources/alfresco/forms/controls/css/Select.css, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js
This addresses issue [AKU-274](https://issues.alfresco.com/jira/browse/AKU-274), which talks about odd styling of the Select control in a specific circumstance. The problem is twofold, both aesthetic (selected styling was grey text, now changed to bold) and functional (options with empty values are unsupported by the underlying Dojo control, now prevented). Also includes a small tweak to prevent XSS scripting tests from breaking the DebugLog and very minor refactor inside TestCommon.
=> AKU-274: Odd styling in alfresco/forms/controls/Select

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This addresses issue [AKU-277](https://issues.alfresco.com/jira/browse/AKU-277), which notes a regression in the keyboard navigation of the MultiSelect. This was due to a leftover reference from the old widget DOM model and has been updated accordingly. A test has been added to ensure any future regression would be detected. Also a small tweak to default the MockXHR log to collapsed, in order for test "screenies" to be more useful.
=> AKU-277: MultiSelect keyboard navigation not working

aikau/pom.xml, aikau/src/main/resources/alfresco/core/NotificationUtils.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/header/templates/LiveSearchItem.html, aikau/src/main/resources/alfresco/lists/KeyboardNavigationSuppressionMixin.js, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/i18n/SiteService.properties, aikau/src/main/resources/extension-module/aikau-extension.xml, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js, aikau/src/test/resources/alfresco/services/actions/SimpleWorkflowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js, aikau/src/test/resources/testApp/WEB-INF/surf.xml, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This PR addresses https://issues.alfresco.com/jira/browse/AKU-19 in moving Aikau up to use Dojo 1.10.4.  The unit tests revealed some issues following the upgrade which have been resolved in this PR. Unit tests are now all passing. I've also done a sniff test against Share and it also seems to be functioning as expected.
=> AKU-19: Upgrade to Dojo 1.10.4

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css, aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/reporters/AikauReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/MultiSelectMockService.js
This addresses issue [AKU-280](https://issues.alfresco.com/jira/browse/AKU-280) by offering three new configuration options:
`choiceCanWrap`: Defaults to true, but can be set to false to prevent the text within choices from wrapping to the next line. Any overflow will be hidden by an ellipsis
`choiceMaxWidth`: The maximum width of choices. This defaults to 100%, but can take any CSS max-width value
`labelFormat`: Allows specification of custom label formats by permitting format strings, where item properties can be wrapped in curly-braces. Can specify some or all of `choice`, `result` and `full` for displaying in the chosen items, the results dropdown or the title attribute of both respectively.
This also makes some modifications to the ServiceStore (bug-fix, function externalisation and …
=> AKU-280: MultiSelect should handle long items better

aikau/pom.xml, aikau/src/main/resources/alfresco/services/CommentService.js, aikau/src/main/resources/webscripts/sanitize-response.get.desc.xml, aikau/src/main/resources/webscripts/sanitize-response.get.js, aikau/src/main/resources/webscripts/sanitize-response.get.json.ftl
This PR addresses https://issues.alfresco.com/jira/browse/AKU-244. 
I've created a new proxy WebScript that accepts URIs for Alfresco Repository REST APIs and runs a single property of each item through the stripUnsafeHTML() function. This is currently limited in that it only sanitizes a single attribute attribute and nested attributes can't be used with dot-notation properties.
However, I think we can live with these limitations initially and iterate as the use-cases arise. I've done manual testing to verify it works, but have not provided an automated test because we have no satisfactory way of testing WebScripts at the moment.
The CommentService has been updated to make use of this new proxy WebScript and I have verified that it works as expected.
=> AKU-244: Sanitize HTML proxy WebScript

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/layout/StripedContent.js, aikau/src/main/resources/alfresco/layout/css/StripedContent.css, aikau/src/test/resources/alfresco/layout/StripedContentTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StripedContent.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StripedContent.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StripedContent.get.js
This addresses issue [AKU-278](https://issues.alfresco.com/jira/browse/AKU-278) which is a feature request for a new style of layout widget called "striped content", which is a stylable, full-width container with a centred, fixed-width content.
=> AKU-278: Add "striped content" widget

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumb.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumb.css, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumbTrail.css, aikau/src/main/resources/alfresco/documentlibrary/templates/AlfBreadcrumb.html, aikau/src/main/resources/alfresco/documentlibrary/templates/AlfBreadcrumbTrail.html, aikau/src/main/resources/alfresco/documentlibrary/views/AlfTableView.js, aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/_NavigationServiceTopicMixin.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/core/PublishPayloadMixinTest.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/alfresco/renderers/DateLinkTest.js, aikau/src/test/resources/alfresco/renderers/SearchResultPropertyLinkTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/PublishPayloadMixin.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/DateLink.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-262 to make the breadcrumb trail more abstract and useful for purposes (so that it isn't coupled to the document library) as well as making some styling updates.
=> AKU-262: Breadcrumb updates

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/services/OptionsService.js
Combined with a minor fix to remove a trailing comma.
=> JSDoc wouldn't compile. types can't have a description.

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/MultiSelectMockService.js
This addresses issue [AKU-283](https://issues.alfresco.com/jira/browse/AKU-283), which had an occasional problem with the Loading... message not disappearing when selecting a control. This was caused by a double search request triggering a bug inside the `ServiceStore` which meant that the later response handler was removed by the first response to come back. It has been fixed by preventing the double search and also fixing the bug in `ServiceStore`.
=> AKU-283: Loading... message does not disappear

aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/layout/css/FixedHeaderFooter.css, aikau/src/main/resources/alfresco/layout/templates/FixedHeaderFooter.html, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js
This addresses issue [AKU-294](https://issues.alfresco.com/jira/browse/AKU-294), which requests a new, fixed-height widget with a header, footer and scrollable central content area inside it.
=> AKU-294: Fixed header/footer

aikau/src/main/resources/alfresco/editors/TinyMCE.js, aikau/src/main/resources/alfresco/editors/i18n/TinyMCE.properties, aikau/src/main/resources/alfresco/forms/controls/TinyMCE.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/editors/TinyMCE.get.desc.xml
It was noted that we failed to update the JSDoc for the TinyMCE related widgets following recent updates to make them production ready. I've updated the JSDoc to remove the warnings as well as added in some localization (which isn't used by default) and added a description for the test page.
=> Updates to TinyMCE to correct JSDoc, NLS and WebScript descriptor

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/config/Suites.js
This addresses issue [AKU-312](https://issues.alfresco.com/jira/browse/AKU-312) where the MultiSelect results dropdown was not properly populated after keyboard selection. Have now properly reset the control after a choice is made, and changed what happens when the down arrow is pressed or the control is clicked. The test has also been updated accordingly.
=> AKU-312: Dropdown not properly populated after keyboard selection

aikau/src/main/resources/alfresco/navigation/_HtmlAnchorMixin.js, aikau/src/test/resources/alfresco/menus/MenuTests.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/BasicMenuTestPage.get.js
This addresses issue [AKU-305](https://issues.alfresco.com/jira/browse/AKU-305), which points out that the right-click is not working in the header-menu. This is because the URL defined on the link is incorrect, due to a missing condition from a previous deprecation. This has been added in, and tests updated.
=> AKU-305: Header menu right-click broken

aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/forms/controls/CheckBoxTest.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/alfresco/services/ActionServiceTest.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/alfresco/services/actions/NodeLocationTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js
This addresses issue [AKU-300](https://issues.alfresco.com/jira/browse/AKU-300) which notes that calendar events in search results to not navigate to the correct page when clicked. It also includes an update to the testing code to make it easier to query the pub/sub debug log.
=> AKU-300: Search result has incorrect link for events

aikau/src/main/resources/alfresco/services/DocumentService.js
Stefan spotted an issue with the DocumentLibrary failing to load documents and I've tracked it down to an incorrect correction to a JSHint issue. This PR corrects that mistake.
=> Fix issue in alfresco/services/DocumentService introduced by previous commit

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This addresses issue [AKU-296](https://issues.alfresco.com/jira/browse/AKU-296) which has content slightly overflowing the bottom of the dialog content and being cropped.
=> AKU-296: Dialog height incorrect

aikau/src/main/resources/alfresco/menus/AlfDropDownMenu.js, aikau/src/main/resources/alfresco/menus/AlfMenuBar.js, aikau/src/main/resources/alfresco/menus/AlfMenuBarPopup.js, aikau/src/main/resources/alfresco/menus/AlfMenuGroup.js, aikau/src/main/resources/alfresco/menus/AlfMenuGroups.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-290 which is something of an edge case condition (e.g. it requires the user to hover over a different drop-down menu from the one just actioned, and this may or may not be something that often happens). However to prevent this issue occurring I'm disabling the auto open on hover feature in the menu bar. Theoretically the reported problem (that the popup-menu becomes detached) could be reproduced now if the user *clicks* on another menu, but this is even more of an edge case.
=> AKU-290: Updates to prevent menu items opening on hover

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/HiddenValue.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-314. It doesn't provide a fix (as we don't believe that there is anything to fix in terms of code) but rather updates the JSDoc to explicitly indicate how and when the alfresco/forms/controls/HiddenValue widget should be used.
=> AKU-314: Update JSDoc

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses issue [AKU-325](https://issues.alfresco.com/jira/browse/AKU-325) which refers to the MultiSelect control having inconsistent behaviour regarding the backspace key. Have corrected a switch condition to fix the bug. Have also updated the MultiSelect test to provide visual verification state-data and update the test and the control to support the bug fix, and to fix discovered problems from adding the visual state checking info.
=> AKU-325: MultiSelect backspace key inconsistent behaviour

aikau/src/main/resources/alfresco/core/ResizeMixin.js
This addresses issue [AKU-307](https://issues.alfresco.com/jira/browse/AKU-307), which highlights a potential memory leak in ResizeMixin. The fix assumes that most of the time this mixin will be used in a widget, and if it has then it should use the "own" method ensure the resize listener is cleaned up when the widget is destroyed.
=> AKU-307: Memory leak in ResizeMixin

aikau/src/main/resources/alfresco/dnd/Constants.js, aikau/src/main/resources/alfresco/dnd/DragAndDropNestedTarget.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/dnd/css/DragAndDropTarget.css, aikau/src/main/resources/alfresco/dnd/css/DroppedItemWrapper.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-297 (or at least makes an attempt to). By removing the transitions and margin updates this should help to indicate whether or not there are deeper issues with moving items around a nested DND structure. The JavaScript now tracks and sets explicit Aikau classes to indicate the current drop target.
=> AKU-297: Removed DND "flutter" 

aikau/src/main/resources/alfresco/dnd/DroppedItem.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-313 in that it provides the ability to configure which property of a dropped item's value to render as the display name (previously this was just hard-coded to "name").
=> AKU-313: Added additional config support to alfresco/dnd/DroppedItem

aikau/src/main/resources/alfresco/debug/WidgetInfo.js, aikau/src/main/resources/alfresco/debug/css/WidgetInfo.css, aikau/src/test/resources/alfresco/debug/WidgetInfoTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/debug/WidgetInfo.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/debug/WidgetInfo.get.js
This addresses issue [AKU-328](https://issues.alfresco.com/jira/browse/AKU-328) which solves a problem with the WidgetInfo class, where click-bubbling is preventing the info button being useful in Debug mode when a widget already has a click handler.
=> AKU-328: WidgetInfo click-bubbling problem

aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/additional-config.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-318 to ensure that dropped item label information is not lost from a nested dropped item when editing the item that it has been dropped into.
=> AKU-318: Ensure that nested DND item label isn't lost when editing parent DND item

aikau/src/main/resources/alfresco/forms/ControlRow.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/ControlRowTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/ControlRow.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/ControlRow.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/ControlRow.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-322. I've reproduced the reported issue and created a unit test to verify the problem and then fixed the issue in the "alfresco/forms/ControlRow" widget.
=> AKU-322: Update ControlRow to publish initial value of its children

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/ProcessWidgets.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/modeller.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-298 to provide support for the "additionalCssClasses" attribute whenever processWidgets is called. Specifically this meets DND requirements of being able to set CSS classes on modelled dropped items.
=> AKU-298: Add global support for additionalCssClasses

aikau/src/main/resources/alfresco/lists/views/HtmlListView.js, aikau/src/main/resources/alfresco/lists/views/HtmlListViewRenderer.js, aikau/src/main/resources/alfresco/lists/views/templates/HtmlListView.html, aikau/src/main/resources/alfresco/lists/views/templates/HtmlListViewRenderer.html, aikau/src/test/resources/alfresco/lists/views/HtmlListViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/HtmlListView.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/HtmlListView.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/HtmlListView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-321 and provides a simple view for lists that outputs a single property from each item as an HTML li element.
=> AKU-321: Added alfresco/lists/views/HtmlListView

aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/forms/DynamicForm.js, aikau/src/main/resources/alfresco/forms/css/DynamicForm.css, aikau/src/test/resources/alfresco/dnd/AlternateEditorTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/alternate-edit.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/alternate-edit.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/alternate-edit.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-301 and allows developers to configure alternative publication topics and payloads for editing dropped items. The default behaviour of requesting that a dialog be displayed is retained and a unit test has been added to edit dropped items using the "alfresco/forms/DynamicForm" widget which has been updated to support this use case and make it more abstract.
=> AKU-301: Support alternative edit item publications in DND

aikau/src/main/resources/alfresco/documentlibrary/_AlfFilterMixin.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/HashFormTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/HashForm.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/HashForm.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/HashForm.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-316 in updating alfresco/forms/Form to support the hashVarsForUpdate property defined in the alfresco/documentlibrary/_AlfHashMixin. This means that it's now possible to configure a form so that only some form control values are updated from the hash and that only certain form control values update the hash.
=> AKU-316: Update forms to support hashVarsForUpdate

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentListInfiniteScroll.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/services/InfiniteScrollService.js, aikau/src/test/resources/alfresco/lists/InfiniteScrollTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/InfiniteScroll.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/InfiniteScroll.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/InfiniteScroll.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-342 to ensure that all instances of "alfresco/lists/AlfSortablePaginatedList" support infinite scrolling (and not just the "alfresco/search/AlfSearchList"). I've also deprecated the "alfresco/documentlibrary/AlfDocumentListInfiniteScroll" widget (because it was badly packaged) and replaced it with the "alfresco/services/InfiniteScrollService" (as this capability it provides makes more sense as a service than a widget).
=> AKU-342: Make infinite scroll generic

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-345 to improve the error logging in the alfresco/services/NavigationService, but even more importantly it revealed a more serious issue where hashing was broken. There wasn't a unit test to cover this so I've added one.
=> AKU-345: Added error handling on buildUrl in NavigationService

aikau/src/main/resources/alfresco/services/actions/WorkflowService.js, aikau/src/test/resources/alfresco/services/actions/WorkflowTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-346 to correct a problem with the way that workflow assignment URLs were being constructed. I don't like the mixin approach for topics, but it makes sense to use it whilst we have one already defined so I've updated the WorkflowService and added a test to prevent any future regressions.
=> AKU-346: Ensure workflow assignment uses correct URL

aikau/src/main/resources/alfresco/menus/AlfMenuBar.js, aikau/src/test/resources/alfresco/menus/MenuBarOrientationTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/MenuBarOrientation.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/MenuBarOrientation.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/MenuBarOrientation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-349 and provides support for allowing menu bars to be configured so that popups appear above, rather than below, the menu bar.
=> AKU-349: Add support for menu bar popups to appear above menu

aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumb.css, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumbTrail.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-347. I've updated the test page so that we'll always display at least one overflowing breadcrumb trail for us to inspect when making any future design changes, however there are no updates to the unit tests because this isn't exactly testable without actually looking at it!
I've attached a screenshot to the JIRA ticket so that you can see what the output should look like
=> AKU-347: Breadcrumb overflow CSS updates

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PreferenceServiceMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/Preferences/Preferences.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-343. It would appear that the alfresco/lists/Paginator was not currently updating the user preference when they changed page size, however it was requesting the user preference and using that (so overriding any configured value). I've updated the Paginator and updated the unit tests to ensure that page preferences are set. 
I've also broken up the Pagination tests into smaller suites because they're so large they frequently take the code coverage server down - hopefully this should help.
=> AKU-343: Ensure that Paginator updates user preferences

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/lists/templates/AlfList.html, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-352 to ensure that pagination controls are hidden when no data is available either because the data contains no items or because the page start index is greater than the number of results available to display (previously it was just addressing the former case where there were no items).
=> AKU-353: Updated Paginator to hide controls on invalid page

aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-341 and updates the validation of the NumberSpinner to ensure that commas and spaces are stripped out of numbers before they are validated.
=> AKU-341: Ensure that number spinner can be configured > 1000

aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AutoHeightFixedHeaderFooter.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AutoHeightFixedHeaderFooter.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AutoHeightFixedHeaderFooter.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-350 to change the default behaviour of the alfresco/layout/FixedHeaderFooter widget. I've added a unit test for the new auto sizing capabilities as well as improving the JSDoc so that developers can understand the limitations of using a percentage based height.
=> AKU-350: Improve default FixedHeaderFooter size handling

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/services/CrudServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-331 to update the alfresco/services/CrudService to encode all URIs before they're requested (however, it's possible to configure the service so that URIs aren't encoded). A unit test has been added to verify encoding occurs.
=> AKU-331: Updated CrudService to encode URIs by default

aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedListDataFail.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedListDataFail.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedListDataFail.get.js
This is a second attempt at addressing https://issues.alfresco.com/jira/browse/AKU-352 (the previous PR: https://github.com/Alfresco/Aikau/pull/277 addressed some of the issues, but not a specific use case). This update ensures that pagination controls are hidden when data fails to load at all. The unit tests have been updated to address this.
=> AKU-353: Hide pagination controls on data failure

aikau/pom.xml, aikau/src/main/resources/extension-module/aikau-extension.xml, aikau/src/test/resources/testApp/WEB-INF/surf.xml, pom.xml
This change adds library information (available at build time) to the Jar manfest file. It just lists surf, dojo, jquery, jqueryui by using dependency properties in the pom.
This should make it easier to upgrade those libraries by just changing the property. However, I notice that jquery/jquery ui are saved in the source tree whereas dojo is a dependency.  That would require some rework.
=> Adding library version information to the manifest.mf

aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/test/resources/alfresco/renderers/PublishingDropDownMenuTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.js
This PR attempts to address https://issues.alfresco.com/jira/browse/AKU-344. I've made some updates so that it's possible to publish requests to cancel using the escape key (obviously this can't actually stop a publication after it's been made, but a listening service should potentially be able to kill an XHR request in flight. When a failure or cancellation occurs the value of the select will be reset to it's previous value.
=> AKU-344: Publishing action cancel reset

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SitesList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AutoHeightFixedHeaderFooter.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedListDataFail.get.js
This PR addresses an additional comment that was raised on https://issues.alfresco.com/jira/browse/AKU-352. I originally added the "hidePageSizeOnWidth" as an experiment in alternative approaches to response web design, but really it's caused nothing but problems (see https://issues.alfresco.com/jira/browse/AKU-348) so I've removed it - it was inconsistent with the rest of the library and hasn't been used in production (the paginator is used, but this feature isn't relied upon and is likely to cause more confusion if left).
=> AKU-352: Remove hidePageSizeOnWidth attribute

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/lists/views/layouts/Cell.js, aikau/src/main/resources/alfresco/lists/views/layouts/Column.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/main/resources/alfresco/lists/views/layouts/_LayoutMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/test/resources/alfresco/lists/views/layouts/RowTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js, aikau/src/test/resources/alfresco/renderers/PublishingDropDownMenuTest.js, aikau/src/test/resources/alfresco/renderers/SocialRenderersTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/layouts/Row.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.js
This PR addresses comments in https://issues.alfresco.com/jira/browse/AKU-344 relating to alfresco/renderers/PublishingDropDownMenu widgets not detecting cancellation actions when a dialog is closed (by clicking the close icon rather than using the ESCAPE key).
This change "normalises" behaviour by simulating an ESCAPE key press when the dialog closes to ensure that anything listening to the escape key is notified. In order to efficiently write the test for this I've made some updates to the way that iterated data (e.g. in lists) is handled so that IDs can be applied more effectively. This will go some way to addressing https://issues.alfresco.com/jira/browse/AKU-353.
=> AKU-344: Dialog containing PublishingDropDownMenu close

aikau/conf.json, aikau/src/jsdoc-plugins/customization-support-tags.js, aikau/src/jsdoc-templates/alfresco/tmpl/details.tmpl, aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/core/JsNode.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/services/DialogService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-336 and defines some new JSDoc tags that can be used to indicate which modules and functions will be supported in Aikau going forwards. An initial set of modules have been updated to use these tags. This is not necessarily the final implementation but we'll need to review at the sprint end to see if we're happy with the approach going forwards.
=> AKU-336: Annotating JSDoc with support statements

aikau/src/main/resources/alfresco/header/AlfSitesMenu.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/HeaderTest/Favourites.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-354 to ensure that the asynchronously loaded favourites cascading menu is hidden before being populated and then redisplayed to ensure that the popup positioning and scrolling are consistent each time it is used (the asynchronous loading only takes place the first time the cascade is opened). I've not updated the unit test for this as the existing tests prove that the menu can be opened and the contents displayed.
=> AKU-354: Sites menu updates

aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/templates/AlfListView.html, aikau/src/test/resources/alfresco/lists/views/AlfListViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListView.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListView.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListView.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/AlfListViewMockService.js
This PR addresses issue [AKU-332](https://issues.alfresco.com/jira/browse/AKU-332), which requests CSS class identification of certain list elements/messages, in order to make them more testable/stylable.
=> AKU-332: Identify empty results with CSS

aikau/src/main/resources/alfresco/core/Events.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/layout/InfiniteScrollArea.js, aikau/src/main/resources/alfresco/layout/VerticalWidgets.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/services/InfiniteScrollService.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-364 and https://issues.alfresco.com/jira/browse/AKU-358. It provides a new alfresco/layout/InfiniteScrollArea widget that allows lists to support infinite scrolling pagination when they don't take up the entire page height. It also addresses the issue where data filtering does not clear previous page data (or in the document list when paths/filters/tags/categories are applied).
=> AKU-358, AKU-364: Added initial InfiniteScrollArea widget

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This addresses issue [AKU-356](https://issues.alfresco.com/jira/browse/AKU-356), and permits the auto-publishing of a form when its values change. By default, it will not publish when any of its values are invalid, but this can be turned on with a config option. For full usage information, see the JSDoc.
=> AKU-356: Auto-publish form on field changes

aikau/src/main/resources/alfresco/forms/controls/DragAndDropTargetControl.js
It is not possible to configure a DragAndDropTargetControl to work with it's drag and drop handles false, because the declarative configuration property 'withHandles' is not passed through to the DragAndDropTarget it generates. This PR makes a small change to allow this.
=> Add 'withHandles' pass through to DragAndDropTargetControl

aikau/src/main/resources/alfresco/services/DialogService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-371 to add the missing "formValue" attribute to the JSDoc description of the payload that can be used with the "ALF_CREATE_FORM_DIALOG" publication.
=> AKU-371: DialogService JSDoc update

aikau/src/grunt/shell.js, aikau/src/grunt/testing.js
Run with the command: 
grunt startUnitTestApp --mvnOptions='-DproxyUrl="10.181.129.80" -DproxyPort="5677" -DunitTestAppBaseUrl=${HOSTNAME} -DbrowserName="internet explorer"'
(note the single quotes around all the maven options, preserving the double quotes inside it. It allows arbitrary mvn options)
I've also added "clean" to the mvn commands as we've found we need that locally.
=> Add ability to passthrough maven options to startTestApp

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-368 to ensure that text only dialogs have that text centre aligned. I've not added a test for this as there seems little value for something relatively trivial like this.
=> AKU-368: Ensure that text content in dialogs is centre aligned

aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedViewItem.js, aikau/src/main/resources/alfresco/renderers/InlineEditPropertyLink.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLib.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-362 (and it might also resolve https://issues.alfresco.com/jira/browse/AKU-374). The breadcrumb trail was not working with URL hashing disabled so I have added tests for checking a Document Library (created using an updated version of the doclib.lib.js file) with useHash enabled and disabled and also with and without a pubSubScope.
=> AKU-362: Non hash breadcrumb trail

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This addresses issue [AKU-373](https://issues.alfresco.com/jira/browse/AKU-373) where the autosave payload, if specified, is not mixing in form values. The tests have also been updated accordingly.
=> AKU-373: Autosave payload not mixing in form values

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SearchList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-66 and removes the blockConcurrentRequests which is never used and had the result of allowing concurrent requests to occur.
=> AKU-66: Remove use of blockConcurrentRequests

aikau/pom.xml, aikau/src/grunt/testing.js
- Added unitTestsGrid maven profile
- Runtest_grid task in the Maven integration-test phase
- Unplugged startUnitTestApp task for grid as Tomcat is started during
the pre-integration-test phase by Maven.
I added a new Maven profile to avoid collision with ongoing
developments (ie: The run profile). For the same reasons, I kept all
the jetty part and only
unplugged that for the test_grid task.
Run command: mvn verify -PunitTestsGrid
@ohej , @MartinDoyleUK, could you guys review my changes and tell me if it's not colliding with your current developments around Tomcat ?
Thanks.
-Jp
=> AKU-2: Added unitTestsGrid maven profile

aikau/src/main/resources/alfresco/renderers/Actions.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/test/resources/alfresco/renderers/ActionsTest.js, aikau/src/test/resources/alfresco/renderers/actions/UploadNewVersionActionTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-361 and https://github.com/Alfresco/Aikau/issues/303 to support the ability to merge the 3 different actions types within the alfresco/renderers/Actions renderer.
=> AKU-361: Merge action types

aikau/src/test/resources/intern_grid.js
report.xml will be created in the aikau folder.
Support for custom configuration of the JUnit reporter is only
available from intern 3.0. (See
https://theintern.github.io/intern/#common-config)
ideally the report.xml file will be located in the aikau/target folder
when we upgrade to intern 3.0+
=> AKU-2: Added JUnit reporter for Bamboo

aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js
I noticed that the DocLib tests were failing on Chrome but not Firefox, this seems to be because the page is quite complex and the test needs to wait a little longer than normal for the widgets to appear. This minor update ensures the tests pass.
=> Update to ensure that the DocLib tests pass on the first run

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/lists/views/css/AlfListView.css, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/HeaderCell.css, aikau/src/main/resources/alfresco/lists/views/layouts/css/Row.css, aikau/src/main/resources/alfresco/lists/views/layouts/css/_MultiItemRendererMixin.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-366 to improve support for zebra striping in lists as well as tidy up the related LESS variables.
=> AKU-366: Improve zebra striping support in lists

aikau/src/main/resources/alfresco/header/css/SearchBox.css
This minor CSS change is required to ensure the SearchBox renders correctly in Share
=> Minor SearchBox CSS tweak

aikau/src/main/resources/alfresco/forms/controls/Select.js, aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/test/resources/alfresco/renderers/PublishingDropDownMenuTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-353 to add additional testing hook points into the PublishingDropDownMenu widget (and its associated Select) widget
=> AKU-353: Improve PublishingDropDownMenu widget testability

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-381 to ensure that there are is no unnecessary white space at the bottom of dialogs with no buttons. This occurs when an ALF_CREATE_DIALOG topic is used where widgetsButtons is empty, it can be seen in Share when clicking on the More Info link in the faceted search page.
=> AKU-381: Remove white space on dialogs when there are no buttons

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/services/DialogService.js
This update ensures that only form controls that are placed in the "root" form within a dialog have the new form style applied to them. In particular this is important because the MultipleEntryElementFormControl uses forms within forms and this was corrupting the layout when used in the search manager in Share. Therefore root form elements will have the new style applied to them but nested forms will not.
=> Ensure that MultipleEntryElementFormControl widgets render in dialogs

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/HashFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/HashForm.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-382 to correct a few outstanding issues with using the browser URL hash with forms. The "setHash" configuration attribute is properly honoured so that the URL hash is only updated on request. The "postWhenHiddenOrDisabled" and "noValueUpdateWhenHiddenOrDisabled" configuration attributes now have tests to ensure that they're honoured with respect to setting the hash. I've also noted and resolved an unrelated issue where a button payload does not have values that should be hidden removed (e.g. if a field is disabled that shouldn't POST when disabled having previously output its value - the value is NOT removed from the payload - this has now been corrected).
=> AKU-382: Form updates to ensure that URL hash setting works properly

aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js, aikau/src/test/resources/alfresco/menus/AlfMenuItemTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuItem.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuItem.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuItem.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-388. As this is a bug I've just added a test to prevent regressions on the reported issue, but we can use the test to handle any additional bugs reported in the future. I've also updated the JSDoc to give examples of the various types of payload that can be configured.
=> AKU-388: Ensure that PROCESS payload types can be used with menu items

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/test/resources/alfresco/dnd/MultiSourceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-379 to ensure that single use drag and drop items can only be added to a drop target once when using the keyboard.
=> AKU-379: Ensure that single use items can only be added once via keyboard

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/AutoSaveFormsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/AutoSaveForms.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/AutoSaveForms.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/AutoSaveForms.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-383 to iron out some issues with the recently added auto save capabilities in forms. The key change here is to ensure that auto save does not commence until form setup has completed. 
There were some interesting issues to resolve here caused by the fact that the publications are queued until the page is complete, so even though form and control states could be updated, publications would not be processed until after everything was setup. I've addressed this for both forms that appear on the page initially and also forms created dynamically post page load.
Along the way I've also fixed a few other issues that I uncovered with forms in general
=> AKU-383: Fix form auto save issues

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-392 to ensure that issuing a reload request to a list (when the list has infinite scroll enabled) will clear the previous results.
=> AKU-392: Correction to infinite scroll reload behaviour

aikau/src/main/resources/alfresco/documentlibrary/AlfGalleryViewSlider.js, aikau/src/main/resources/alfresco/layout/Twister.js, aikau/src/main/resources/alfresco/layout/css/Twister.css, aikau/src/test/resources/alfresco/layout/TwisterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/Twister.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PreferenceServiceMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/Preferences/Preferences.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-375 to update the alfresco/layout/Twister widget to support the ability to configure initial open/closed state. It also adds the ability to use the alfresco/services/PreferenceService to retrieve and store the preferred open/closed state of the twister from the current users personal preferences. For good measure I've also updated the JSDoc and fixed up the unit tests.
=> AKU-375: Twister updates

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/services/LoggingService.js
This PR finally (hopefully) resolves https://issues.alfresco.com/jira/browse/AKU-380. The issue was that we were implementing the dojo/dnd/Source extension points "onDraggingOut" and "onDraggingOver"... however those extension points were only being fired if the targetState was NOT disabled, e.g.
```JAVASCRIPT
if(this.isDragging && this.targetState != "Disabled"){
this.onDraggingOut();
}
```
This meant that the updates we'd added to notify the dojo/dnd/Manager of a change of current target were only being fired when the current target was NOT disabled. This meant that as soon as a target was marked as disabled (e.g. when passing over a nested drop target that accepted a different type) the new target was not set when leaving that nested target.
The solution is to use an aspect to chain to …
=> AKU-380: Resolved DND nested drag over/out issue

aikau/src/main/resources/alfresco/services/SearchService.js
Ensure that recent alfCallerName addition to payloads for filtering pub/sub logs to the console is omitted from search requests.
=> SearchService update

aikau/src/main/resources/alfresco/misc/AlfTooltip.js, aikau/src/test/resources/alfresco/misc/AlfTooltipTest.js
This addresses issue [AKU-384](https://issues.alfresco.com/jira/browse/AKU-384) which requests the ability to configure a delay before displaying a tooltip. Some sensible defaults have been set initially, and the tooltip will appear after a 250ms delay and hide 250ms after the mouse has moved away from the target element. This also refines the triggering of the tooltip to make it more consistent with expectations.
=> AKU-384: Tooltip-display delay

aikau/src/main/resources/alfresco/core/_EventsMixin.js, aikau/src/main/resources/alfresco/dashlets/Dashlet.js, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/test/resources/alfresco/dashlets/DashletTest.js, aikau/src/test/resources/alfresco/dashlets/InfiniteScrollDashletTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dashlets/InfiniteScrollDashlet.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dashlets/InfiniteScrollDashlet.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dashlets/InfiniteScrollDashlet.get.js
This PR addresses (in part) https://issues.alfresco.com/jira/browse/AKU-395. I've attempted to reproduce the issues that the customer was having with infinite scroll inside a dashlet (now possible with the pure Aikau dashlet). I've had to make some minor tweaks to get it working and I've added a test page, but no test yet... this might be worth pulling into 1.0.24 though and completing the test work in the next sprint (alternatively I'll try and get the test in before end of sprint)
=> AKU-395: Code updates and test page for infinite scroll in dashlet

aikau/src/main/resources/alfresco/dashlets/Dashlet.js, aikau/src/main/resources/alfresco/misc/AlfTooltip.js
Remove Dojo attach points from Dashlet code (we don't have them explicitly set anywhere else). Fix naming (and scoped-naming) of methods in AlfTooltip.
=> Minor fixes for committed Sprint code

aikau/ReleaseNotes.md, aikau/src/main/resources/alfresco/buttons/AlfFormDialogButton.js, aikau/src/main/resources/alfresco/core/NotificationUtils.js, aikau/src/main/resources/alfresco/dialogs/_AlfCreateFormDialogMixin.js, aikau/src/test/resources/alfresco/core/NotificationUtilsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/NotificationUtils.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/NotificationUtils.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/NotificationUtils.get.js, aikau/src/test/resources/testApp/js/aikau/testing/core/NotificationUtilsInstance.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-400 to ensure that the deprecated alfresco/core/NotificationUtils is backwards compatible with previous releases.
=> AKU-400: NotificationUtils fix

aikau/src/main/resources/alfresco/dnd/Constants.js, aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/DragAndDropNestedTarget.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/services/DragAndDropModellingService.js, aikau/src/test/resources/alfresco/dnd/MultiSourceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/multi-source.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-399 to resolve an issue whereby the acceptance types for drop targets was being incorrectly set. In fact the types were not being set at all and this has now been corrected. Additionally I've fixed the issue where all dropped items created from a preset value are initially selected on the first drag and ensured that single use items that are used by a preset value are removed from the palette.
=> AKU-399: DND preset value typing issues

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/actions/ManageAspectsService.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.js
This addresses issue [AKU-396](https://issues.alfresco.com/jira/browse/AKU-396), which is the addition of ManageAspects to the AlfSearchResult. When this is integrated with Share then further changes will be needed in Share, as documented in the JIRA ticket.
=> AKU-396: Update AlfSearchResult to include "Manage Aspects" as an available action

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/FormValidationTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormValidation.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormValidation.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormValidation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-378 to add the ability to configure forms to not show validation errors immediately. This is done by configuring the form with the new attribute "showValidationErrorsImmediately" as false (the default is true).
=> AKU-378: Only show validation when forms lose focus

aikau/src/main/resources/alfresco/services/InfiniteScrollService.js
Fix bug whereby InfiniteScrollService was not correctly calculating nearBottom when using `window` as the scrollNode.
=> InfiniteScroll issue with Share

aikau/src/main/resources/alfresco/dnd/Constants.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/dnd/DroppedNestingItemWrapper.js, aikau/src/test/resources/alfresco/dnd/NestedReorderTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/nested-reorder.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/nested-reorder.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/nested-reorder.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-390 to resolve issues with the DND capabilities in nested items. Previous tests for re-ordering were only looking at root level items so a new test page has been created with items nested within nested items and these are then re-ordered (using the up/down buttons), moved from one target to another and deleted. 
Some significant portions of the DND implementation have required updating to ensure that this now works as it should.
=> AKU-390: Nested DND re-order and delete updates

aikau/src/main/resources/webscript-libs/service-filtering.lib.js
I took a look ahead to AKU-410 and realised that some additional service filtering capabilities would be required. In a scenario where there are 2 Surf Components that render Aikau content it will be necessary to not just filter duplicate services defined in libraries, but to eliminate them altogether. This means that a dashlet WebScript can import the share-header.lib.js file and remove all services that it defined (rather than just eliminating duplicates)... because even if duplicates are removed, the Surf Component containing the header will duplicate them anyway. So the service-filtering.lib.js now supports an additional argument that allows duplicates to not just be filtered but removed entirely.
=> Updates to service-filtering.lib.js

aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/test/resources/alfresco/creation/WidgetConfigTest.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/alfresco/dnd/FormCreationTest.js, aikau/src/test/resources/alfresco/dnd/MultiSourceTest.js, aikau/src/test/resources/alfresco/dnd/NestedReorderTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/nested-reorder.get.js
This PR resolves https://issues.alfresco.com/jira/browse/AKU-413 in ensuring that the DragAndDropItems widget only removes the appropriate items in single use mode.
=> AKU-413: Ensure that single item mode works with nested items

aikau/src/main/resources/alfresco/core/TemporalUtils.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/main/resources/alfresco/forms/controls/css/DateTextBox.css, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This addresses issue [AKU-409](https://issues.alfresco.com/jira/browse/AKU-409) which is about errors caused when an invalid value is fed into the DateTextBox control. There are also some JSHint and JSDoc updates, and all corresponding tests are updated.
=> AKU-409: DateTextBox cannot be empty

aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js, aikau/src/test/resources/alfresco/forms/SingleTextFieldFormTest.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/alfresco/preview/PdfJsPreviewTest.js
This PR address https://issues.alfresco.com/jira/browse/AKU-412 to try and ensure consistency of test failures. In particular this addresses the DocLib tests that fail when caches are cleared and for PDF.js preview tests where a failure was caused by not waiting for a notification to be removed. This also clears up deprecations.
=> AKU-412: Test failures

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css
This addresses issue [AKU-403](https://issues.alfresco.com/jira/browse/AKU-403), which requires that Dashlets can be themed in Share, in order to sit alongside the non-Aikau dashlets when the theme is changed from the default. See the JIRA ticket for sample files of how to theme them in Share.
=> AKU-403: Dashlet theming

aikau/src/main/resources/alfresco/renderers/AvatarThumbnail.js, aikau/src/main/resources/alfresco/renderers/templates/Thumbnail.html, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/renderers/AvatarThumbnailTest.js, aikau/src/test/resources/alfresco/renderers/ThumbnailTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/AvatarThumbnail.get.js
This addresses issue [AKU-407](https://issues.alfresco.com/jira/browse/AKU-407) and provides the ability to publish when clicking on an Avatar Thumbnail.
=> AKU-407: AvatarThumbnail add support for link

aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/i18n/DialogService.properties, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-267 to add support for repeating form dialogs (the create and create another paradigm). Unit tests have been updated accordingly. Both golden path and error handling scenarios have been addressed.
=> AKU-267: Repeating form dialog support in DialogService

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/PaginatedSearchList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/PaginatedSearchList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/PaginatedSearchList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PaginatedSearchListMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/PaginatedSearchList/results.json
This addresses issue [AKU-414](https://issues.alfresco.com/jira/browse/AKU-414) which, in response to [a forum post](http://forums.alfresco.com/forum/developer-discussions/alfresco-share-development/extending-aikau-search-page-faceted-search), notes that there are problems using the search list with a paginator.
Here is an example that shows how it can be used:
```javascript
{
name: "alfresco/lists/Paginator",
config: {
documentsLoadedTopic: "ALF_RETRIEVE_DOCUMENTS_REQUEST_SUCCESS",
totalResultsProperty: "response.numberFound",
startIndexProperty: "response.startIndex",
documentsPerPage: 10,
pageSizes: [5, 10, 20]
}
},
{
name: "alfresco/search/AlfSearchList",
config: {
useHash: true,
useInfiniteScroll: false,
currentPageSize: 10,
widgets: [
{
name: "alfresco/search/AlfSearchListView", …
```
=> AKU-414: AlfSearchList does not work with Paginator

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js
This addresses issue [AKU-420](https://issues.alfresco.com/jira/browse/AKU-420) by allowing the specification of a custom page-size preference name in AlfSortablePaginatedList and its descendants. Tests have also been added to ensure this works properly.
=> AKU-420: currentPageSize issue

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This addresses issue [AKU-423](https://issues.alfresco.com/jira/browse/AKU-423) which requests allowing a custom scope to be passed to DialogService for use when submitting a form. The publishPayload property will now the following config parameters: formSubmissionTopic [existing], formSubmissionPayloadMixin [existing], formSubmissionGlobal and formSubmissionScope. Core.js has also been updated to allow proper use of a custom, one-off scope which will also update the alfPublishScope property in the payload. Tests have all been updated accordingly.
=> AKU-423: DialogService form to allow publish scoping

aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This addresses issue [AKU-431](https://issues.alfresco.com/jira/browse/AKU-431) by allowing a new config option of 'permitEmpty' on the NumberSpinner control and update tests accordingly.
=> AKU-431: NumberSpinner cannot be empty

aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This addresses issue [AKU-430](https://issues.alfresco.com/jira/browse/AKU-430) by treating empty values supplied to DateTextBox as invalid values, rather than epoch date.
=> AKU-430: DateTextBox does not handle empty values normally

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/notifications/AlfNotification.js, aikau/src/main/resources/alfresco/notifications/css/AlfNotification.css, aikau/src/main/resources/alfresco/notifications/templates/AlfNotification.html, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses issue [AKU-436](https://issues.alfresco.com/jira/browse/AKU-436) which fixes the notifications showing off screen when scrolled by changing positioning from absolute to fixed. Have also added a requested close button on the notification.
=> AKU-436: Notifications show off screen if scrolled

aikau/src/main/resources/alfresco/services/DialogService.js
In AKU-378 Form validation should not run on form load - config was added to allow Forms to not show validation messages until fields were focused. This adds the missing code to apply the config value into formConfig when forms are created via the ALF_CREATE_FORM_DIALOG_REQUEST pubsub mechanism.
=> Added missing code to apply showValidationErrorsImmediately config

aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/main/resources/alfresco/services/UserService.js, aikau/src/main/resources/alfresco/services/_UserServiceTopicMixin.js, aikau/src/main/resources/alfresco/services/i18n/UserService.properties, aikau/src/test/resources/alfresco/services/UserServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceDefaultPage.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceDefaultPage.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/UserServiceDefaultPage.get.js
- Added _UserServiceTopicMixin which contains all UserService topics
- Updated UserService to use topics from mixing
- Updated UserService with onSetUserDefaultPage method and related
success and failure methods
- Added check for optional alfResponseTopic in
PreferenceService.setPreference
- Added UserServiceDefaultPage test webscript
- Added User Service Default Page Test suite to UserServiceTest
=> AKU-459: Ability to Set a New User Default Page Preference Via Publish

aikau/src/main/resources/alfresco/buttons/AlfDynamicPayloadButton.js, aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/main/resources/alfresco/menus/AlfMenuBarToggle.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/main/resources/alfresco/util/hashUtils.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/TestIndex.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js
This pull request replaces #393, as it was necessary to delete the old branch in order to rebase it. Additionally, it has been further updated following the review comments.
_Original description_
> This addresses issue [AKU-415](https://issues.alfresco.com/jira/browse/AKU-415) which requests the ability to have useHash set to true on a filtered list and have the hash mirror the filtering controls' values with bidirectional communication between the two and the filtered data updating appropriately as well.
=> AKU-415: AlfFilteredList: support for hash

aikau/src/main/resources/alfresco/forms/controls/Picker.js, aikau/src/test/resources/alfresco/forms/controls/DocumentPickerSingleItemTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DocumentPickerSingleItem.get.js
This addresses issue [AKU-437](https://issues.alfresco.com/jira/browse/AKU-437) by permitting a simple config parameter (`useCurrentItemAsValue`) that sets the initial value of a picker to the currentItem.
=> AKU-437: DocumentPicker improvements

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfTabContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-451. The issue was again related to form controls waiting for notification that widget processing has been completed and to address the issue an update has been made such that the required topic is published after adding and selecting tabs. The unit test has been updated to reproduce scenarios of form controls being included in tabs with and without delayed processing and when tabs are dynamically added.
=> AKU-451: Updates to ensure form controls are rendered in tab containers

aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js
Fix default label not displaying on UploadButton, due to dijit superclass replacing with empty string.
=> Fix default label not displaying on UploadButton

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/documentlibrary/AlfCreateContentMenuBarItem.js, aikau/src/main/resources/alfresco/documentlibrary/AlfCreateContentMenuItem.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/UploadButton.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfCreateContentMenuItemMixin.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfCreateContentPermissionsMixin.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/documentlibrary/i18n/_AlfCreateContentMenuItemMixin.properties, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/menus/AlfFilteringMenuItem.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js
This addresses both https://issues.alfresco.com/jira/browse/AKU-445 and https://issues.alfresco.com/jira/browse/AKU-446 to resolve issues preventing uploading and refreshing Document Libraries when those Document Libraries have been given a specific pubSubScope.
=> AKU-445, AKU-446: Document Library upload scoping issues

aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-422 to ensure that path breadcrumbs publish globally and hash breadcrumbs subscribe to hash events globally. I've also made some updates to the test page to ensure this works with scoped breadcrumbs.
=> AKU-442: Ensure that path breadcrumbs publish requests globally

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/TopicsMixin.js, aikau/src/main/resources/alfresco/renderers/InlineEditPropertyLink.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js
This addresses issue [AKU-421](https://issues.alfresco.com/jira/browse/AKU-421), which is about invalid scoping when using the InlineEditPropertyLink. Additionally, NotificationService has been updated to always publish when notifications are closed, and the SiteServices test has been removed from testing because it's pointless.
=> AKU-421: Invalid alfPublishScope set by InlineEditPropertyLink

aikau/src/main/resources/alfresco/documentlibrary/AlfCreateTemplateContentMenu.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentActionMenuItem.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedViewItem.js, aikau/src/main/resources/alfresco/menus/AlfSelectedItemsMenuItem.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/CreateTemplateContentService.js, aikau/src/main/resources/alfresco/services/actions/NodeLocationService.js, aikau/src/main/resources/alfresco/services/actions/WorkflowService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/CreateContent.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/NodeLocation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-447 (the JIRA issue contains detailed information on the changes) but this is a substantial PR to rework the scoping of action handling to allow multiple Document Libraries to co-exist without actions (especially those relating to current node and selecte items) from bleeding into one another. It also ensures that the correctly scoped Document Library will be refreshed only by actions relating to it.
=> AKU-447: Address action scoping issues

aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/main/resources/alfresco/forms/controls/css/NumberSpinner.css
Styles to remove the default dijit transitions, gradients and border colours that we don't use in other Alfresco Form controls.
=> Add dedicated CSS resource for NumberSpinner control

aikau/src/main/resources/alfresco/forms/ControlColumn.js, aikau/src/main/resources/alfresco/forms/ControlRow.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/LayoutMixin.js, aikau/src/main/resources/alfresco/forms/TabbedControls.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/test/resources/alfresco/forms/TabsInFormsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/TabsInForms.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/TabsInForms.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/TabsInForms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-405 to add a new mixin module "alfresco/forms/LayoutMixin" that can be applied to layout controls to create layout widgets to be used inside forms. This has been abstracted and applied to the "alfresco/forms/ControlRow" widget and used to create the "alfresco/forms/TabbedControls" and "alfresco/forms/ControlColumn" modules.
Unit tests have been added to support the new modules.
=> AKU-405: Added support for form controls in tabs

aikau/src/main/resources/alfresco/header/css/Warning.css
A rarely seen component, but now looks cleaner against the Share header area.
=> Remove odd looking gradient from Share License Header warning section.

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-466 to ensure that the alfresco/forms/TabbedControls (or even the "alfresco/layout/AlfTabContainer" that it extends) will be displayed correctly in dialogs. This was resolved by mixing the "alfresco/core/ResizeMixin" into the "alfresco/layout/AlfTabContainer" and handling the resize events that the "alfresco/dialogs/AlfDialog" was providing when first displayed.
A unit test has been added to prevent regressions.
=> AKU-466: Ensure that tab containers are displayed properly in dialogs

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/main/resources/alfresco/forms/controls/i18n/FormControlValidationMixin.properties, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This addresses issue [AKU-457](https://issues.alfresco.com/jira/browse/AKU-457) which is about decimal points on number spinners being invalid without any notification as to why, and also a request to permit decimal places through configuration. Tests have been updated accordingly.
=> AKU-457: NumberSpinner control invisibly rejects decimal points

aikau/src/main/resources/alfresco/renderers/InlineEditPropertyLink.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js
This addresses issue [AKU-480](https://issues.alfresco.com/jira/browse/AKU-480) where InlineEditPropertyLink is not scoping when it should. Reverted changes in [AKU-421](https://issues.alfresco.com/jira/browse/AKU-421) and updated test accordingly.
=> AKU-480: InlineEditPropertyLink not scoping when it should

aikau/src/main/resources/alfresco/forms/TabbedControls.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js
This is a further update for https://issues.alfresco.com/jira/browse/AKU-405. To absolutely guarantee that all tabbed form values are included in form publications. It's a less efficient solution than I was previously going for, but is more reliable.
=> AKU-405: Ensure that tabbed form values are published

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/forms/controls/i18n/FormControlValidationMixin.properties, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This addresses issue [AKU-455](https://issues.alfresco.com/jira/browse/AKU-455) which is reporting poor validation errors in the DateTextBox control. The control now has fully-implemented validation, as per the rest of the controls in Aikau.
=> AKU-455: Embedded DateTextBox validations display errors

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/search/i18n/AlfSearchResult.properties, aikau/src/main/resources/alfresco/search/templates/AlfSearchResult.html, aikau/src/test/resources/alfresco/search/CustomSearchResultTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/CustomSearchResult.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/CustomSearchResult.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/CustomSearchResult.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/previews/PDF.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-450 to make the alfresco/search/AlfSearchResult more customizable. The key updates are that you can now replace the filtered actions for documents/folder and other nodes (or just add in additional filters). You can configure the MoreInfo widget to not be rendered and it is possible to configure either "widgetsBefore" or "widgetsAfter" that will appear above or below the main properties in the central column. The widget has also been refactored so that when extending it is possible to just override specific functions that produce each specific renderer.
A unit test has been added for these new capabilities.
=> AKU-450: Initial update pending testing

aikau/src/main/resources/alfresco/documentlibrary/AlfGalleryViewSlider.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-428. It was observed that the correct number of columns were not being rendered when initially displaying a gallery view. This was because the preferences were not being passed to the gallery view when returned via the XHR request. This resulted in the default display being rendered. Whether or not this completely resolves AKU-428, this change is necessary as Share is also exhibiting the same behavior.
=> AKU-429: Update gallery view and slider to ensure correct initial column rendering

aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-453 to ensure that search results for folders that contain special characters in their path are encoded so that they can link to the correct location in the repository/document library. The unit test has been updated to prevent regressions.
=> AKU-453: Update folder search result links

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This addresses issue [AKU-448](https://issues.alfresco.com/jira/browse/AKU-448) which notes that the bottom of the scrollbar is hidden on long dialogs
=> AKU-448: Bottom of scrollbar hidden on long dialogs

aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-487 to make further updates to the alfresco/documentlibrary/AlfBreadcrumbTrail and related widgets to resolve scoping issues.
=> AKU-487: Breadcrumb trail updates

aikau/src/main/resources/alfresco/services/DialogService.js
This addresses issue [AKU-449](https://issues.alfresco.com/jira/browse/AKU-449) where a dialog can lose focus and escape will no longer close the dialog. A stack of active dialogs is now maintained by the DialogService and pressing escape will always close the dialog.
=> AKU-449: Dialog loses focus and escape doesn't close

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
For reasons only known to browser vendors, width of textbox and textarea fields varies by a few pixels when set to the same value. Override the value for textarea to match - in dialogs only.
=> Minor change to width of dijitTextArea within Dialogs to line up with width of dijitTextBox

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/util/urlUtils.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/alfresco/util/urlUtilsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This is required to support RM-2465.
=> NavigationService: allow queryParams and hashParams objects in payload to support encoding

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/search/AlternativeSearchLabel.js, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/search/FacetFilters.js, aikau/src/test/resources/alfresco/search/FacetFiltersTest.js, aikau/src/test/resources/alfresco/search/NoHashSearchingTest.js, aikau/src/test/resources/alfresco/search/SearchSuggestionsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/NoHashSearching.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/NoHashSearching.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/NoHashSearching.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchSugggestions.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SearchMockService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchService/alternative.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchService/default.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchService/original.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-472, https://issues.alfresco.com/jira/browse/AKU-475 and https://issues.alfresco.com/jira/browse/AKU-488 to make a number of changes required to enable the search widgets to be used with useHash configured to be false.
=> AKU-472: Search without URL hashing

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js
This addresses issue [AKU-497](https://issues.alfresco.com/jira/browse/AKU-497) which is about paging no longer working in a list when using hash. The fix was to remove a superfluous loadData request. Additionally, the filterDelay has been increased, as per a request in the last Sprint review meeting, in order to avoid pauses in typing causing irritating syncing issues in the filter value. Tests have been updated accordingly.
=> AKU-497: Paging broken in list when using hash

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/lists/LocalStorageFallbackTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/LocalStorageFallback.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/LocalStorageFallback.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/LocalStorageFallback.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-476 and re-works the use of local storage in lists as a fallback when a URL hash is not available. I've added tests to ensure the correct behaviour and prevent future regressions. I've also tested that the originally reported problem has been resolved on Share.
=> AKU-467: Re-work list local storage fallback

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/documentlibrary/AlfCreateContentMenuBarPopup.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/core/ResponseScopeTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ResponseScope.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ResponseScope.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ResponseScope.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-500 and re-works the logic for figuring out the correct alfResponseScope to apply to a payload to ensure that global scope (or empty string) is accepted as a valid scope. I've added some specific unit tests to verify the expected behaviour and checked that the issue no longer occurs on Share with the Document Library.
=> AKU-500: Update response scope behaviour to handle empty string falsy logic

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/FormValidationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormValidation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-490 to ensure that pending validation failures are cleared if the form control becomes valid before focus is lost. The unit test has been updated to verify the correct behaviour.
=> AKU-490: Updates to form validation

aikau/src/main/resources/alfresco/buttons/css/AlfButton.css, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.js, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This addresses issue [AKU-452](https://issues.alfresco.com/jira/browse/AKU-452), which is about making updates to the Aikau buttons to match the new Share improvements.
The final effect should be invisible to end-users of Share, however the "Aikau Test Theme"—as applied to our test application—will make the new changes visible on all unit-test pages.
NOTE: If at all possible, please double-check the aesthetics for me (both old and new) to ensure I've not broken the old and that it matches the new.
=> AKU-452: Update Aikau buttons to match new Share improvements

aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/renderers/LockedBanner.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FullDocLibMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FullDocLib/favourites_filter.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-495. I've made an update to that the breadcrumb trail is able to track whether or not it's rendering a path or a filter and then used that information to determine whether or not to re-draw the trail on node changes (e.g. don't when a filter is displayed). I've added a unit test to prevent any further regressions.
=> AKU-495: Update breadcrumb trail

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses [AKU-493](https://issues.alfresco.com/jira/browse/AKU-493) which notes that a MultiSelect control can have duplicated values displayed inside it. It has been fixed, such that multiple attempts to set the value will always replace the current value, not append to it.
=> AKU-493: MultiSelect values displayed twice

aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/main/resources/alfresco/layout/css/AlfTabContainer.css, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-489 and updates the AlfTabContainer so that it creates its tabs in the DOM model before creating widgets in them (this allows the widgets in the tabs to have access to actual dimensions to work from). The AlfSideBarContainer is also updated to make better use of the _ResizeMixin capabilities. The styling of the tabs has been tidied up (to remove the default padding) which has allowed the sidebar borders to be tidied up as well. A unit test has been added to verify that the heights are now calculated sensibly.
=> AKU-489: AlfTabContainer and AlfSideBarContainer heights

aikau/src/main/resources/alfresco/css/less/defaults.less
Change border-radius of new buttons to 3px (as per [this comment from Shane](https://issues.alfresco.com/jira/browse/SHA-1284?focusedCommentId=407935&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-407935)) and set legacy buttons back to 0.
=> AKU-452: Aikau buttons update

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfSideBarContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-506. It updates the AlfSideBarContainer so that the previous height of the resizer bar is ignored when calculating the container height (this allows the container to reduce in size as the browser window reduces in size). The main Page widget now publishes a resize topic when loading has completed to ensure that all widgets have a final resize opportunity (this is something of a brute force solution to the problem, but is effective). Unit tests have been added to verify the new resizing behaviour and confirm dynamically added tabs work as expected (in this case with lists)
=> AKU-506: Updates to improve layout behaviour

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/layout/VerticalWidgets.js, aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/navigation/TreeStore.js, aikau/src/main/resources/alfresco/renderers/_ItemLinkMixin.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-494 to ensure that the alfresco/navigation/PathTree can be configured to track path change publication as well as hash changes. I've also moved the relevant topics into the constants file and updated the unit test appropriately. One final change also ensures that tree nodes are expanded based on value and not name as the TreeStore can swap the names with descriptions in certain circumstances.
=> AKU-494: Update PathTree to track path changes

aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-492 to improve the logic handling relating to siteId, containerId and rootNode values that might be set via calls to the functions provided in the doclib.lib.js. Previously any undefined values were being interpreted as actual data because explicit checks for null were being made.
=> AKU-492: Improvements in JS logic to support DocLib options

aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/i18n/InlineEditProperty.properties, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-502. This isn't a brilliant change accessibility wise, but is something of an edge case and we can make further improvements when we go through an accessibility review. However, this does satisfy the test case in the raised issue.
=> AKU-502: Updated alt text for inline edit property with no value

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/alfresco/lists/FilteredListUseCaseTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredListUseCase1.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredListUseCase1.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredListUseCase1.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-508 to ensure that lists only make subscriptions to the page ready topic once. This was impacting the AlfFilteredList widget because it was calling processWidgets twice. A check has been added to ensure only one subscription is created and a unit test has been created to prevent future regressions.
=> AKU-508: Ensure only once page widgets subscription is created in lists

aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedViewItem.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfSimpleView.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfTableView.js, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/MoreInfo.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/renderers/Tags.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/main/resources/alfresco/renderers/i18n/Property.properties, aikau/src/test/resources/alfresco/documentlibrary/views/AlfDetailedViewTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Tags.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-503 and has made updates to both the alfresco/renderers/InlineEditProperty widget and how it is used within the various views. It also updates in particular how the cm:title is displayed in views. There is a new check within the InlineEditProperty widget on whether or not the current user has edit permissions (this is a configurable property) and editing will automatically be disabled if they do not. After discussion with UX it was agreed to always display the title and display a warning if the property is not actually set, but we will further review this in the future. Unit tests have been updated.
=> AKU-503: InlineEditProperty updates

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/test/resources/alfresco/lists/PaginatorVisibilityTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/PaginatorVisibility.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/PaginatorVisibility.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/PaginatorVisibility.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-290 to add support for the alfresco/lists/Paginator to be configured to hide when lists request data and displayed when data is successfully retrieved. The default behaviour is for this to be off because it preserves existing behaviour and also the data request/response topics are variable/configurable. Unit tests have been added to verify behaviour.
=> AKU-290: Support for pagination hiding on list loading

aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js
This is a follow on to the previous fix for https://issues.alfresco.com/jira/browse/AKU-506 to address some inconsistencies between resizing behaviour of the alfresco/layout/FixedHeaderFooter widget and the other layout widgets. I've tried to make the behaviour more consistent and more expected - one of the main differences here is to switch the default of the "recalculateAutoHeightOnResize" attribute as that was causing confusion when not set with the default "auto" sizing.
This also addresses https://issues.alfresco.com/jira/browse/AKU-483 which wasn't included in the current sprint but made sense to implement whilst I was working on the module and assumes that all numerical heights provided are intended to be pixels (as this also previously caught people out).
I've updated the unit …
=> AKU-506: Make FixedHeaderFooter resize consistently with other layout widgets

aikau/src/main/resources/alfresco/renderers/AvatarThumbnail.js, aikau/src/test/resources/alfresco/renderers/AvatarThumbnailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/AvatarThumbnail.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-509 to ensure that user names containing the % symbol are encoded before being used in the avatar image URL
=> AKU-509: AvatarThumbnail encoding

aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-522 to provide a configurable way in which to stop lists from publishing requests to load data as soon as the list is created.
=> AKU-522: Add configuration to stop lists from loading immediately

aikau/src/main/resources/alfresco/renderers/Tags.js
This PR is a minor update to https://issues.alfresco.com/jira/browse/AKU-503 to add default warnings for the Tags renderer when the Node has not been tagged.
=> AKU-503: Default tag warnings

aikau/src/main/resources/alfresco/header/css/SearchBox.css
Addresses issue [AKU-499](https://issues.alfresco.com/jira/browse/AKU-499) to fix the incorrect search icon placement by moving the icon 3px to right as discussed with Kev. Has been tested in local Share and looks fine without side-effects. Looks like it might have been introduced back in March, as part of a search customisation story.
=> AKU-499: Incorrect search icon placement

aikau/src/main/resources/alfresco/accessibility/AccessibilityMenu.js, aikau/src/main/resources/alfresco/accessibility/css/AccessibilityMenu.css, aikau/src/main/resources/alfresco/accessibility/templates/AccessibilityMenu.html, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/accessibility/AccessibilityMenuTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/accessibility/AccessibilityMenu.get.js, aikau/src/test/resources/testApp/js/aikau/testing/css/CssOverrides.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-510 to update the alfresco/accessibility/AcessibilityMenu so that it conforms to our BEM CSS approach and correctly focuses on the items linked to in the skip links. The unit tests have been updated to verify this behaviour.
=> AKU-510: Accessibility focus updates

aikau/src/main/resources/alfresco/renderers/Tags.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Tags.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/TaggingMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-504 to improve the testing of the alfresco/renderers/Tags widget. Along the way a couple of minor bugs have been found and resolved.
=> AKU-504: Added additinal Tags renderer tests with minor fixes

aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-514 to make some improvements on the layout of the alfresco/layout/AlfSideBarContainer. The key update is that the resize bar is not outside the main sidebar node so that it doesn't overlap any of the sidebar content (this is particularly important when the sidebar contains a scrollbar as it hides the scrollbar). It also ensures that the resize bar is always accessible via the mouse (although a z-index has now been set to ensure this is possible).
=> AKU-514: Sidebar improvements.

aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js
Adds a new unit test to ensure [AKU-525](https://issues.alfresco.com/jira/browse/AKU-525) described bug will not occur again in future. Also updates FilteredListTest to try and solve intermittent failure.
=> AKU-525: AlfHashList loading problem

aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js
Update to doclib.lib.js to pass on useHash from options to PathTree (see https://issues.alfresco.com/jira/browse/AKU-494)
=> AKU-494: Update doclib.lib.js to use useHash option on PathTree config

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-460 to wrap user search terms in brackets when hidden search terms are configured for an alfresco/header/SearchBox. The unit test has been updated to reflect this change and converted to use DebugLog.
=> AKU-460: Update hidden search term handling in SearchBox

aikau/src/main/resources/alfresco/accessibility/css/AccessibilityMenu.css, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/main/resources/alfresco/debug/css/WidgetInfo.css, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumb.css, aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/css/Title.css, aikau/src/main/resources/alfresco/layout/css/Twister.css, aikau/src/main/resources/alfresco/navigation/css/Link.css, aikau/src/main/resources/alfresco/navigation/css/_HtmlAnchorMixin.css, aikau/src/main/resources/alfresco/preview/PdfJs/css/Outline.css, aikau/src/main/resources/alfresco/renderers/InlineEditPropertyLink.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/main/resources/alfresco/renderers/css/InlineEditPropertyLink.css, aikau/src/main/resources/alfresco/renderers/css/Property.css, aikau/src/main/resources/alfresco/renderers/css/PropertyLink.css, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This is an initial commit for https://issues.alfresco.com/jira/browse/AKU-528 (I expect that there will potentially be subsequent commits to update the defaults.less file). 
I've been through all the existing widget modules and updated them to use new LESS variables for styling links. Currently the defaults remain as they were previously (e.g. no link specific colour and no underline). However, I'd like to get this reviewed and merged as an initial starting point. If nothing else this will allow themes to be created that change the links colour and decoration.
=> AKU-528: Updated link decoration to be based off LESS variables

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-521 to update the alfresco/forms/controls/DateTextBox to mixin in the alfresco/forms/controls/utilities/TextBoxValueChangeMixin module to setup up the keyboard entry change events. The unit test has been updated with additional widgets based on the model provide in the JIRA issue.
=> AKU-521: DateTextBox updates for keyboard entry rule processing

aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/test/resources/alfresco/renderers/ThumbnailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Thumbnail.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-515 to ensure that pubSubScope is respected in the alfresco/renderers/Thumbnail widget. The unit test has been updated to verify scoping.
=> AKU-515: Correct invalid falsy logic for global/parent publish

aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AutoHeightFixedHeaderFooter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-529 to ensure that when an alfresco/layout/FixedHeaderFooter widget is explicitly configured with "auto" height (as opposed to not setting any value which also defaults to auto height calculation) that resizing occurs but does NOT update the height setting. This ensures that repeating resize events are correctly processed. The unit test was testing the behaviour but the test model was not addressing the explicit height setting.
=> AKU-529: FixedHeaderFooter resize handling update

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/utilities/RulesEngineMixin.js, aikau/src/main/resources/alfresco/forms/css/Form.css, aikau/src/main/resources/alfresco/forms/templates/Form.html, aikau/src/main/resources/alfresco/header/LicenseWarning.js, aikau/src/main/resources/alfresco/header/Warning.js, aikau/src/main/resources/alfresco/header/css/Warning.css, aikau/src/main/resources/alfresco/header/templates/Warning.html, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/forms/FormWarningsTest.js, aikau/src/test/resources/alfresco/header/WarningTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormWarnings.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormWarnings.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormWarnings.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Warning.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-523 to add support for configurable warnings in forms. The warnings are processed using the same rules engine that was originally in the BaseFormControl (the code has now been abstracted to a RulesEngineMixin module so that it can be shared with the Form widget). I've made updates to alfresco/header/Warning to add support for dynamic visibility over pub/sub and have applied BEM to it. 
The unit tests added ensure that the warnings work for both regular forms and forms in dialogs. The warning can also be styled via LESS variables.
=> AKU-523: Warnings in forms support

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/main/resources/alfresco/debug/css/WidgetInfo.css, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/documentlibrary/css/AlfBreadcrumb.css, aikau/src/main/resources/alfresco/header/SetTitle.js, aikau/src/main/resources/alfresco/header/Title.js, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/css/Title.css, aikau/src/main/resources/alfresco/header/templates/Title.html, aikau/src/main/resources/alfresco/layout/css/Twister.css, aikau/src/main/resources/alfresco/navigation/css/Link.css, aikau/src/main/resources/alfresco/navigation/css/_HtmlAnchorMixin.css, aikau/src/main/resources/alfresco/preview/PdfJs/css/Outline.css, aikau/src/main/resources/alfresco/renderers/PropertyLink.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditPropertyLink.css, aikau/src/main/resources/alfresco/renderers/css/Property.css, aikau/src/main/resources/alfresco/renderers/css/PropertyLink.css, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Title.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/Title.get.js, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This PR makes further updates to https://issues.alfresco.com/jira/browse/AKU-528. Primarily the purpose was to add in additional LESS configuration for link hover states to allow themes to be customized so that different decoration and colour can be applied based on whether or not the mouse is hovering over the link or not. 
I've also made further updates around the alfresco/header/Title to improve accessibility by ensuring that title are only links when they have a targetUrl set and defining dedicated LESS variables for title links (because I think they should be special cased).
Default Aikau LESS variable remain consistent with Share 5.0.x (e.g no text decoration or colours for links).
=> AKU-528: Further link updates

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/documentlibrary/views/css/AlfFilmStripView.css, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/layouts/Carousel.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/Carousel.css, aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/css/DebugLog.css, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html, aikau/src/test/resources/alfresco/dashlets/InfiniteScrollDashletTest.js, aikau/src/test/resources/alfresco/dnd/FormCreationTest.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/FilmStripView.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/NodesMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/DocumentLibrary/policiesFolderTemplate.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/Nodes/seedData.js
This pull request is a replacement for #487, and deals with various issues arising from the code review. Most significantly, a second, paginated film strip has been added to the test page and the code and tests updated to support it.
> _Previous pull request:_
> This pull request primarily addresses AKU-526 and adds support for infinite scrolling in FilmStripView. Additionally, DebugLog has been updated to add an exclude-filter (in addition to the include-filter) and to allow selecting/copying of the payloads and a new mock XHR class has been created which will mock the document library on a large, generic scale. Finally, a few tests were made more robust, which were failing with timing issues on Chrome.
=> AKU-526: Add support for infinite scrolling in FilmStripView (replacement)

aikau/src/main/resources/alfresco/documentlibrary/views/layouts/AlfFilmStripViewDocument.js, aikau/src/main/resources/alfresco/layout/LeftAndRight.js, aikau/src/main/resources/alfresco/renderers/PropertyLink.js, aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/search/FilmStripViewSearchResult.js, aikau/src/main/resources/alfresco/search/SearchFilmStripView.js, aikau/src/main/resources/alfresco/search/SearchThumbnailMixin.js, aikau/src/main/resources/alfresco/search/css/FilmStripViewSearchResult.css, aikau/src/main/resources/alfresco/search/css/SearchFilmStripView.css
This PR has been created in relation to the work done for https://issues.alfresco.com/jira/browse/AKU-526 (although it is not the primary task associated with that issue). AKU-526 is about making the alfresco/documentlibrary/views/AlfFilmStripView work with infinite scrolling lists, but this PR is specifically to extending the AlfFilmStripView to provide a new view that is dedicated exclusively to working with the alfresco/search/AlfSearchList (which does not need to be infinitely scrolled).
This new view provides the bare minimum implementation for getting a film strip style view into Alfresco Share faceted search and addresses the issues of inconsistent API and additional node types (i.e. nodes that are neither documents nor folders).
No unit tests have yet been added for this as we …
=> AKU-526: Filmstrip view for search previews and links

aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/layouts/Carousel.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js
This PR makes some updates following the initial PRs for https://issues.alfresco.com/jira/browse/AKU-526. After some preliminary testing in Share we hit a few issues that needed to be resolved because the AlfSearchList was not calling the processLoadedData function so wasn't taking advantage of some of the improvements made in the previous PR. This has now been corrected along with some defensive code updates and some other minor corrections
=> AKU-526: Filmstrip view with infinite scroll corrections

aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-537 to pass the "columns" configuration from the alfresco/documentlibrary/views/AlfGalleryView to the alfresco/documentlibrary/AlfGalleryViewSlider that it defines as an additional control for the view. 
The unit test page has been updated to override the default configuration and the tests updated to take this into consideration.
=> AKU-537: Pass gallery view columns config to slider

aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js
Tests are empty, to be filled in once layout issues are resolved with FilmStripView (see https://issues.alfresco.com/jira/browse/AKU-538)
=> Add extra tests to FilmStrip to cover possible regressions

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/main/resources/alfresco/forms/controls/utilities/UseServiceStoreMixin.js, aikau/src/test/resources/alfresco/forms/controls/ComboBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ComboBox.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses issue [AKU-534](https://issues.alfresco.com/jira/browse/AKU-534) by changing the default value of `searchStartsWith` to be `false`. This change affects the FilteringSelect, MultiSelect and ComboBox controls. More details are in the linked JIRA ticket.
=> AKU-534: Single select drop drop should filter anywhere

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This addresses issue [AKU-516](https://issues.alfresco.com/jira/browse/AKU-516) which is about multiple XHR requests being made. In making minor changes to BaseFormControl and MultiSelect, we have removed two of the three calls, meaning that there should now only be one call made. Also did some minor refactoring of the MockXHR log.
=> AKU-516: MultiSelectInput widget makes several calls to the server

aikau/src/main/resources/alfresco/dialogs/AlfFormDialog.js, aikau/src/main/resources/alfresco/dialogs/_AlfCreateFormDialogMixin.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/DocumentPicker.js, aikau/src/main/resources/alfresco/forms/controls/Picker.js, aikau/src/main/resources/alfresco/forms/controls/SitePicker.js, aikau/src/main/resources/alfresco/header/CurrentUserStatus.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-518 to set the primary button style (via the "call-to-action" CSS class) onto certain buttons that are created within Aikau.
=> AKU-518: Set call-to-action on certain buttons

aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/test/resources/alfresco/layout/DynamicHorizontalLayoutTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicHorizontalLayout.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicHorizontalLayout.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicHorizontalLayout.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-478 to update the alfresco/layout/HorizontalWidgets to take the visibilityConfig and invisibilityConfig of it's child widgets into consideration when calculating the widths of those widgets. It sets up a subscription for each unique topic used across all the visibility rules where each subscription is bound to the onResize function. This means that each time a child of a HorizontalWidgets changes visibility the widths of all the children will be re-calculated to ensure that all the available horizontal space is consumed without overflow.
=> AKU-478: Horizontal Widget Resizing

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/i18n/BaseFormControl.properties
This is a further recommended update from the user assistance team to make the help popup alt text more accessible (it also ensures that localization is used properly with token substitution)
=> Further updates from the user assistance team

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/AlfFilmStripViewDocument.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/menus/AlfSelectedItemsMenuItem.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/main/resources/alfresco/renderers/actions/DownloadAsZip.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js
This PR is some further updates related to https://issues.alfresco.com/jira/browse/AKU-532. In particular this addresses support when "rawData" is used (e.g. using APIs directly on the Repository rather than the Share tier), has a standalone client icon rendering fallback and ensures that selected items are cleared when the list data is cleared (e.g. to support the use in faceted search when applying facets). I've also included some general improvements to the doclib.lib.js file.
=> AKU-532: Further download as zip updates

aikau/src/main/resources/alfresco/services/SearchService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-549 to remove the default facets sent by the SearchService on XHR requests to the Search API. We shouldn't be including any default facets if the admin has configured Share to remove all facets.
=> AKU-549: Remove default facets from search service

aikau/src/main/resources/alfresco/css/less/defaults.less
This PR addresses https://issues.alfresco.com/jira/browse/AKU-543 to remove the use of bold fonts on buttons.
=> AKU-543: Removed use of bold font on buttons

aikau/src/main/resources/alfresco/header/css/Warning.css
Since the warning component is now used to display Share Services AMP version mismatch, it is more visible and shows that an old margin setting is still present - not needed and adds an unwanted horizontal scrollbar.
=> Removed obsolete negative margin from Warning component (used in Alfresco Share)

aikau/src/main/resources/alfresco/forms/controls/utilities/RulesEngineMixin.js, aikau/src/test/resources/alfresco/forms/controls/utilities/RulesEngineTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/utilities/RulesEngine.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/utilities/RulesEngine.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/utilities/RulesEngine.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-541 to provide an additional attribute that can be added to visibilityConfig, requirementConfig and disablementConfig to support OR based evaluation (the default remains as AND based evaluation). The new attribute is "rulesMethod" and if set to any value other than "ANY" will behave exactly as before.
=> AKU-541: RulesEngine updates

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-556 to ensure that the "In Folder" links in the alfresco/search/AlfSearchResult publish the correct information to link to. The problem was caused by fault logic on determining whether or not the result should be viewed in the context of a site or in the context of the repository.
=> AKU-556: Ensure "In folder" link is correct in AlfSearchResult

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/Paginator.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-559 to resolve an issue with filtered lists. The main cause of the problem was a missing dependency in the paginator widget (which resulted in an XHR request being made and through processing out of order) however I've also tidied up the code flow to make it more consistent.
=> AKU-559: FilteredList fix

aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js
This PR addresses the 2nd bug described in the re-opened https://issues.alfresco.com/jira/browse/AKU-507 issue. The problem was that filter removal was not being correctly tracked. Strangely there was a unit test for this that was not failing, however I suspect that this was to do with the topic being searched for.
=> AKU-507: Track removal of filters accurately

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/layout/HeightMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/Carousel.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreviewPlugin.js, aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js, aikau/src/test/resources/alfresco/layout/HeightMixinTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/HeightMixin.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/HeightMixin.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/HeightMixin.get.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/TestHeight.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/css/TestHeight.css, aikau/src/test/resources/testApp/js/aikau/testing/widgets/templates/TestHeight.html
This PR addresses https://issues.alfresco.com/jira/browse/AKU-538 to primarily ensure that the preview carousel in the FilmStripView is the correct height but also provides a new mixin that can be used for setting height of widgets. Tests have been updated and tweaks have been made to the way that dialogs and previews are displayed in order to get the optimum sizes.
=> AKU-538: Created HeightMixin module

aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/menus/css/_AlfMenuItemMixin.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-558 to suppress text-decoration in any menu item regardless of whether or not it is a link.
=> AKU-558: Suppress text-decoration on menu links

aikau/src/main/resources/alfresco/core/ObjectTypeUtils.js, aikau/src/main/resources/alfresco/core/ValueDisplayMapMixin.js, aikau/src/main/resources/alfresco/renderers/DateLink.js, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/InlineEditSelect.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/main/resources/alfresco/renderers/templates/Property.html, aikau/src/test/resources/alfresco/documentlibrary/views/AlfDetailedViewTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-563 to ensure that when InlineEditProperty widgets (and their sub-classes) are edited that the new value is rendered using all the original configuration to ensure that appropriate warnings and styles are applied.
=> AKU-563: Inline Edit update re-rendering support

aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/test/resources/alfresco/renderers/PublishingDropDownMenuTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishingDropDownMenu.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-569 to add support for having alfresco/renderers/PublishingDropDownMenu renderers disabled based on evaluation each item being rendered.
=> AKU-569: Updated PublishingDropDownMenu to support disabled state

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/_NavigationServiceTopicMixin.js, aikau/src/test/resources/alfresco/services/DeleteSiteTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DeleteSite.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DeleteSite.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DeleteSite.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-566 to add support for optional redirect when deleting sites.
=> AKU-556: Added support for site deletion with redirect

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/FullScreenDialogTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FullScreenDialogs.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FullScreenDialogs.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FullScreenDialogs.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-557 to provide for full screen dialog support. This new feature can be used by including fullScreenMode and fullScreenPadding attributes in dialog creation payloads consumed by the alfresco/services/DialogService
=> AKU-557: Support for full screen dialogs

aikau/src/main/resources/alfresco/documentlibrary/AlfGalleryViewSlider.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/test/resources/alfresco/documentlibrary/AlfGalleryViewSliderTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/GalleryViewSlider.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/GalleryViewSlider.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/GalleryViewSlider.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/MockPreferenceService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-576 to ensure that the AlfGalleryViewSlider uses the configured columns default when a user preference isn't available (with a fallback to a default value when the configured value is invalid). It also adds support for customizing the columns preference property.
=> AKU-576: Gallery view slider preferences

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectDocumentListItems.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfSimpleView.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/menus/AlfMenuBarSelectItems.js, aikau/src/main/resources/alfresco/menus/AlfSelectedItemsMenuItem.js, aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/menus/AlfMenuBarSelectItemsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfFormDialogMenuItem.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuBarSelect.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuBarSelectItems.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-551 to ensure that when switching views any item selection on one view is retained on the next.
=> AKU-551: Retain item selection when switching views

aikau/src/main/resources/alfresco/forms/controls/ComboBox.js, aikau/src/test/resources/alfresco/forms/controls/ComboBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ComboBox.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-575 to ensure that the alfresco/forms/controls/ComboBox widget listens to selection of items in the drop-down as well as keyboard entry to trigger value change updates.
=> AKU-575: Update ComboBox change events to include item selection

aikau/src/main/resources/alfresco/logging/DebugLog.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-567 to add defensive code to prevent a potential JS exception that was reported as occurring in the DebugLog
=> AKU-567: Added defensive code into DebugLog

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-572 and fixes the issue of resize and creation publications not always being adequately provided when dynamically creating tabs- especially where lists are concerned. I've replicated the failing scenario into the test case page and have added a unit test to prevent future regressions.
=> AKU-572: Updated to tab container rendering and resizing

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-581. This is a strange issue that only seems to impact the Chrome browser that results in form control labels being hidden when an unrelated HTML element has a class removed from it (resizing the browser resolves the issue, but this is not a resize issue). This doesn't impact Firefox and there are no CSS selectors being triggered. There are no tests because this was an incredibly tricky issue to reproduce. It only seems to occur when the field is required. But setting the display value for the label explicitly seems to resolve the issue.
=> AKU-581: Set explicit CSS selector for form control label

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-559 and addresses the issue of async order when calling processWidgets that can occur when JS dependencies are missing. In particular this occurs where Surf has not been able to include locale specific dependencies (so this problem only occurs when the browser is using the non-default locale). It adds support for mapping the final result of a call to processWidgets with a specific ID of that call.
=> AKU-559: Support async widget processing callbacks

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-579 in order to ensure that the correct overflow settings are passed for form dialogs. Previously we were not passing through the handleOverflow configuration correctly.
=> AKU-579: Update how form dialog handles overflow

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfTabContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-573 to prevent multiple tabs with the same ID being added to a tab container. Instead, if a tab with the ID is found to already exist the existing tab will be re-selected. I've also improved the way in which the tabs are given "id" attributes in the DOM to make the AlfTabContainer easier to test and as such have updated the existing unit tests.
=> AKU-573: No duplicate tabs

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/config/web-application-config.xml, aikau/src/main/resources/alfresco/core/css/Core.css, aikau/src/main/resources/alfresco/core/css/Icons.css, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/documentlibrary/css/AlfGalleryViewSlider.css, aikau/src/main/resources/alfresco/header/css/AlfCascadingMenu.css, aikau/src/main/resources/alfresco/header/css/AlfMenuBarPopup.css, aikau/src/main/resources/alfresco/header/css/AlfMenuItem.css, aikau/src/main/resources/alfresco/header/css/Header.css, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/css/Title.css, aikau/src/main/resources/alfresco/menus/css/AlfCheckableMenuItem.css, aikau/src/main/resources/alfresco/menus/css/AlfContextMenu.css, aikau/src/main/resources/alfresco/menus/css/AlfDropDownMenu.css, aikau/src/main/resources/alfresco/menus/css/AlfMenuBar.css, aikau/src/main/resources/alfresco/menus/css/AlfMenuBarPopup.css, aikau/src/main/resources/alfresco/menus/css/AlfMenuBarToggle.css, aikau/src/main/resources/alfresco/menus/css/AlfMenuGroup.css, aikau/src/main/resources/alfresco/menus/css/_AlfMenuItemMixin.css, aikau/src/main/resources/alfresco/navigation/css/Link.css, aikau/src/main/resources/alfresco/navigation/css/_HtmlAnchorMixin.css, aikau/src/main/resources/alfresco/renderers/css/QuickShare.css, aikau/src/main/resources/alfresco/renderers/css/_ActionsMixin.css, aikau/src/test/resources/testApp/WEB-INF/config/web-application-config.xml
This change allows Aikau app developers the freedom to change the top-level selector from "alfresco-share" to something else and still make use of the standard Aikau widget CSS.
The top-level selector is now defined as a LESS default in src/main/resources/alfresco/css/less/defaults.less:
```css
// Root selector
@alfresco: alfresco-share;
```
In a custom theme an example override would be:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<theme>
<id>sfs-theme</id>
<title>SFS Theme</title>
<css-tokens>
<less-variables>
@alfresco: somevalue;
</less-variables>
</css-tokens>
</theme>
```
NOTE! This has a dependency on fixing the compression of CSS files in Surf - this is currently achieved with the following *mandatory* application context bean override to remove *.css from compression step - …
=> Extracted top-level CSS selector as LESS variable

aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/main/resources/alfresco/layout/templates/AlfSideBarContainer.html, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-574. I've gone through the implementation to use LESS with a BEM approach. But the fix is somewhat hidden in that all the children of the sidebar element (apart from the resize bar) have display:none applied when the sidebar is closed. This means that they cannot prevent the open/close toggle from being used. But as an added measure I've increased the z-index as well (making sure that it is less than the dialog z-index)
=> AKU-574: Sidebar contents hidden on collapse

aikau/src/main/resources/alfresco/forms/controls/css/TextArea.css, aikau/src/test/resources/alfresco/forms/controls/TextAreaTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TextArea.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TextArea.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TextArea.get.js
This addresses [AKU-468](https://issues.alfresco.com/jira/browse/AKU-468), which is about the TextArea font not being the same as the TextBox font. Have updated the CSS and created a test page/suite to prevent regression.
=> AKU-468: TextArea font not same as TextBox font

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SearchService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SearchMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-584 to ensure that the SearchService uses the correct scope when making XHR requests. The unit tests have been updated to prevent future regressions.
=> AKU-584: Ensure correct scope on SearchService XHR

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/layout/Twister.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js
This PR is another (hopefully the final) attempt at resolving https://issues.alfresco.com/jira/browse/AKU-559. This time I've updated CoreWidgetProcessing to make use of promises to ensure that the allWidgetsProcessed function is only called when widgets have really finished being created.
=> AKU-559: Update CoreWidgetProcessing to use promises

aikau/src/main/resources/alfresco/services/LoginService.js, aikau/src/main/resources/alfresco/services/LogoutService.js
Modified URLs for default Login and Logout services to use SERVICECONTEXT rather than PAGECONTEXT.
For the default installation of Aikau with example archetype the service context redirects to the page context - so it makes no difference, which is also true for Alfresco Share. However for some future apps, we may want the PAGECONTEXT to rewrite to something quite different (such as to an authenticated aikau webscript page URL) - and therefore having login/logout use the more correct SERVICECONTEXT will allow that.
=> Modified URLs for default Login and Logout services.

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/config/surf-config.xml, aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/config/web-application-config.xml, aikau/pom.xml, aikau/src/main/resources/spring-context-config/custom-web-framework-application-context.xml
This is a follow up to https://github.com/Alfresco/Aikau/pull/539 to remove the requirement for 3rd party modules to add in the bean override. This will need to be removed once we have Alfresco releases containing AKU-589.
=> Bean override config

aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This addresses [AKU-464](https://issues.alfresco.com/jira/browse/AKU-464) by allowing a special value of "TODAY" to set the initial value to today's date.
=> AKU-464: Set DateTextBox to today

aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This addresses [AKU-465](https://issues.alfresco.com/jira/browse/AKU-465) which requests placeHolder attribute support for the DateTextBox and TextArea controls. Unfortunately, there's [a bug in the underlying Dojo control](https://bugs.dojotoolkit.org/ticket/11145) for the TextArea that means we can't add support there, but it's been added to the DateTextBox control, and the tests updated.
=> AKU-465: placeHolder config option for DateTextBox and TextArea is missing

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/main/resources/alfresco/dialogs/_AlfCreateFormDialogMixin.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/main/resources/alfresco/layout/DynamicWidgets.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/layout/HeightMixin.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreviewPlugin.js, aikau/src/main/resources/alfresco/search/css/AlfSearchResult.css, aikau/src/main/resources/alfresco/upload/UploadHistory.js, aikau/src/test/resources/alfresco/accessibility/SemanticWrapperMixinTest.js, aikau/src/test/resources/alfresco/dashlets/DashletTest.js, aikau/src/test/resources/alfresco/layout/BasicLayoutTest.js, aikau/src/test/resources/alfresco/layout/DynamicWidgetsTest.js, aikau/src/test/resources/alfresco/layout/HeightMixinTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicWidgets.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicWidgets.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/DynamicWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/ParentHeight.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/ParentHeight.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/ParentHeight.get.js
This PR has resulted from the work done for an internal presentation (work done under https://issues.alfresco.com/jira/browse/AKU-568). It adds a new alfresco/layout/DynamicWidgets layout container that was needed for a demo, as well as adding a new heightMode of "PARENT" for the alfresco/layout/HeightMixin (and updates the alfresco/layout/FixedHeaderFooter widget to use that mixin). There are a couple of other minor tweaks as well.
=> AKU-568: Updates resulting from presentation creation

aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/config/vm/Config.js, aikau/src/test/resources/intern.js
I've found that by increasing the time outs that the unit tests pass more reliable when run in bulk.
=> Increase timeouts to improve test consistency

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/LoggingService.js, aikau/src/test/resources/alfresco/services/LoggingServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/LoggingService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/LoggingService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/LoggingService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-578 (and issue #530) to provide support for suppressing user preferences for the LoggingService.
=> AKU-578: Update logging service to suppress user prefs

aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css
This is a follow up PR for to https://issues.alfresco.com/jira/browse/AKU-574. This removes a superfluous CSS selector
=> AKU-574: Remove superfluous CSS selector

aikau/src/main/resources/alfresco/renderers/PublishingDropDownMenu.js, aikau/src/main/resources/alfresco/renderers/i18n/PublishingDropDownMenu.properties
Update the default text used for the cancel button title attribute, as recently added in pull request #540, as it was using inappropriate language.
=> Update "cancel message"

aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-587 to ensure that the dialog body is correctly sized and removes the dependency on LESS escaped calculations.
=> AKU-587: Dialog resizing

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-593. In the updates made for 1.0.36 I neglected to take the buttons bar into consideration when calculating resizing the dialog. This PR will be reviewed and merged into develop and then cherry-picked into a 1.0.36.1 hotfix release.
=> AKU-593: Take buttons bar into consideration when calculating dialog sizes

aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/core/_EventsMixin.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/test/resources/alfresco/layout/DynamicHorizontalLayoutTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-588. It ensures that resize publications are made from the alfresco/layout/HorizontalWidgets module when widths are dynamically updated. This will be merged to develop and then cherry picked for a 1.0.36.1 hotfix release.
=> AKU-588: Ensure resize events published on dynamic width resizing

aikau/src/main/resources/alfresco/core/DynamicWidgetProcessing.js, aikau/src/main/resources/alfresco/documentlibrary/AlfToolbar.js, aikau/src/main/resources/alfresco/layout/LeftAndRight.js, aikau/src/test/resources/alfresco/layout/BasicLayoutTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/BasicLayouts.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-595 to ensure that the right aligned widgets in the LeftAndRight module are ordered correctly. The unit tests have been updated to verify the behaviour.
=> AKU-595: Ensure that right ordering in LeftAndRight is correct

aikau/src/main/resources/alfresco/search/css/SearchThumbnail.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-596. This is a defensive CSS update required for future deployment of Share in the Cloud.
=> AKU-596: Prevent bad thumbnail renditions corrupting search view

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-597. Because of changes to the way in which the AlfSearchList is now initialised the facetFilters object is not getting initialised from the hash correctly.
=> AKU-597: Ensure facets from URL hash are applied to search

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-599 to ensure that search term request parameters generated by the SearchBox are encoded to ensure that they're rendered correctly in the search page.
=> AKU-599: Ensure that SearchBox generated URLs are encoded

aikau/src/main/resources/alfresco/header/SearchBox.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-554 to make the live search REST API URIs configurable.
=> AKU-554: Make live search URLs configurable

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/AlfTagFilters.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/renderers/Tags.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/TagService.js, aikau/src/main/resources/alfresco/services/_TagServiceTopics.js, aikau/src/main/resources/alfresco/services/actions/WorkflowService.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/documentlibrary/TagFiltersTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/reporters/AikauConcurrentReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/TagFilters.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/TagFilters.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/TagFilters.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/TagsMockXhr.js
This addresses [AKU-586](https://issues.alfresco.com/jira/browse/AKU-586), and deals with the issues with using alfresco/documentlibrary/AlfTagFilters in a scoped environment. It has been tested in Share locally, and new tests have been created and a full test run completed succcesfully. CoreXhr has also been updated to support scoped responses. Additionally, various topics constants have been updated, some small improvements to TestCommon helper methods have been made and the test reporter has had its environment detection/reporting improved.
=> AKU-586: alfresco/documentlibrary/AlfTagFilters does not work in a scoped environment

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/Delete.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/GenericMockXhr.js
As part of the work for [AKU-591](https://issues.alfresco.com/jira/browse/AKU-591), I fixed the test page for the Delete action, as the mock XHR service it was using failed on attempting the Delete, and so didn't fire the reload event. The actual bug is apparently no longer an issue, after other fixes, so this is just to tidy up the test page and makes no changes to the actual code.
=> AKU-591: Delete action should reload document list

aikau/src/main/resources/alfresco/forms/controls/Select.js, aikau/src/main/resources/alfresco/forms/controls/css/Select.css, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/intern_local.js, aikau/src/test/resources/reporters/AikauConcurrentReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/Twister.get.js
This addresses issue [AKU-467](https://issues.alfresco.com/jira/browse/AKU-467) and permits restricting the width of a Select dropdown to the size of the base control. Also, update intern_local configuration to permit using the new test reporter (but without turning it on yet), and fix a bug with running multiple environments. Finally, update a couple of occasionally-failing tests to make them run more reliably (GalleryView keyboard test and Twister test).
=> AKU-467: Truncate the text for the select widget element automatically

aikau/src/main/resources/alfresco/core/NotificationUtils.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/dashlets/Dashlet.js, aikau/src/main/resources/alfresco/preview/PdfJs/PDFFindController.js, aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js, aikau/src/main/resources/alfresco/renderers/AvatarThumbnail.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/QuaddsService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/CreateTemplateContentService.js, aikau/src/main/resources/alfresco/services/actions/ManageAspectsService.js, aikau/src/main/resources/alfresco/services/actions/WorkflowService.js
Update references to "ALF_DISPLAY_NOTIFICATION". Also fix JSHint errors in two files: `alfresco/preview/PdfJs/PDFFindController` and `alfresco/services/QuaddsService`. Full test suite has been run on FF/Chrome, and JSDoc confirmed working.
=> Update references to "ALF_DISPLAY_NOTIFICATION"

aikau/src/main/resources/alfresco/search/i18n/AlfSearchList.properties, aikau/src/test/resources/alfresco/services/SearchServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-602 to update the search failure message.
=> AKU-602: Update search failure message

aikau/src/main/resources/alfresco/header/SearchBox.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-555 to make it easier to extend the alfresco/header/SearchBox with a view to changing how the live search items are rendered.
=> AKU-555: Externalise live search item creation

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/forms/TabbedControls.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/core/WidgetCreationTest.js, aikau/src/test/resources/alfresco/forms/controls/AsyncFormControlLoadingTest.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/WidgetCreation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-603 to defensively code against duplicate IDs causing failure to process models. This problem was found when creating dialogs (with different IDs) that render form controls that share IDs. Because the dialogIds are different the first dialog is not destroyed so the form controls attempt to use an already registered id. This was particularly problematic with the TabbedControl layout. This has been fixed and the unit tests updated to prevent regressions.
=> AKU-603: Defensively code against duplicate IDs

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js
This is another PR as part of the fall out of changes made for https://issues.alfresco.com/jira/browse/AKU-559. This change ensures that the filterTopic subscriptions are only setup once all the filter widgets have successfully been created.
=> AKU-559: Ensure that filterTopic subscriptions are set up when filters have been created

aikau/src/main/resources/alfresco/renderers/_XhrActionsMixin.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/renderers/XhrActionsTest.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/XhrActions.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-607 and https://issues.alfresco.com/jira/browse/AKU-608 to make it possible that XhrActions supports customActions and widgetsForActions attributes. It also exposes those configuration attributes on the AlfSearchResult module so that they can be used in search.
=> AKU-608: XhrActions updates

aikau/src/main/resources/alfresco/documentlibrary/AlfTagFilters.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/renderers/Tags.js, aikau/src/test/resources/alfresco/documentlibrary/TagFiltersTest.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/TagFilters.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/TaggingMockXhr.js
This addresses [AKU-598](https://issues.alfresco.com/jira/browse/AKU-598) and adds support for the ALF_DOCUMENT_TAGGED event.
=> AKU-598: "ALF_DOCUMENT_TAGGED" is neither fired nor properly handled

aikau/src/main/resources/alfresco/layout/DynamicVisibilityResizingMixin.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/layout/HorizontalWidgets.js, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-600 to ensure that the alfresco/layout/FixedHeaderFooter respects dynamic visibility. This abstracts the solution previously applied to the alfresco/layout/HorizontalWidgets module to a new mixin that is then applied to both modules. The unit test has been updated to verify the correct behaviour.
=> AKU-600: Support dynamic visibility in FixedHeaderFooter

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/renderers/Favourite.js, aikau/src/main/resources/alfresco/renderers/Toggle.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/main/resources/alfresco/services/_PreferenceServiceTopicMixin.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/renderers/MultiFavouriteTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/MultiFavourite.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/MultiFavourite.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/MultiFavourite.get.js
This issue addresses https://issues.alfresco.com/jira/browse/AKU-609 to add support for bulk adding and removing of folders and nodes as user favourites.
=> AKU-609: Support for bulk favouriting

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/alfresco/layout/HeightMixinTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/HeightMixin.get.js
I was evaluating some customer use cases and realised that the full screen dialog mode was not working correctly with the HeightMixin functionality. This PR fixes the issues - I've added unit tests to verify behaviour and to prevent regressions.
=> Some updates to the full screen mode for dialogs

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js
This PR addresses a specific use-case raised by a customer that requires multiple document action payloads to include the currently selected nodes. This update uses the existing object processing capabilities to allow action payloads to include the {nodes} token with payloads to have access to them (this prevents the necessity of an interim service). In particular this addresses situations where the output of the selected items action results in a dialog.
=> Selected items payload use case

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js
This updates the previous changes in #589 to make the processing of action payloads and opt-in behaviour rather than the default. This is needed because an infinite recursion loop can occur when this is used with selected nodes in the Document Library (this was originally written with respect to the search page which uses a different API).
=> Fixes bug introduced in PR 589

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/Tree.js, aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/main/resources/alfresco/forms/controls/utilities/UseServiceStoreMixin.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/main/resources/alfresco/navigation/TreeStore.js, aikau/src/main/resources/alfresco/services/CloudSyncService.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/i18n/CloudSyncService.properties, aikau/src/test/resources/alfresco/services/CloudSyncServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CloudSyncService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CloudSyncService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CloudSyncService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CloudSyncMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/MultiSelectMockService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path1.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path2.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path3.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Path4.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Sites.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Tenants.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/CloudSync/Unauthenticated.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-548 to implement a new service for supporting Cloud Sync operations. In order to complete this task it was necessary to make various changes to core forms behaviour as well as create a new Tree form control.
=> AKU-548: Cloud Sync Service

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/alfresco/layout/TwisterTest.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/alfresco/renderers/actions/DeleteActionTest.js, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/alfresco/services/CrudServiceTest.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/intern_bs.js, aikau/src/test/resources/intern_grid.js, aikau/src/test/resources/intern_local.js, aikau/src/test/resources/intern_sl.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/Delete.get.js, aikau/src/test/resources/testApp/js/aikau/testing/MockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/css/MockXhr.css, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/GenericMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/templates/MockXhr.html
This PR addresses issues [AKU-617](https://issues.alfresco.com/jira/browse/AKU-617) and [AKU-623](https://issues.alfresco.com/jira/browse/AKU-623), which are both updates to do with the user dashboard page usage in SiteService. Also, the MockXhr log functionality has been upgraded, and tests updated to cope with this. A full test suite has been run, and no unexpected failures occurred.
=> AKU-617: Return to user dashboard after joining site / AKU-623: SiteService siteLanding page variable incorrect

aikau/src/main/resources/alfresco/renderers/_SearchResultLinkMixin.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-611 (and issue https://github.com/Alfresco/Aikau/issues/586) to make the target links in the alfresco/renderers/_SearchResultLinkMixin configurable so that they can navigate to a new window/tab. This configuration is exposed through the alfresco/search/AlfSearchResult
=> AKU-611: Search result link target config

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/node/DraggableNodeMixin.js, aikau/src/main/resources/alfresco/search/SearchThumbnailMixin.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/DNDUploadBehaviour.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/DNDUploadBehaviour.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/DNDUploadBehaviour.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-622 to make the drag-and-drop highlighting behaviour configurable as well as the thumbnail dragging behaviour configurable. Lists by default to not expect to support drag-and-drop upload (but the document library overrides this so that it can show the appropriate highlighting). Thumbnails continue to be draggable by default (for backwards compatibility) but the search thumbnails override this setting so that they are not.
I've created a unit test page to verify that everything works but was unable to bend Intern to my will in order to actually get a test working.
=> AKU-622: DND highlighting and drag suppression

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentActionMenuItem.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectDocumentListItems.js, aikau/src/main/resources/alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/layout/LeftAndRight.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/SelectedItemStateMixin.js, aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/SelectedItemsMenuTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/alfresco/services/ActionServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SelectedItemsMenu.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-615. Details of the changes are described in the JIRA ticket, but essentially this moves the selected item state management into a new mixin module and then makes the AlfList the primary manager of item selection state (but allows both the gallery view and selected items popup menu to manage state if configured to do so).
=> AKU-615: Rretain selection on grid resize

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/css/AlfSideBarContainer.css, aikau/src/test/resources/alfresco/layout/AlfSideBarContainerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/SimpleSideBarContainer.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/SimpleSideBarContainer.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/SimpleSideBarContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-634 to update the AlfSideBarContainer so that it can be configured such that the sidebar cannot be resized. The CSS has also been updated to improve the use of LESS variables to make it possible to theme the background colours of the sidebar, the main panel and the borders used on the separators.
=> AKU-634: Non-resizeable sidebar

aikau/src/main/resources/alfresco/renderers/css/GalleryThumbnail.css, aikau/src/main/resources/alfresco/renderers/templates/GalleryThumbnail.html, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryView.get.js
This addresses [AKU-630](https://issues.alfresco.com/jira/browse/AKU-630) and now truncates long text on gallery view thumbnails. It's been tested (as much as possible), and a full test suite run successfully.
=> AKU-630: Truncate GalleryView thumbnail text

aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/lists/ItemSelectionMixin.js, aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/renderers/css/Selector.css, aikau/src/main/resources/alfresco/renderers/templates/Selector.html, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentListTest.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentSelectorTest.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/alfresco/renderers/ThumbnailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocumentList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocumentSelector.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-627 to add optional support for item selection by clicking on it's thumbnail. A new mixin module ItemSelectionMixin has been abstracted from the Selector widget and mixed into both the Selector and Thumbnail widgets. The unit tests have been updated to verify the new functionality works as expected.
=> AKU-627: Thumbnail select on click

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/GalleryViewInfiniteScrollTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewInfiniteScroll.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewInfiniteScroll.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewInfiniteScroll.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-629 to ensure that the layout of thumbnails in the gallery view is correct when there are less results than there are columns. It also includes testing for the Show More link (which we previously weren't testing the behaviour of).
=> AKU-629: Gallery thumbnail layout

aikau/src/main/resources/alfresco/core/_PublishOrLinkMixin.js, aikau/src/main/resources/alfresco/core/css/_PublishOrLinkMixin.css, aikau/src/main/resources/alfresco/logo/Logo.js, aikau/src/main/resources/alfresco/logo/css/Logo.css, aikau/src/main/resources/alfresco/logo/templates/Logo.html, aikau/src/main/resources/alfresco/navigation/_HtmlAnchorMixin.js, aikau/src/test/resources/alfresco/logo/LogoTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/logo/Logo.get.js
This PR addresses [AKU-633](https://issues.alfresco.com/jira/browse/AKU-633) and enables the Logo widget to publish and navigate when clicked. This was achieved by the creation of a new mixin that can now be applied to any widget to achieve a similar effect.
=> AKU-633: Have Logo widget able to publish and link

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfGalleryViewSlider.js, aikau/src/main/resources/alfresco/documentlibrary/ThumbnailSizeSlider.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewThumbnailSizingTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryViewThumbnailSizing.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryViewThumbnailSizing.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryViewThumbnailSizing.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-628 to add support for resizing thumbnails directly (rather than indirectly by adjusting the number of columns).
=> AKU-628: Resize thumbnail view

aikau/src/main/resources/alfresco/layout/ClassicWindow.js, aikau/src/main/resources/alfresco/layout/css/ClassicWindow.css, aikau/src/main/resources/alfresco/layout/templates/ClassicWindow.html, aikau/src/test/resources/alfresco/layout/ClassicWindowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/ClassicWindow.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-644 to ensure that the ClassicWindow widget will show scrollbar when its content is too large to be displayed.
=> AKU-644: Ensure that ClassicWindow overflows when it has fixed dimensions

aikau/src/test/resources/alfresco/documentlibrary/TagFiltersTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/TagFilters.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-640. Although there is no bug to fix I am adding additional tests for rootNode tags in order to be able to demonstrate there is no bug.
=> AKU-640: TagFilters - additional tests

aikau/src/main/resources/alfresco/html/Image.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/layout/css/FixedHeaderFooter.css, aikau/src/test/resources/alfresco/layout/FixedHeaderFooterTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/FixedHeaderFooter.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/unit-test-template.ftl
This addresses issue [AKU-646](https://issues.alfresco.com/jira/browse/AKU-646) by adding some code to detect resizes in the header node. It also fixes some discovered bugs in Image.js and the unit-tests index page template.
=> AKU-646: FixedHeaderFooter: support resizing in header and footer

aikau/src/main/resources/alfresco/debug/css/WidgetInfo.css
Removed transition from widget debug - as is causing some UI elements to transition on initial display when client-debug is true - which is distracting and a waste of battery power.
=> Removed transition from widget debug

aikau/src/main/resources/alfresco/documentlibrary/AlfDocument.js, aikau/src/test/resources/alfresco/documentlibrary/AlfDocumentTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocument.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocument.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocument.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/AlfDocumentMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/Document/DocumentAsObject.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-656 to restore the ability to use "" as the itemProperty on AlfDocument (previously regressed due to overzealous JSHint cleanup). A unit test has been added to prevent future regressions.
=> AKU-656: Update to AlfDocument to ensure "" can be used as itemProperty

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses [AKU-660](https://issues.alfresco.com/jira/browse/AKU-660) which suggests that the MultiSelectInput form control is not working with fixed options. In fact, the use case where it was failing was not providing value properties on the passed-in options, however the general logic around missing properties has been tidied up and some work done (while investigating the bug) on being able to configure the control to infer missing properties. Additionally, a bug whereby clicking on an unfocused control would open and then immediately close the dropdown has been fixed. Unit tests have been added to confirm that using fixed options works with the MultiSelect control, and a full test suite has been run successfully with no unexpected failures.
=> AKU-660: MultiSelectInput form control not working with fixed options

aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/services/CrudServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/CrudService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-658 to update the alfresco/services/CrudService to ensure that requests published from scoped originators use the responseScope when making refresh requests. The unit test has been updated to take advantage of the DebugLog and new tests have been added for scoped originators of publications.
=> AKU-658: Update CrudService to support scoped responses

aikau/src/main/resources/alfresco/html/Image.js, aikau/src/main/resources/alfresco/html/templates/Image.html, aikau/src/main/resources/alfresco/logo/Logo.js, aikau/src/main/resources/alfresco/navigation/_HtmlAnchorMixin.js, aikau/src/test/resources/alfresco/logo/LogoTest.js, aikau/src/test/resources/config/Suites.js
This addresses [AKU-652](https://issues.alfresco.com/jira/browse/AKU-652) and incorrect generation of the title attribute, because it's not looking up the value in the properties file. Test now added to prevent regression.
=> AKU-652: Logo-link title attribute incorrect

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/documentlibrary/css/_AlfDndDocumentUploadMixin.css, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/DNDUploadBehaviour.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-653 to add support for mixing the alfresco/documentlibrary/_AlfDndDocumentUploadMixin into the alfresco/lists/views/layouts/Row. Unfortunately this required some reworking of the mixin because previously we were creating the drag overlay (to display the highlighting) in the mixing widgets parent node. This didn't work for Row because there were multiple overlays at the same node and they were positioned incorrectly and the layout was corrupted. So the overlays are now created in the body. In order to get this working we've needed to use pointer-events none, but as this is a feature only required for releases that support IE10 an up this is acceptable.
=> AKU-653: Upload to row

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/test/resources/alfresco/documentlibrary/FilteredDocumentListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/FilteredDocumentList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/FilteredDocumentList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/FilteredDocumentList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-647 to make the AlfDocumentList extend the AlfFilteredList rather than the AlfSortablePaginatedList.
=> AKU-653: AlfDocumentList now extends AlfFilteredList

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-659 to ensure that full screen dialogs have a fixed position so that they are always visible even if the main window is scrolled.
=> AKU-659: Ensure full screen dialogs have fixed position

aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/layout/css/FixedHeaderFooter.css, aikau/src/main/resources/alfresco/util/domUtils.js, aikau/src/test/resources/config/Suites.js
[AKU-657](https://issues.alfresco.com/jira/browse/AKU-657): Make resize-detection generic
Add new domUtils class, and use it in ResizeMixin to provide a generic resize listener for the FixedHeaderFooter (and other future widgets) to use. Tests unchanged but all passing.
=> AKU-657: Make resize-detection generic

aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-666 to ensure that the file select form controls in the upload and update new version dialogs provided by the content service are required (i.e. so that you can't submit the form dialog unless at least one file is selected)
=> AKU-666: Ensure that file select form control is required when uploading/updating

aikau/src/main/resources/alfresco/html/Image.js, aikau/src/test/resources/alfresco/logo/LogoTest.js
This addresses issue [AKU-662](https://issues.alfresco.com/jira/browse/AKU-662) and ensures that src property outranks the classes property, and update tests where appropriate.
=> AKU-662: alfresco/logo/Logo broken

aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UploadMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-667. The cancel upload request has been updated to actually abort any in progress requests. I've done manual testing for this but have not been able to find a satisfactory way to automate unit testing for this.
=> AKU-667: Cancel upload requests

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This addresses [AKU-661](https://issues.alfresco.com/jira/browse/AKU-661) and encodes the username in the redirection-URL in SiteService that's navigated to after site join-request or departure.
=> AKU-661: Encode URL in SiteService

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/main/resources/alfresco/renderers/actions/Download.js, aikau/src/main/resources/alfresco/renderers/css/_ActionsMixin.css, aikau/src/main/resources/alfresco/renderers/i18n/_ActionsMixin.properties, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/alfresco/services/actions/DownloadTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/Download.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/Download.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/Download.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-416 to add support for a "pure" Aikau download action.
=> AKU-416: Download action

aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/test/resources/alfresco/services/SearchServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SearchService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-664 to ensure that the SearchService can handle requests to change sort order when URL hashing is not being used. The unit tests have been updated to support both hashing and non-hashing scenarios.
=> AKU-644: SearchService no hash sort fix

aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/main/resources/alfresco/navigation/Tree.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.desc.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-663 to ensure that the PathTree highlights nodes when they are expanded. The unit has been updated and the PathTree has also been updated to improve the way in which tree nodes are given IDs to assist with unit testing
=> AKU-663: Path tree node highlight on expand

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/util/domUtils.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This addresses [AKU-678](https://issues.alfresco.com/jira/browse/AKU-678) and fixes an automated error-generation from the WAVE plugin to do with an input[type=button] not having a value. This PR also tweaks the resizing code slightly to fix a failing test discovered while running a full test suite for this change.
=> AKU-678: Button causing WAVE a11y error

aikau/src/main/resources/alfresco/navigation/PathTree.js
This PR is a further update to https://issues.alfresco.com/jira/browse/AKU-663 - it corrects the previous PR to ensure that the tree node is highlighted (not selected as that changes focus) and that the appropriate node is always selected regardless of whether it expands or not.
=> AKU-663: Update to ensure that the highlight is applied to selected tree node

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/main/resources/alfresco/services/i18n/UploadService.properties, aikau/src/main/resources/alfresco/upload/AlfUploadDisplay.js, aikau/src/test/resources/alfresco/upload/UploadTargetTest.js, aikau/src/test/resources/alfresco/upload/UploadTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/Upload.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/UploadFailure.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-668 to ensure that there is only a single button on the upload dialog. Whilst uploads are in progress this is labelled "Cancel" and once all uploads have completed (regardless of result) it is changed to say "OK" (to indicate that cancellation is no longer possible).
=> AKU-668: Vary-label single button on upload dialog

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/alfresco/services/DocumentServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DocumentService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DocumentService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DocumentService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SmartDownloadMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-677 to provide a "smart" download for multiple selection actions such that a single selected document is downloaded as the document, but multiple selected documents are downloaded as an archive.
=> AKU-677: Smart download action

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/search/FacetFilters.js, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/main/resources/alfresco/util/hashUtils.js, aikau/src/test/resources/alfresco/search/NoHashSearchingTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-680 to implement the recommended changes to support encoding of facet filters described by https://issues.alfresco.com/jira/browse/MNT-14333. One unit test needed to be updated to handle the encoding. I've also verified that the changes work fine with Share 5.0.x releases for backwards compatibility.
=> AKU-680: Faceted search filter encoding updates

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/core/_EventsMixin.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/layout/FixedHeaderFooter.js, aikau/src/main/resources/alfresco/util/domUtils.js, aikau/src/main/resources/alfresco/util/functionUtils.js, aikau/src/main/resources/alfresco/util/hashUtils.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses [AKU-671](https://issues.alfresco.com/jira/browse/AKU-671) "Dialogs not re-centered on content change" by updating and then applying the updated `ResizeMixin.addResizeListener()` functionality to [`AlfDialog`](https://github.com/Alfresco/Aikau/blob/develop/aikau/src/main/resources/alfresco/dialogs/AlfDialog.js).
=> AKU-671: Dialogs not re-centered on content change

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/renderers/CommentsList.js
This addresses [AKU-672](https://issues.alfresco.com/jira/browse/AKU-672) by customising the CSS and config for TinyMCE dialogs only. Also LESSified the Dialog CSS. Have manually, visually checked various form dialogs (on Chrome, FF and IE) after these changes and does not _seem_ to have unintentionally introduced any problems (the intentional changes will only affect the TinyMCE dialog).
[EDIT] Have now also done a semantic diff and there are definitely only intended changes in the reformatted CSS file. To make review easier, here are the newly added classes in the reformatted AlfDialog.css (after compilation and normalisation):
```css
.alfresco-dialog-AlfDialog.dijitDialog.tinymce-dialog {
min-width: 540px;
.alfresco-dialog-AlfDialog.dijitDialog.tinymce-dialog .control {
margin-right: …
```
=> AKU-672: "Add Comment" dialog: Editor not fitted into dialog

aikau/resources/grunt/coverage.js
This PR makes some updates to the code coverage merging. We have reached the point where we're generating so many individual reports that the node-coverage server can't cope. So I've made some changes such that we make multiple runs through the reports to make a set of "sub-merged" reports and then merge all those sub-merged reports into the final report.
=> Updates to make code coverage merging more reliable

aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/alfresco/services/CloudSyncServiceTest.js
This PR attempts to make the AlfTabContainerTest and CloudSyncServiceTest more reliable. These typically pass when run individually but can fail when run as part of a full regression suite.
=> Updates to make intermittently failing tests more reliable

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/GalleryViewFocusTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewFocus.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewFocus.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewFocus.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-690 to ensure that widgets in an alfresco/lists/views/layouts/Grid can be focused even when they do not have a "focus" function. A unit test has been added to support the fix.
=> AKU-690: Focus on widgets in grid without focus function

aikau/src/main/resources/alfresco/header/Title.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-685 to ensure that the browser window title is not encoded. The title on the page correctly being set without encoding, however it was the window title itself (i.e. provided by the OS) that was incorrect. In order to achieve this I've had to set document.title using unencoded data but have included XSS style values to ensure that there are no vulnerabilities that can be exploited.
=> AKU-685: Ensure that browser window title bar is set correctly

aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/GalleryViewFocusTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/GalleryViewFocus.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-689 to ensure that widgets placed within an alfresco/lists/views/layouts/Grid widget are resized appropriately when they do not have a resize function. In particular this addresses the scenario where an alfresco/layout/HorizontalWidgets widget is used within a grid to ensure that the first cell does not consume too much horizontal space before the rest of the cells on the row have been rendered.
=> AKU-689: Ensure resizing widgets resize within grid cells

aikau/src/main/resources/alfresco/core/WidgetsCreator.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfGalleryView.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/css/AlfFilteredList.css, aikau/src/main/resources/alfresco/lists/views/layouts/CellContainer.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/lists/views/layouts/css/CellContainer.css, aikau/src/main/resources/alfresco/lists/views/layouts/css/Grid.css, aikau/src/main/resources/alfresco/lists/views/layouts/templates/CellContainer.html, aikau/src/test/resources/alfresco/lists/views/ExpandableGalleryTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-675 to make it possible to expand a grid to reveal a panel for displaying additional information about the selected cell. A new alfresco/lists/views/layouts/CellContainer widget has been added for grids that do not want to use thumbnails and optional highlighting is now supported.
=> AKU-675: Expandable grid

aikau/src/test/resources/testApp/WEB-INF/dtd/urlrewrite3.0.dtd, aikau/src/test/resources/testApp/WEB-INF/urlrewrite.xml
I've been getting fed up with not being able to restart the unit test application when commuting through mobile data blackspots. This PR adds a local copy of the DTD to the test application to prevent it making requests to validate the XML.
=> Add local copy of urlrewrite DTD for test application

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/main/resources/alfresco/forms/controls/PushButtonsControl.js, aikau/src/main/resources/alfresco/forms/controls/css/PushButtonsControl.css, aikau/src/main/resources/alfresco/forms/controls/templates/PushButtonsControl.html, aikau/src/test/resources/alfresco/forms/controls/PushButtonsTest.js, aikau/src/test/resources/alfresco/forms/controls/RadioButtonsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/RadioButtons.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/RadioButtons.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/RadioButtons.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PushButtonsMockService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/RadioButtonsMockService.js
This addresses issue [AKU-682](https://issues.alfresco.com/jira/browse/AKU-682), and creates a new PushButtons control which can act as either radio-buttons (in single-value mode) or checkboxes (in multi-value mode). Tests has been almost duplicated from the RadioButtons tests, in order to try and promoted interoperability between controls. A full test suite has been run successfully. Also, updated some documentation in the MultiSelect controls.
=> AKU-682: Create Aikau Push Button Control

aikau/src/main/resources/alfresco/layout/AlfSideBarContainer.js, aikau/src/main/resources/alfresco/layout/Twister.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/layout/TwisterTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/Twister.get.js, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-670 to add a new configuration option for the alfresco/layout/Twister so that it can be configured with a width of "AUTO" to automatically grow and shrink to the available width.
=> AKU-670: Auto twister width

aikau/src/main/resources/alfresco/lists/views/layouts/css/Carousel.css, aikau/src/test/resources/alfresco/search/SearchFilmStripViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchFilmStripView.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchFilmStripView.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchFilmStripView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-697. The change ensures that height calculations are correct, a full regression suite has been run and no tests failed.
=> AKU-697: Ensure search previews are same height in film strip

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/ExpandableGalleryTest.js
This PR fixes a problem observed in the sprint review when demonstrating https://issues.alfresco.com/jira/browse/AKU-675. This ensures that the the expanded panel cell does not get resized when it is displayed. A unit test has been added to verify the fix.
=> AKU-675: Fix expanded cell resize bug

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/i18n/Form.properties, aikau/src/main/resources/alfresco/util/objectUtils.js, aikau/src/test/resources/alfresco/forms/controls/DisablingSubmitFormTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/DisablingSubmitForm.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/DisablingSubmitForm.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/DisablingSubmitForm.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/DisablingSubmitMockService.js
This addresses [AKU-683](https://issues.alfresco.com/jira/browse/AKU-683), and permits optionally disabling the OK button and updating the OK button label on a Form when it is submitted. Additionally it extracts out the algorithms behind visibilityConfig into a new objectUtils module and then reuses them to provide conditional re-enablement via topics and rules.
=> AKU-683: Optionally disable the submit button on a Form when it is submitted

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/test/resources/alfresco/lists/views/AddableViewTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-704 to ensure that only the immediate child widgets of a cell in a grid are resized. It also ensures that empty cells are added as appropriate when no data is available. Unit tests have been added for both fixes.
=> AKU-704: Ensure grid resizing only impacts immediate children

aikau/src/main/resources/alfresco/renderers/Progress.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/alfresco/services/actions/DownloadAsZipTest.js
This addresses [AKU-694](https://issues.alfresco.com/jira/browse/AKU-694) by changing the cancel-button publish from `ALF_CLOSE_DIALOG` to `ALF_PROGRESS_CANCELLED`. This automatically closes the dialog. Additionally, the cancel handler-function sets a flag to say that the task(s) have been cancelled and for the completion actions not to be run.
=> AKU-694: Download Cancel is not canceling download

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/dnd/DroppedItemWrapper.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js
This addresses [AKU-665](https://issues.alfresco.com/jira/browse/AKU-665) by creating a new alfCleanFrameworkAttributes() method in Core.js and deprecating alfDeleteFrameworkAttributes(). References to the old method have been removed and the bug has been addresses by updating ContentService as per the ticket and also including cleaning-by-default in CoreXhr.serviceXhr() method. A full test suite has been run successfully.
=> AKU-665: Aikau page makes weird call to form processor

aikau/src/main/resources/alfresco/forms/controls/Password.js, aikau/src/main/resources/alfresco/forms/controls/TextBox.js, aikau/src/main/resources/alfresco/forms/controls/TextBoxControl.js, aikau/src/test/resources/alfresco/login/LoginFormTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/login/Login.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/login/Login.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/login/Login.get.js
This addresses [AKU-698](https://issues.alfresco.com/jira/browse/AKU-698) and [AKU-701](https://issues.alfresco.com/jira/browse/AKU-701) together because the major work effort for both is completed by either one of them. Specifically, `autocomplete` can now be specified on `alfresco/forms/controls/TextBox` controls and all its descendants (e.g. Password). Also, the `placeholder` attribute is used instead of Dojo's "visual shim", wherever it's supported. Some simple tests have been added and a full regression suite run successfully.
=> AKU-698 & AKU-701: alfresco/forms/controls/Textbox attributes

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/services/DialogService.js
This addresses [AKU-696](https://issues.alfresco.com/jira/browse/AKU-696) by setting overflow:hidden on a 100% height top-container when dialogs are visible. Also removed some older attempts to fix this. No unit-tests applicable for this change, but have tested manually using the DialogService test page in Chrome, FF and IE9.
=> AKU-696: Scrolling in dialog scrolls in window

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This addresses [AKU-718](https://issues.alfresco.com/jira/browse/AKU-718), which is about long dialogs not scrolling in IE9 (in fact any dialog that has enough content to require a scrollbar). The change is a single CSS change that has been manually tested in IE9 against all dialogs on the DialogService test page. No regressions were found.
=> AKU-718: Cannot scroll long dialogs in IE9 - CSS updated

aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/test/resources/alfresco/renderers/ThumbnailAspectAndSizeTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/ThumbnailAspectAndSize.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-713 and https://issues.alfresco.com/jira/browse/AKU-714 to ensure that landscape and portrait images are rendered correctly in a non-square thumbnail. This fixes one bug and adds the unit tests to verify both that fix and that margins can be set correctly on GalleryThumbnails.
=> AKU-713, AKU-714: Fix thumbnail aspect ratio and margin

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/FullScreenCommentsList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/Preferences/Preferences.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-719 to initially make sure that the AlfSortablePaginatedList configured within the CommentsList uses an alternative preference for the number of items per page to show. However, on top of this the pagination code has generally been reviewed to ensure that preferences are handled appropriately.
=> AKU-719: CommentsList preferences

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/editors/TinyMCE.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/controls/TinyMCETest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/editors/TinyMCE.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-711 to ensure that the TinyMCE editor is given focus when displayed in a form dialog.
=> AKU-711: Ensure that TinyMCE editor is given focus on dialog form open

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentFilter.js, aikau/src/main/resources/alfresco/html/Label.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/AlfDocumentFiltersTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentFilters.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentFilters.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentFilters.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentFilters.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-721 to ensure that the alfresco/documentlibrary/AlfDocumentFilters widget does not create HTML encoded values in it's  alfresco/documentlibrary/AlfDocumentFilter children. Unit tests have been updated to ensure that XSS attacks are not possible and this PR also includes some general updates to the alfresco/html/Label attribute that is used in the unit tests to improve its JSDoc and make it more configurable.
=> AKU-721: Address double encoding issues in AlfDocumentFilters

aikau/src/main/resources/alfresco/core/css/Core.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-727 to ensure that the "X" on input fields in IE10/11 is not displayed.
=> AKU-727: Hide IE "X" on input fields

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/util/hashUtils.js, aikau/src/test/resources/alfresco/util/hashUtilsTest.js, aikau/src/test/resources/config/Suites.js
This addresses [AKU-731](https://issues.alfresco.com/jira/browse/AKU-731) by removing the double encoding/decoding present because of the explicit encodeURICompoment and the implict one inside Dojo's ioQuery module, and similarly the decode version. Share checked manually without finding any problems. Full suite run successfully.
=> AKU-731: Double encoding in hashUtils

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/header/templates/LiveSearchItem.html, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/pdf_docs_search.json
This addresses [AKU-736](https://issues.alfresco.com/jira/browse/AKU-736), which is about double-encoding of HTML, by removing this.encodeHTML and replacing with setAttribute() and appendChild(createTextNode()). Tests updated and full suite run successfully.
__~~NOTE: Please do not merge yet ... awaiting completion of regression suite~~__
__Ready to merge__
=> AKU-736: Double-encoding of HTML

aikau/src/main/resources/alfresco/core/ResizeMixin.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/main/resources/alfresco/util/functionUtils.js, aikau/src/test/resources/alfresco/util/functionUtilsTest.js
Fix bug by "scoping" the resize throttling to the node being resized, so that multiple nodes can be resized simultaneously without messages getting lost. Unit test created and full regression test completed successfully.
=> Fix bug with throttled resize publishes

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CreateContentMockXhr.js
This update for [AKU-738](https://issues.alfresco.com/jira/browse/AKU-738) fixes the scoping regression introduced while fixing [AKU-665](https://issues.alfresco.com/jira/browse/AKU-665) and updates tests accordingly. Regression suite run.
=> AKU-738: ContentService not responding in correct scope

aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js
This request fixes [AKU-723](https://issues.alfresco.com/jira/browse/AKU-723) by copying the "unescaping" of the rendered value from superclass templates. Tests updated to confirm fix and check for XSS. Full regression test completed.
=> AKU-723: Double-encoding in InlineEditPropertyLink

aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfDetailedViewItem.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfSimpleView.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfTableView.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/SelectedItemStateMixin.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/lists/AlfSortablePaginatedListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfSortablePaginatedList.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PaginationService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-734 to ensure that selected items retain selection when the sort order is changed. I went further than just this though to fix up some general issues whilst investigating sort issues.... the Document Library lib file now ensures sort menu derived from Share XML config renders correctly, the OOTB views configure the Selector widgets appropriately for both data accessed via the Share tier and from the Repository directly. I've also ensured that changing page size retains selection as well.
=> AKU-734: Item selection retention on sort

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-737. Although the issue reported problems with SearchBox ("live search")... the actual issue was with the underlying NavigationService and how it attempted to make use of site data. I've resolved the issue and added new unit tests to verify the behaviour and prevent future regressions.
=> AKU-737: NavigationService site handling

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/forms/controls/i18n/BaseFormControl.properties, aikau/src/main/resources/alfresco/forms/controls/templates/BaseFormControl.html, aikau/src/test/resources/alfresco/forms/FormValidationTest.js, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/alfresco/forms/controls/TextBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Validation.get.js
This pull-request addresses [AKU-679](https://issues.alfresco.com/jira/browse/AKU-679) by adjusting the template of the BaseFormControl to customise the alt-text for images by control. A full regression suite has been run successfully.
It may be easier to view CSS changes by looking at the second commit below individually, as the first commit makes no changes to the CSS directly, but does reformat it all to "LESSify" it.
=> AKU-679: Aikau Form elements are producing some Wave accessibility alerts

aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/css/EditTag.css, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Tags.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-715 to make it possible to configure the alfresco/renderers/Tags widget hide the "Save" and "Cancel" actions displayed in edit mode.
=> AKU-715: Tag renderer customization

aikau/src/main/resources/alfresco/editors/TinyMCE.js, aikau/src/main/resources/alfresco/forms/controls/TinyMCE.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-717 to make it possible to the TinyMCE editor to automatically grow to take up available space. In particular this is focused around the full screen commenting support for CommentsList.
=> AKU-717: Add support for TinyMCE editor to auto resize

aikau/src/main/resources/alfresco/misc/AlfTooltip.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewThumbnailSizingTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/GalleryViewThumbnailSizing.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-743 to ensure that the alfresco/misc/AlfTooltip widget will delegate any resize functions to the widgets that it wraps. This ensures that when widgets in a grid are wrapped by a tooltip that they can be resized correctly. An existing unit test has been updated to verify this fix and prevent future regressions.
=> AKU-743: Delegate resize calls to child widgets

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/buttons/css/AlfButton.css, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.js
This addresses [AKU-687](https://issues.alfresco.com/jira/browse/AKU-687) by adding a new primary-call-to-action class which mirrors the call-to-action class but with altered background/border colors. Test page updated. No automated tests required.
=> AKU-687: Add "primary-call-to-action" class for buttons

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-739 to ensure that the alfresco/navigation/PathTree will refresh nodes when content related to them is added or deleted.
=> AKU-739: Tree refresh on add or delete content

aikau/src/main/resources/alfresco/html/i18n/Label.properties, aikau/src/main/resources/alfresco/search/AlfSearchList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-749 to change the label and remove the bold tags from the search result count
=> AKU-749: Changed label for search result count to remove <b> tags

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/util/hashUtils.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This addresses [AKU-745](https://issues.alfresco.com/jira/browse/AKU-745) and [AKU-732](https://issues.alfresco.com/jira/browse/AKU-732) by changing NavigationService to modify rather than replace the current hash when a certain flag is passed. The changes also fix the escaping bug. Have also improved hashUtils slightly. Full regression suite run successfully.
=> AKU-732 & AKU-745: AlfBreadcrumbTrail updates

aikau/src/main/resources/alfresco/search/FilmStripViewSearchResult.js, aikau/src/test/resources/alfresco/search/SearchFilmStripViewTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchFilmStripView.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-744 to ensure that the heightMode and heightAdjustment can be applied to the SearchFilmStripView
=> AKU-744: Height config for SearchFilmStripView

aikau/src/main/resources/alfresco/forms/ControlRow.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/misc/TableAndFormDialog.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-740. The problem can actually be resolved through configuration of the dialog. The JSDoc has also been updated to provide helpful information when using the widget.
=> AKU-740: Set fixedWidth to resolve

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/test/resources/alfresco/lists/views/HtmlListViewTest.js, aikau/src/test/resources/alfresco/lists/views/ViewNoDataWidgetsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ViewNoDataWidgets.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ViewNoDataWidgets.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ViewNoDataWidgets.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-741 to add a new widgetsForDataFailureDisplay attribute to AlfList to render a custom widget model when data cannot be retrieved.
=> AKU-741: Added widgetsForDataFailureDisplay attribute to AlfList

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/main/resources/alfresco/layout/css/StickyPanel.css, aikau/src/main/resources/alfresco/layout/i18n/StickyPanel.properties, aikau/src/main/resources/alfresco/layout/templates/StickyPanel.html, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses [AKU-747](https://issues.alfresco.com/jira/browse/AKU-747) and creates a fixed-position StickyPanel widget. Tests have been created accordingly.
Full suite has been run and only `src/test/resources/alfresco/dnd/NestedConfigurationTest` has any failures, which seems entirely unrelated to any of this work, so should be safe to merge. Would be good to have a look at the failures though, to see if there's a quick fix?
=> AKU-747: Create non-modal fixed position dialog

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/test/resources/alfresco/forms/controls/ButtonsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/Buttons.get.js
This addresses [AKU-752](https://issues.alfresco.com/jira/browse/AKU-752) and updates the button control to pass through a title attribute. Test created. Full suite run.
=> AKU-752: Add title attribute to button - Update control and tests

aikau/src/main/resources/alfresco/core/shims.js
This addresses [AKU-765](https://issues.alfresco.com/jira/browse/AKU-765) and adds a polyfill for using textContent with IE8 to the shims file in Aikau.
=> AKU-765: Add textContent shim for IE8

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This addresses [AKU-750](https://issues.alfresco.com/jira/browse/AKU-750) and permits submission of a form when pressing enter, by adding the following config to the Form control in a model:
```javascript
publishValueSubscriptions: ["ALF_ENTER_KEY_PRESSED"],
```
A test has been created. Additionally, the properties in the AlfButton widget have been reordered.
=> AKU-750: Submit form on ENTER

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormValidationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormValidation.get.js
This addresses [AKU-751](https://issues.alfresco.com/jira/browse/AKU-751) and will focus on the first field in the form, on page load, if the following is added to the form config:
```javascript
firstFieldFocusOnLoad: true,
```
Unit-test added.
=> AKU-751: Focus on first field in form

aikau/src/main/resources/alfresco/forms/ControlRow.js, aikau/src/main/resources/alfresco/forms/css/ControlRow.css, aikau/src/test/resources/alfresco/forms/ControlRowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/ControlRow.get.js
This addresses [AKU-761](https://issues.alfresco.com/jira/browse/AKU-761) and makes showValidationErrorsImmediately setting work in ControlRow. Tests have been updated accordingly.
=> AKU-761: Get showValidationErrorsImmediately setting working in ControlRow

aikau/src/main/resources/alfresco/navigation/LinkClickMixin.js, aikau/src/main/resources/alfresco/renderers/DateLink.js, aikau/src/main/resources/alfresco/renderers/PropertyLink.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/AlfSearchResult.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-769 to add support for middle mouse clicks and left mouse clicks with the control key depressed resulting in navigation requests opening in a new browser tab. This has been applied to the AlfSearchResult widget to ensure that these types of clicks are supported in the faceted search page in Share. The unit tests have been updated.
=> AKU-769: Search result middle and control clicks

aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-766 to ensure that the selected tab in the tab container is always displayed.
=> AKU-766: Ensure selected tab is displayed

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-764 to tidy up the base form control test and ensure that pubSubScopes are set correctly. I've added a warning if a control within a form is given an explicit pubSubScope - I've resisted the urge to remove it completely.
=> AKU-764: Base form test updates

aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-770 to ensure that root tree nodes in the PathTree can be refreshed on content creation topic publications. The unit tests have been updated to verify this works - delete was already working but a test has been added to be sure and prevent regressions.
=> AKU-770: Ensure PathTree content creation reloads work for root nodes

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-771 to ensure that the edit value of InlineEditProperty and InlineEditPropertyLink widgets are not encoded. The unit tests have been updated to verify the widget behaves as expected.
=> AKU-771: Inline edit encoding of edit value

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/imports/sandpit.lib.js, aikau/src/main/resources/alfresco/layout/css/StripedContent.css
This PR provides some more minor updates to https://issues.alfresco.com/jira/browse/AKU-748. The StripedContent CSS selectors weren't quite correct for handling the title colour. I've also added a back button so that the user can easily return to the list of examples.
=> AKU-748: StripedContent CSS fix and minor tweaks to Sandpit app

aikau/src/test/resources/testApp/js/aikau/testing/mockservices/TaggingMockXhr.js
This PR fixes another issue with mock data introduced following the update to Sinon 1.17.2. The response needs to be valid JSON.
=> Fix TaggingMockXhr issue following upgrade to Sinon 1.17.2

aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FullDocLibMockXhr.js
This PR addresses an issue that has been introduced with the mocking of data for the Document Library test since the update to Sinon 1.17.2... it seems we need to include some kind of response to void a 404.
=> DocLib mock xhr correction

aikau/src/main/resources/alfresco/search/AlfSearchList.js
A customer reported that they had noticed a duplicate subscription in AlfSearchList. It is subscribing to the "reloadDataTopic" topic - but the inherited function from AlfList was already creating this subcription. I've removed it and run the unit tests to verify that this does not cause any issues.
=> Remove duplicate subscription from AlfSearchList

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-776 to ensure that the "no data" message is not displayed between initial list creation and first loading of data. The search list unit test has been updated to verify and prevent future regressions.
=> AKU-776: Ensure that no data message is not displayed during initial list load

aikau/src/main/resources/alfresco/search/SearchFilmStripView.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/SearchFilmStripView.get.js
This PR is a follow up to https://issues.alfresco.com/jira/browse/AKU-744. In the sprint review it was noticed that although the overall previewer had the height set correctly, the internal PDF.js rendering was too short so that the bottom of the scrollbar was not visible. This corrects that problem.
=> AKU-744: SearchFilmStripView preview follow-up

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js
This is a further enhancement to the fix for https://issues.alfresco.com/jira/browse/AKU-776 - after the previous commit was merged I noticed similar issues occurring in other test pages - this update further refines the previous fix.
=> AKU-776: Further improvement to no data message handling

aikau/src/main/resources/alfresco/editors/TinyMCE.js, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-775. Because of the lack of proper AMD support for TinyMCE we're forced to load the resources on demand. This means that the first time we create a TinyMCE editor we go through a slightly different code path and for some reason the timing of this results in a dimension calculation error. The simplest resolution to this problem is to add a short timeout on this initial code path that results in the TinyMCE editor being resized correctly. 
This PR also updates the related CommentsList test to make it more reliable on Chrome.
=> AKU-775: Ensure TinyMCE resize works effectively

aikau/src/main/resources/alfresco/renderers/Thumbnail.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-786 to change the behaviour of Thumbnail clicks so that the presence of a mimetype attribute in the node metadata is used to determine that a preview is possible (as opposed to a type of cm:content). This will allow types that extend cm:content to be previewed. The existing unit tests already cover that preview is shown and I've manually tested it still works.
=> AKU-786: Show preview on thumbnail click when MIME type present

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/search/FacetFilter.js, aikau/src/main/resources/alfresco/search/css/FacetFilter.css, aikau/src/main/resources/alfresco/services/SearchService.js, aikau/src/test/resources/alfresco/search/FacetFiltersTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/search/FacetFilters.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-782 to ensure that it is not possible to apply facet filters whilst a search request is in progress.
=> AKU-782: Block facet filtering when search is in progress

aikau/src/main/resources/alfresco/editors/TinyMCE.js
This PR is a second attempt at fixing https://issues.alfresco.com/jira/browse/AKU-775. It adds back the timeout removed in the code review (as this is required for Firefox) and also tweaks the height setting to make it consume more of the available space.
=> AKU-775: TinyMCE auto resize updates

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/testing/NodesMockXhr.js, aikau/src/test/resources/alfresco/upload/DndUploadTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/DndUpload.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/DndUpload.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/DndUpload.get.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/DragAndDropUploadTester.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/templates/DragAndDropUploadTester.html
This PR addresses https://issues.alfresco.com/jira/browse/AKU-784 to ensure that new view instances have all the appropriate metadata to allow drag-and-drop file upload to progress. This resolves an issue introduced by the re-implementation of list rendering. The unit tests have been updated to simulate drag-and-drop file events as it is not possible to do a real drag-and-drop from OS desktop to browser in the selenium tests
=> AKU-784: Ensure new view instance has correct data

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses [AKU-777](https://issues.alfresco.com/jira/browse/AKU-777) by changing the event-handler from click to mousedown on the item's "delete" button, to correct event-firing order and prevent the focus event firing in this context. Test added and MultiSelect tests all now passing. Full suite not run because of nature of change.
=> AKU-777: MultiSelect options expanding when choice removed

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/DragAndDropUploadTester.js
This PR fixes incorrect JSDoc @since statements left in a commit for https://issues.alfresco.com/jira/browse/AKU-784 that was originally intended for a 1.0.50.1 hotfix but moved to the 1.0.51 release.
=> Fix abandoned hotfix release numbers in JSDoc

aikau/src/main/resources/alfresco/forms/controls/MultiSelect.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/MultiSelectInput.get.js
This addresses [AKU-778](https://issues.alfresco.com/jira/browse/AKU-778) which is about MultiSelect options not filtering correctly. The fix is to put the missing properties into the fixed options on the test page, however a regression test has been added, and warnings will now be logged if properties are missing on retrieved items.
=> AKU-778: MultiSelect fixed options not filtering

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/documentlibrary/views/AlfFilmStripView.js, aikau/src/main/resources/alfresco/documentlibrary/views/css/AlfFilmStripView.css, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/AlfFilmStripViewDocument.js, aikau/src/main/resources/alfresco/documentlibrary/views/layouts/DocumentCarousel.js, aikau/src/main/resources/alfresco/lists/views/layouts/Carousel.js, aikau/src/main/resources/alfresco/preview/AVPlugin.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreview.js, aikau/src/main/resources/alfresco/preview/AlfDocumentPreviewPlugin.js, aikau/src/main/resources/alfresco/preview/Audio.js, aikau/src/main/resources/alfresco/preview/Image.js, aikau/src/main/resources/alfresco/preview/Video.js, aikau/src/main/resources/alfresco/preview/css/AlfDocumentPreview.css, aikau/src/main/resources/alfresco/preview/css/Audio.css, aikau/src/main/resources/alfresco/preview/css/Image.css, aikau/src/main/resources/alfresco/preview/css/Video.css, aikau/src/test/resources/alfresco/documentlibrary/views/MediaFilmStripViewTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/MediaFilmStripView.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/MediaFilmStripView.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/views/MediaFilmStripView.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/previews/Video.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-779 to primarily ensure that video previews do not continue to play when they are no longer displayed in the AlfFilmStripView. However, I've taken this further to do some general tidying up of the AlfFilmStripView as well as providing an auto-play feature for the previewer so that it can be configured to automatically play audio/video previews if required.
=> AKU-779: Film strip view video previews

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/test/resources/alfresco/core/ClientPropRenderFilterTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ClientPropRenderFilter.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ClientPropRenderFilter.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/ClientPropRenderFilter.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-781 to add support for client-side property render filter evaluation. Unit tests have been added to verify the behaviour. Rather than adding JSDoc into a mixin module I think I'm going to create a wiki page to document the various behaviour if the implementation passes review.
=> AKU-781: Added support for client-side property render filter evaluation

aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-787 (#773) to add the missing label element back into the InlineEditProperty template.
=> AKU-787: Add "label" element to InlineEditProperty template

aikau/src/main/resources/alfresco/menus/AlfMenuBarPopup.js, aikau/src/main/resources/alfresco/menus/css/AlfMenuBarPopup.css, aikau/src/test/resources/alfresco/documentlibrary/DocumentSelectorTest.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/alfresco/services/actions/DownloadAsZipTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-788 to ensure that the drop-down arrow added to the AlfMenuBarPopup is always visible even when the text is shortened to use an ellipsis. All unit tests have been run and some updated to make use of the new CSS classes to ensure tests work as expected.
=> AKU-788: Ensure menu arrow is visible on long labelled AlfMenuBarPopUp

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/main/resources/alfresco/services/LoggingService.js, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-789 to ensure that page refresh occurs when leaving a site via the header menu in Share. An additional change will need to be made to the Share code-base publishPayload when resolving https://issues.alfresco.com/jira/browse/MNT-14600 (a change set has been created pending release of 1.0.52).
=> AKU-789: Support page reload option when becoming site manager

aikau/src/main/resources/alfresco/navigation/LinkClickMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-769 to make a further update to the LinkClickMixin to handle the cmd key on OSX. Unit tests not updated as not possible to test in our current testing environment. A manual test would be useful by someone with a Mac at some point (hint hint).
=> AKU-769: Update LinkClickMixin to handle Mac cmd key

aikau/resources/vagrant/setup.sh, aikau/src/test/resources/intern.js
This PR makes further updates against [AKU-793](https://issues.alfresco.com/jira/browse/AKU-793) after errors were noticed when running tests against Chrome more than once. It updates the Chromedriver and Selenium versions (2.20 and 2.49.1 respectively).
=> AKU-793: Fix vagrant testing issues

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/test/resources/alfresco/services/DialogServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-799. Although there are other layout issues with the form dialog (see comments in the JIRA ticket) this PR focuses on the primary reported issue and in particular adding a test to prevent future regressions.
=> AKU-799: Form dialog layout fix

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/alfresco/services/FullScreenDialogTest.js
This PR addresses the page still scrolling in https://issues.alfresco.com/jira/browse/AKU-791. The only way to truly fix this is to remove the scrollbar completely when the dialog is visible, however to avoid the display "jumping" it's also necessary to temporarily add a right-hand margin to the body to compensate for the loss of the scrollbar. This has been tested in a local RM instance and on the Aikau test pages, and a full Aikau test suite has been run successfully.
=> AKU-791: AlfDialog - Scrolling when dialog is open shows that part of the page is hidden

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/css/AlfList.css, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-792 to improve the way that lists handle loading and rendering messages. In particularly this focuses on making sure that messages do not remain on the screen, and that rendering messages are correctly displayed when switching views (e.g. in the Document Library). I've not added any unit tests for this because the reported problem was incredibly tricky to reproduce, and the existing unit tests should cover the current behaviour.
=> AKU-792: List loading and rendering message

tutorial/chapters/Tutorial1.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-810 (#804) to make sure that tutorial 1 contains instructions to include the "alfresco/services/DialogService" on the page.
=> Include DialogService in tutorial 1 instructions

aikau/src/test/resources/alfresco/documentlibrary/views/FilmStripViewTest.js
This PR updates the unit test for the film strip view to make them run more reliably. It seems like some of the tests were failing because of how we were trying to calculate whether or not items were visible rather than using the Leadfoot API. The tests are now passing reliably.
=> Fix FilmStripView unit test failures

aikau/src/main/resources/alfresco/lists/views/ListRenderer.js
This PR fixes a failing test with scrolling to items into view. The failure was introduced when we added support for scrolling in the ClassicWindow and as a result the scrollParent JQuery function was returning the scroll parent as an item capable of scrolling, although not necessarily one that has scroll bars displayed. This update improves the search for the scroll parent to ensure the first item that can actually be scrolled is returned.
=> Fix pagination scroll test

aikau/src/test/resources/alfresco/dnd/NestedConfigurationTest.js
This PR fixes the inherited drag-and-drop configuration test by improving dialog open/close detection and using the tabToElement utility.
=> Fix the Inherited DND Configuration Tests

aikau/src/main/resources/alfresco/lists/views/ListRenderer.js
This is an update to PR #802 that addressed correctly finding scroll parents. The previous change has introduced a failure in the FixedHeaderFooterTest due to incorrect recursion handling. This update resolves that problem.
=> Further update to PR 802 to fix scroll to behaviour

aikau/resources/grunt/testing.js, aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js, aikau/src/test/resources/reporters/AikauConcurrentReporter.js, aikau/test_reports/.gitignore
This addresses [AKU-798](https://issues.alfresco.com/jira/browse/AKU-798) by updating the main test reporter to give more useful post-run output, and by setting up a new target for Bamboo to use (`grunt test_bamboo`) when performing functional testing.
=> AKU-798: Get unit tests working against BrowserStack

aikau/src/test/resources/alfresco/TestCommon.js
Remove legacy reference to virtual-box IP address. Tested with grunt test, test_local and test_bs and all work with this change. Previously all tests used the virtual-box IP address as setup when vagrant is used for testing.
=> AKU-798: BrowserStack work

aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/config/grid/Config.js, aikau/src/test/resources/config/loc/Config.js, aikau/src/test/resources/config/sl/Config.js, aikau/src/test/resources/config/vm/Config.js
Remove legacy reference to virtual-box IP address. Picked up a few problems that were missed in previous PR. Again, tested with `grunt test`, `grunt test_local` and `grunt test_bs`.
=> AKU-798: BrowserStack improvements

aikau/src/main/resources/alfresco/services/LoggingService.js
LoggingService to handle case where the pubSub logging preference is disabled dynamically.
See https://issues.alfresco.com/jira/browse/AKU-818
=> Fix for AKU-818

aikau/src/main/resources/alfresco/lists/css/AlfList.css, aikau/src/test/resources/alfresco/lists/AlfHashListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/AlfHashList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-809 to ensure that overflowing lists can be scrolled. When reviewing it's worth noting the changes made to the CSS to resolve this - it was not clear why overflow hidden was applied to list views in the first place.
=> AKU-809: Ensure that overflowing lists can be scrolled

aikau/ReleaseNotes.md, aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfFilterMixin.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-813. This ensures that form controls in a form can make use of renderFilter configuration. A unit test has been added to prevent regressions.
=> AKU-813: Eliminate duplicate processFilter function from multiple mixin modules

aikau/src/main/resources/alfresco/documentlibrary/_AlfHashMixin.js
This further addresses https://issues.alfresco.com/jira/browse/AKU-813 and updates #823 to update a call to processFilter that should have been changed to processHashFilter.
=> AKU-813: Correction to previous fix

aikau/src/main/resources/alfresco/forms/controls/FormControlValidationMixin.js, aikau/src/main/resources/alfresco/forms/controls/NumberSpinner.js, aikau/src/test/resources/alfresco/forms/controls/NumberSpinnerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-808 to ensure that min/max validation does not apply to empty NumberSpinner fields when permitEmpty is configured to be true.
=> AKU-808: Ensure min/max validation allows empty values with permitEmpty configured

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/NumberSpinner.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-807 to update the unit test page for NumberSpinner for the purposes of manually verifying the issue is fixed. There is no unit test for this update because at the moment we have no capability for locale specific testing so are reliant on manual testing. There is also no fix required because related issues committed in the current sprint have resolved the reported problem.
=> AKU-807: Updated unit test page for manual verification of locale specific issue

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/main/resources/alfresco/layout/css/StickyPanel.css, aikau/src/main/resources/alfresco/services/FileUploadService.js, aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-794 to ensure that the StickyPanel close button is disabled whilst uploads are in-progress.
=> AKU-807: Prevent sticky panel closing during upload

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/layout/css/StickyPanel.css, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/layout/StickyPanelTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.js, aikau/src/test/resources/testApp/WEB-INF/surf-config/themes/aikauTestTheme.xml
This fixes [AKU-822](https://issues.alfresco.com/jira/browse/AKU-822), which is about the uploads panel not scrolling when too many items are present. A test has also been included. No regression suite has been run, as not deemed to be necessary?
=> AKU-822: Upload panel grows without scrolling

aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/test/resources/alfresco/layout/StickyPanelTest.js
This fixes [AKU-821](https://issues.alfresco.com/jira/browse/AKU-821) by overriding the Dojo function that was automatically putting the title attribute onto the root node.
=> AKU-821: Zero percent tooltip always visible on panel

aikau/src/main/resources/alfresco/menus/AlfMenuBarPopup.js, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/test/resources/alfresco/menus/AlfMenuItemTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuItem.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuItem.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-817 to ensure that titles in menu items are not double-encoded. A unit test has been added to verify this.
=> AKU-817: Remove double encoding from menu items

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dnd/DragAndDropItems.js, aikau/src/main/resources/alfresco/dnd/css/DragAndDropItem.css, aikau/src/main/resources/alfresco/dnd/css/DragAndDropItems.css, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/list-of-items.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/list-of-items.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-827 to ensure that DND item labels are not double-encoded. The unit test has been updated to verify this and to ensure that XSS-style attacks are not possible. The CSS has also been tidied up and LESS variables added.
=> AKU-827: Prevent double-encoding on DND item label

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/layout/StickyPanelTest.js, aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.js
This PR fixes [AKU-823](https://issues.alfresco.com/jira/browse/AKU-823) by always attempting to restore a minimised StickyPanel when a request is made for one. Tests have been added (including previously missing ones) and run successfully in Vagrant and BrowserStack (FF/Chrome/IE11).
=> AKU-823: Minimised panel not restored on new uploads

aikau/src/main/resources/alfresco/renderers/Indicators.js, aikau/src/test/resources/alfresco/renderers/IndicatorsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Indicators.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-829 to improve support for alfresco/renderers/Indicators support when running on Share. It also provides a way in which icons can be mapped to custom images.
=> AKU-829: Updated Indicators to support legacyMode and custom image mapping

aikau/src/main/resources/alfresco/upload/UploadMonitor.js
This fixes [AKU-833](https://issues.alfresco.com/jira/browse/AKU-833) by removing progress percentage when the upload fails. Also, it moves actively in-progress files to the top of the window, so that even with many uploads, one can still see the currently uploading files — this change has been discussed with Kev. No unit-test added, as simply minor visual changes that will not accidentally regress.
=> AKU-833: Remove 100% upload on failure

aikau/src/main/resources/alfresco/services/_BaseUploadService.js
This hopefully fixes [AKU-825](https://issues.alfresco.com/jira/browse/AKU-825) by removing the potential for a NaN to be generated as the result of a progress calculation. Please see the JIRA ticket for more information. No unit-test has been created, however it has been manually tested without the problem recurring.
=> AKU-825: Upload percentage can show NaN

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-836. Under normal circumstances we'd have to live with a badly named property - but in this case it is not a configurable attribute so should not impact any existing modules. And you'd hope that anyone spotting this in extending code would do the right thing and raise an issue or PR like the originator of AKU-836 did!
=> AKU-836: Fixed property name typo

aikau/src/main/resources/alfresco/services/FileUploadService.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/main/resources/alfresco/services/_UploadHistoryServiceMixin.js, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/UploadMonitorV1.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/UploadMonitorV1.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/UploadMonitorV1.get.js
This pull request supersedes #831 as a fix for [AKU-830](https://issues.alfresco.com/jira/browse/AKU-830), and adds v1 API support to the upload service, including appropriate tests.
=> AKU-830: Add Alfresco v1 API support to upload services

aikau/src/main/resources/alfresco/forms/controls/css/MultiSelect.css, aikau/src/main/resources/alfresco/forms/controls/utilities/css/ChoiceMixin.css
Couple of minor tweaks to restore two instances of white-text-on-blue-background (had regressed to black text at some point).
=> Fix legibility problems with MultiSelect caused by CSS issues

aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/main/resources/alfresco/layout/css/StickyPanel.css, aikau/src/main/resources/alfresco/services/FileUploadService.js, aikau/src/test/resources/alfresco/layout/StickyPanelTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/StickyPanel.get.js
This addresses issue [AKU-843](https://issues.alfresco.com/jira/browse/AKU-843) and uses CSS to allow clicks to pass through the panel-container element on IE11+, Chrome and Firefox. JSDoc has been added to explain that it will not work in older browsers. Automated test created and passing. Full regression suite not run, only tested StickyPanelTest and UploadMonitorTest on BrowserStack (because the CSS change can't affect anything else).
=> AKU-843: Cannot click to sides of upload panel

aikau/src/main/resources/alfresco/documentlibrary/views/AlfTableView.js, aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/lists/views/layouts/HeaderCell.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-842 to ensure that when lists (in this case the AlfDocumentList) is used with useInfiniteScroll configured to be true, that sorting data clears the current results. This PR also includes improvements to the HeaderCell widget to enable it to correctly reflect the initial sort state based on the current browser URL hash (when useHash is enabled). Unit tests have been added to verify the fix.
=> AKU-842: Ensure data cleared on infinite scrolling DocumentList sort request

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/main/resources/alfresco/services/i18n/_BaseUploadService.properties, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/main/resources/alfresco/upload/i18n/UploadMonitor.properties, aikau/src/main/resources/alfresco/upload/templates/UploadMonitor.html, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UploadMockXhr.js
This addresses [AKU-796](https://issues.alfresco.com/jira/browse/AKU-796) which is about permitting contextual actions for uploads, based on their current upload-state. There is a default "cancel" action, which was used to ensure that process works, but also serves as a useful example implementation and a good feature to have. A unit test has been added for the cancellation and works on BrowserStack.
=> AKU-796: Delete uploaded files individually

aikau/src/main/resources/alfresco/forms/controls/FileSelect.js, aikau/src/main/resources/alfresco/html/FileInput.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FileSelect.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FileSelect.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FileSelect.get.js
This addresses issue [AKU-834](https://issues.alfresco.com/jira/browse/AKU-834) by taking the cross-browser approach that the (hidden) `input[type=file]` should be replaced after every change event (i.e. when the wrapped widget has its value updated) so that every file selected is a change from the default, empty state. No unit-test added (but happy to add one on suggestion of an appropriate one), but has been tested in SFS and it fixes the problem. Additionally the existing upload regression tests pass successfully in all 5 BS environments.
=> AKU-834: File upload form component does not work when re-selecting same file for upload

aikau/src/main/resources/alfresco/core/shims.js, aikau/src/main/resources/alfresco/services/LoggingService.js
This addresses [AKU-844](https://issues.alfresco.com/jira/browse/AKU-844) by adding a shim for `requestAnimationFrame` in older browsers. It also fixes an IE9 issue regarding the use of `console.log`.
=> AKU-844: IE9 requestAnimationFrame not defined

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js
This fixes [AKU-859](https://issues.alfresco.com/jira/browse/AKU-859) by adding a condition around the domNode that doesn't exist in compact mode. New tests added (as per suggestion in #870) Full regression test run.
=> AKU-859: compactMode causes console error

aikau/package.json, aikau/pom.xml, aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/intern.js, aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js, aikau/src/test/resources/intern_grid.js, aikau/src/test/resources/intern_local.js, aikau/src/test/resources/intern_sl.js, aikau/src/test/resources/test-selectors/alfresco/dialogs/AlfDialog.properties, aikau/src/test/resources/test-selectors/alfresco/forms/Form.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/MultiInputSelect.properties, pom.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-837 (and is a follow-up to #866) to provide a way in which the CSS selectors used for unit testing can be externalised (they will now be built and provided as a separate test JAR). The MultiSelectInput widget tests have been used to test this as a proof-of-concept.
=> AKU-837: Provide test selectors JAR, update MultiSelectInput to use

aikau/src/main/resources/alfresco/preview/AlfDocumentPreview.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/preview/ImagePreview.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/preview/VideoConditionUpdate.get.js
This PR makes some corrections to the previous PR for https://issues.alfresco.com/jira/browse/AKU-840 ( #861 ). There was a typo in the name of the "pluginConditionsOverrides" property (it was "pluginConditionsOverides" - note the missing "r"). Additionally, this PR makes a further update to ensure that better checking of plugin conditions occurs - previously missing mimeType or thumbnail attributes in the condition would result in the associated plugin being used.
=> AKU-840: Correction to property typo

aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/test/resources/alfresco/upload/UploadTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/Upload.get.js
This PR addresses issue [AKU-853](https://issues.alfresco.com/jira/browse/AKU-853), by permitting the customisation of the dialog buttons by overriding the `widgetsButtons` property in the `UploadService`. Regression tests have been added and full suite run.
=> AKU-853: Upload Dialog Enhancements

aikau/src/test/resources/intern_bamboo.js
Normalise the timestamp used when naming the JUnit test result file so that it has only digits in it (prevent filesystem problems).
=> Normalise the filename timestamp

aikau/src/main/resources/alfresco/services/FileUploadService.js, aikau/src/main/resources/alfresco/services/UploadService.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/Upload.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-851 to ensure that it is possible to configure the widgetsForUploadDisplay in the upload services. The UploadService unit test page has been updated to verify that configuration can be overridden.
=> AKU-851: Update "widgetsForUploadDisplay" config handling in upload services

aikau/src/test/resources/alfresco/forms/controls/MultiSelectInputTest.js, aikau/src/test/resources/test-selectors/alfresco/forms/controls/MultiSelectInput.properties
This is an update to #876 for https://issues.alfresco.com/jira/browse/AKU-837 to set the correct name for the MultiSelectInput widget properties file
=> AKU-837: Correct the name of the MultiSelectInput selectors properties file

aikau/src/main/resources/alfresco/forms/controls/FileSelect.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FileSelect.get.js
This PR updates the previous PR #865 to address https://issues.alfresco.com/jira/browse/AKU-834 as the previous update meant that the selected files were not displayed in the form control. This would be a regression in previous behaviour so we now create an opt-in configuration to enable the behaviour rather than it being the default
=> AKU-834: Update to provide opt-in configuration

aikau/src/main/resources/alfresco/html/svg/error.svg, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/main/resources/alfresco/upload/i18n/UploadMonitor.properties, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-852 to change the UploadMonitor so that error messages are replaced with an error icon.
=> AKU-852: Update UploadMonitor to show accessible error icons

aikau/src/main/resources/alfresco/notifications/css/AlfNotification.css, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses PR [AKU-865](https://issues.alfresco.com/jira/browse/AKU-865), however by using a slightly different technique than when fixing the same issue on the StickyPanel (because the notification is not stuck to the bottom of the screen), this fix should work in all browsers. Regression test added and full suite run successfully (however have updated the list of regularly-failing tests).
=> AKU-865: Unable to interact with elements in the same row as a notification while it is visible.

aikau/src/main/resources/alfresco/preview/Video.js
This is a further update to https://issues.alfresco.com/jira/browse/AKU-840 and related video playback issues. Working with the customer we've discovered that the an incorrect "type" attribute on the source element in the video element is causing the video to fail to play. Removing this attribute instructs the browser to check the type itself, see the following quote from https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video 
"If the type attribute isn't specified, the media's type is retrieved from the server and checked to see if the browser can handle it; if it can't be rendered, the next source is checked. If none of the specified source elements can be used, an error event is dispatched to the video element. If the type attribute is specified, it's …
=> AKU-840: Remove type from video source

aikau/src/test/resources/alfresco/TestCommon.js, aikau/src/test/resources/alfresco/layout/AlfTabContainerTest.js, aikau/src/test/resources/alfresco/layout/IFramedTabContainerTest.js, aikau/src/test/resources/test-selectors/alfresco/buttons/AlfButton.properties, aikau/src/test/resources/test-selectors/alfresco/layout/AlfTabContainer.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfTabContainer.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/MixedLayoutWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/TabContainerUseCase2.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-839 to externalise the CSS selectors used to test the AlfTabContainer and to use them in the Aikau tests
=> AKU-839: AlfTabContainer test selectors

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/test-selectors/alfresco/dialogs/AlfDialog.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormDialogMockService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-846 to add support for a new parameter when requesting form dialogs: 'dialogEnableTopic'. When this option is used it will result in all the buttons in the dialog being disabled when data is submitted. The topic is subscribed to in order to re-enable the buttons. Using this new feature requires the developer to ensure that the topic is published when failure occurs so that the buttons can be re-enabled to give the user the opportunity to submit valid data.
=> AKU-846: Form dialog support for "dialogEnableTopic" for button disabling

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This addresses [AKU-820](https://issues.alfresco.com/jira/browse/AKU-820) and adds visual progress bars to the uploads in the UploadMonitor widget. A regression test has been added and a full suite run.
=> AKU-820: Uploader progress bars

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/layout/StickyPanel.js, aikau/src/main/resources/alfresco/layout/i18n/StickyPanel.properties, aikau/src/main/resources/alfresco/layout/templates/StickyPanel.html, aikau/src/main/resources/alfresco/services/FileUploadService.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/main/resources/alfresco/services/i18n/FileUploadService.properties, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This addresses [AKU-832](https://issues.alfresco.com/jira/browse/AKU-832) and sets up button labels for the minimise, restore and close buttons on the StickyPanel with requested overrides for the UploadMonitor. A regression test has been added.
Mentioning @andyhealey26 so that he can review the properties file changes.
=> AKU-832: Allow a tooltip to be set for the minimize button on the Upload Monitor

aikau/src/test/resources/alfresco/forms/controls/AsyncFormControlLoadingTest.js, aikau/src/test/resources/alfresco/forms/controls/AutoSetTest.js, aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js, aikau/src/test/resources/alfresco/forms/controls/ButtonsTest.js, aikau/src/test/resources/alfresco/forms/controls/CheckBoxTest.js, aikau/src/test/resources/alfresco/forms/controls/TextBoxTest.js, aikau/src/test/resources/alfresco/forms/controls/ValidationTest.js, aikau/src/test/resources/test-selectors/alfresco/forms/Form.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/BaseFormControl.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/CheckBox.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/Select.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/TextBox.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/AsyncFormControlLoading.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/AutoSet.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/TextBox.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Validation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-838 to externalise test selectors for form controls. The base form control selectors have been added, as well as some other specific selectors. Not all the tests have been updated, but a significant chunk have been addressed to ensure the most common selectors are provided.
=> AKU-838: Form control selectors

aikau/src/main/resources/alfresco/preview/AlfDocumentPreview.js
Support empty proxy setting correctly in AlfDocumentPreview.
Also set an empty "src" value in default plugin attributes so they merge correctly when the plugin is used in a single page app with multiple thumbnail types e.g. with PDF docs and also thumbnail based urls.
All PDF test pages pass.
=> Support empty proxy setting correctly in AlfDocumentPreview

aikau/src/main/resources/alfresco/preview/AlfDocumentPreview.js
This is a further enhancement to the changes made for https://issues.alfresco.com/jira/browse/AKU-840. The issue that the customer was having was that new plugin conditions were being placed at the end of the condition array and the catch-all "imgpreview" thumbnail condition was being matched before the additional condition. This was resulting in the image previewer being used instead of the video previewer. This change ensures that all new conditions will be evaluated first.
=> AKU-840: Ensure plugin overrides are placed at beginning of the array.

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/layout/UploadContainer.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-862 to improve the DND upload highlighting behaviour. The DragEvent model is notoriously unreliable, so the existing behaviour has been augmented to emit a custom event when DND upload highlights are applied - this results in all wrapping elements to remove any highlights that might have previously been applied.
It has not bee possible to automate the testing of this fix (and indeed it wasn't possible to automate the testing of the original implementation). But manual testing has demonstrated that this works.
=> AKU-862: Improve DND upload highlighting.

aikau/src/main/resources/alfresco/services/LightboxService.js, aikau/src/main/resources/lib/3rd-party/lightbox.js
Fixed loading order of lightbox 'loading' image into init method for LightboxService.
Fixes the issue where the "loading" spinner image is never actually loaded (you can see this on the Aikau sandbox page with clickable thumbnails).
Also removes the need for a cheeky window.load event handler to be injected from the non-amd code. The old Lightbox non-amd code is horrible, and needs a rewrite but for a later time...
=> Fixed loading order of lightbox 'loading' image into init method

aikau/src/main/resources/alfresco/core/NotificationUtils.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/alfresco/services/i18n/SiteService.properties, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SiteMockXhr.js
This addresses [AKU-860](https://issues.alfresco.com/jira/browse/AKU-860) (clone of [MNT-15642](https://issues.alfresco.com/jira/browse/MNT-15642)) to add functionality to deal with site-membership requests failing because of an existing request and the ability to cancel a previously created site-membership request. Regression tests have been added and a full regression suite run. Also, the SiteService test files have had redundant elements removed.
=> AKU-860: "Request to join a moderated site multiple times"

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js
Added recursive parsing of the directory contents and file lists to retrieve a flattened list of files when a folder is dragged and handled by the onDndUploadDrop() handler, to be passed to the UPLOAD_REQUEST topic.
Each item in the flattened list will have an additional "relativePath" property which can be optionally used by an appropriate API to re-create a folder structure if desired. If the property is ignored (which it is currently by existing uploadservice) then the dragged files will simply be uploaded as a flattened list of files. This is good because it means adding this support has no downside to existing upload implementations.
If the browser does not support the FileSystem API (only Chrome 21+ does) then the code will fallback to identical behaviour as before i.e. only handles …
=> Chrome filesystem API folder listing parsing added to onDndUploadDrop() handler.

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js
This PR addresses the final requirements for SFS-210 - addition of relativePath parameter to uploadData handling. Refactor of passing the value now final v1 API is available.
=> Additional v1 upload API support - relativePath upload parameter.

aikau/src/main/resources/alfresco/forms/controls/CheckBox.js, aikau/src/test/resources/alfresco/forms/controls/CheckBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/CheckBox.get.js
This addresses [AKU-874](https://issues.alfresco.com/jira/browse/AKU-874) and adds support for custom values for a checkbox (through the `onValue` and `offValue` properties). Additionally it consolidates the handling of value-setting. Unit-tests have been added and a full regression suite run.
=> AKU-874: Checkbox string values

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/documentlibrary/views/AlfTableView.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/layouts/HeaderCell.js, aikau/src/main/resources/alfresco/lists/views/layouts/_LayoutMixin.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/test-selectors/alfresco/lists/views/layouts/HeaderCell.properties, aikau/src/test/resources/test-selectors/alfresco/lists/views/layouts/Row.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-870 to ensure that sorting of lists works when using HeaderCell widgets with useHash set to false.
=> AKU-870: Ensure list sorting without useHash or infinite scroll

aikau/src/main/resources/alfresco/menus/AlfMenuBarSelectItems.js, aikau/src/main/resources/alfresco/menus/i18n/AlfMenuBarSelectItems.properties, aikau/src/test/resources/alfresco/menus/AlfMenuBarSelectItemsTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-871 to improve the accessibility of the AlfMenuBarSelectItems widget. Some accessibility issues had been addressed by previous PRs ( #913 ) but this ensures that the alt text is more meaningful.
=> AKU-871: Accessibility updates for AlfMenuBarSelectItems

aikau/resources/grunt/linting.js
Allow JSHint task to fail if there are warnings/errors
=> Allow JSHint task to fail if there are warnings/errors

aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js, aikau/src/main/resources/alfresco/menus/css/AlfCheckableMenuItem.css, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/alfresco/menus/AlfCheckableMenuItemTest.js, aikau/src/test/resources/test-selectors/alfresco/menus/AlfCheckableMenuItem.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfCheckableMenuItem.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-872 to improve the accessibility of the AlfCheckableMenuItem widget. The CSS styling has been updated to meet our current standards and the appropriate roles and aria states are set for the menu items as they are used.
=> AKU-872: Improve AlfCheckableMenuItem accessibility

aikau/ReleaseNotes.md, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/renderers/Thumbnail.js, aikau/src/main/resources/alfresco/services/NodePreviewService.js, aikau/src/main/resources/alfresco/services/i18n/NodePreviewService.properties, aikau/src/test/resources/alfresco/renderers/ThumbnailTest.js, aikau/src/test/resources/alfresco/services/NodePreviewServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Thumbnail.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NodePreviewService.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NodePreviewService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NodePreviewService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/PreviewMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-869 to provide a new NodePreviewService that can be used to handle previewing of nodes. The existing preview capabilities from the alfresco/renderers/Thumbnail widget have been retained for backwards compatibility but deprecated with the intention to swap to using the NodePreviewService by default at some point in the future. Unit tests have been added to verify the new service and the new configuration mode for Thumbnails.
=> AKU-869: Add NodePreviewService

aikau/src/main/resources/alfresco/services/NodePreviewService.js
This PR is a minor tweak to #923 in relating to https://issues.alfresco.com/jira/browse/AKU-869 to prevent errors when processing currentItem tokens **after** setting the currentItem for custom previewing via the NodePreviewService
=> AKU-869: Update process function order to prevent errors

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/MaskingTextBoxExample.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/MaskingTextBoxExample.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/MaskingTextBoxExample.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/forms/controls/MaskingTextBoxExample.get.properties, aikau/src/main/resources/alfresco/forms/controls/MaskingTextBox.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-888 to add a new form control (alfresco/forms/controls/MaskingTextBox) that is used by the SiteService for the purpose of generating a valid site shortName from the entered title. The unit tests have been updated to verify the behaviour and a new Sandpit page has been provided.
=> AKU-888: Added MaskingTextBox, updated SiteService, tests and Sandpit

aikau/src/main/resources/alfresco/upload/AlfUploadDisplay.js, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/UploadsDisplayInterface.js, aikau/src/main/resources/alfresco/upload/_UploadsDisplayMixin.js
This pull request addresses issue [AKU-889](https://issues.alfresco.com/jira/browse/AKU-889), which originates from an issue raised against this project (#912) stating that the `alfresco/upload/_UploadsDisplayMixin` class was not behaving as an interface. Have created a new cleaner interface and deprecated old class. Upload regression tests pass successfully.
=> AKU-889: _UploadsDisplayMixin not behaving as interface

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/main/resources/alfresco/util/urlUtils.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js, aikau/src/test/resources/alfresco/forms/controls/SitePickerTest.js, aikau/src/test/resources/alfresco/upload/UploadMonitorTest.js
This addresses issue [AKU-895](https://issues.alfresco.com/jira/browse/AKU-895) by ensuring that, when loaded, `AlfBreadcrumbTrail` will read the hash and apply it. It also adds hash support for filters as opposed to just paths. Tests have been added and a full test suite run successfully. Additionally, a minor bug in `urlUtils` has been fixed.
=> AKU-895: AlfBreadcrumbTrail doesn't reflect hash on load

aikau/pom.xml, aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/extension-module/aikau-extension.xml, aikau/src/main/resources/webscripts/defaults.get.desc.xml, aikau/src/main/resources/webscripts/defaults.get.js, aikau/src/main/resources/webscripts/defaults.get.js.ftl
This PR addresses https://issues.alfresco.com/jira/browse/AKU-885 (and #908) to ensure that the Accept-Language header is set for Internet Explorer. No unit tests have been added (because we don't yet have IE testing running automatically yet), but manual testing has been carried out against BrowserStack.
=> AKU-885: Ensure correct Accept-Language header on IE

aikau/src/main/resources/alfresco/documentlibrary/_AlfDndDocumentUploadMixin.js, aikau/src/main/resources/alfresco/documentlibrary/css/_AlfDndDocumentUploadMixin.css, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-879 to improve the way in which drag and drop upload overlays are handled. The position and dimensions of the overlay are now controlled so that the overlay is constrained to within the view port.
It's not possible automate unit tests for this, however a new unit test page has been provided to manually verify all the various scroll states with both full window scrolling and nested element scrolling.
=> AKU-879: Improve DND upload overlay positioning

aikau/src/main/resources/alfresco/core/Page.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-891 to ensure that inadvertent file drops into the browser don't result in the contents of the file being rendered by the browser. This is something of a "sledgehammer" solution to the problem, but ensures the minimum number of event handlers are registered.
=> AKU-891: Prevent browser rendering dropped files

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/main/resources/alfresco/upload/AlfUploadDisplay.js, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/UploadsDisplayInterface.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/main/resources/alfresco/upload/i18n/UploadMonitor.properties
This addresses issue [AKU-890](https://issues.alfresco.com/jira/browse/AKU-890) whereby uploads appear to hang in Safari. It appears that the cause is waiting for the readystatechange to update, so it only appears to be broken. The "fix" is to send a 100% progress update to the display widget when the "load" event is fired, and in UploadMonitor to display this as "finishing" rather than "in progress", to give indication that the upload has probably succeeded. No new tests added (the timing of it would be very complex), however all existing Upload regression tests work perfectly in all browsers on BrowserStack (IE11, Chrome, FF, Safari).
=> AKU-890: Uploads do not work correctly in Safari

aikau/src/main/resources/alfresco/logging/DebugLog.js, aikau/src/main/resources/alfresco/logging/templates/DebugLog.html, aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/main/resources/alfresco/testing/MockXhr.js, aikau/src/main/resources/alfresco/testing/templates/MockXhr.html, aikau/src/test/resources/alfresco/renderers/PublishActionTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishAction.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishAction.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishAction.get.js
This addresses issue [AKU-903](https://issues.alfresco.com/jira/browse/AKU-903) by preventing the click action from bubbling up. A test page has been created for the PublishAction widget.
=> AKU-903: PublishAction click bubbling

aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/alfresco/services/DocumentServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-757 to ensure that "smart" download works when it is necessary to retrieve the full metadata for a node before downloading. The change is to swap direct URL navigation to creating a re-usable IFrame for downloading to avoid browser popup blocking.
=> AKU-757: Fix smart download for XHR metadata retrieval

aikau/src/test/resources/alfresco/services/actions/DownloadTest.js
This fixes a test that should have been corrected in the last sprint to handle the new way in which single files are downloaded.
=> Fix DownloadTest

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/test-selectors/alfresco/menus/AlfCheckableMenuItem.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-842 to ensure that infinite scrolling document lists can be sorted via menus without duplicating the list contents.
=> AKU-842: Ensure infinite scrolling DocLib can be sorted by menu

aikau/.gitignore, aikau/src/main/resources/alfresco/forms/css/Form.css, aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/InlineEditSelect.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/test-selectors/alfresco/renderers/InlineEditProperty.properties, aikau/src/test/resources/test-selectors/alfresco/renderers/InlineEditSelect.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-908 to swap the action labels in the InlineEditProperty (and descendant widgets) with the previously hidden form buttons. The unit tests have been updated and the InlineEditProperty and InlineEditSelect test selectors have been externalised.
=> AKU-908: Convert inline edit actions labels to buttons

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-912 to remove the hard-coded sort field from the links generated by the SearchBox. This change ensures that initial search (in Share) is derived from the drop-down sort selection menu. This doesn't impact other cases (e.g. where no sort menu is present) because the default is still to initial sort on "Relevance"
=> AKU-912: Remove sort field from SearchBox link

aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-904 to add support for additional form configuration to be applied to form dialogs. This PR also fixes a Firefox specific test failing.
=> AKU-904: Add support for additional form configuration in dialogs

aikau/src/main/resources/alfresco/renderers/Actions.js, aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js, aikau/src/main/resources/alfresco/renderers/_XhrActionsMixin.js, aikau/src/main/resources/alfresco/renderers/css/Actions.css, aikau/src/main/resources/alfresco/renderers/templates/Actions.html, aikau/src/test/resources/alfresco/renderers/ActionsTest.js, aikau/src/test/resources/alfresco/renderers/XhrActionsTest.js, aikau/src/test/resources/alfresco/services/actions/DownloadAsZipTest.js, aikau/src/test/resources/alfresco/services/actions/DownloadTest.js, aikau/src/test/resources/alfresco/services/actions/WorkflowTest.js, aikau/src/test/resources/test-selectors/alfresco/renderers/Actions.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-909 by re-implementing the alfresco/renderer/Actions and alfresco/renderer/XhrActions widgets to prevent the issue occurring (and by doing so simultaneously addressing https://issues.alfresco.com/jira/browse/AKU-772 and https://issues.alfresco.com/jira/browse/AKU-850). Unit tests have been updated and test selectors externalised.
=> AKU-909: Update actions renderer

aikau/src/main/resources/alfresco/renderers/XhrContextActions.js, aikau/src/main/resources/alfresco/renderers/_XhrActionsMixin.js
This PR is an additional update in relation to https://issues.alfresco.com/jira/browse/AKU-909 to make some necessary changes to the alfresco/renderers/XhrContextActions module that were required following the reworking of the alfresco/renderers/Actions widget.
=> AKU-909: Updates to XhrContextActions

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/header/AlfSitesMenu.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-923 to ensure that dialog body content is not vulnerable to XSS attack. In particular this addresses issues with site title related dialogs. This fix will be back-ported for specific hot-fix releases.
=> AKU-923: Ensure site titles are encoded

aikau/src/main/resources/alfresco/header/AlfSitesMenu.js, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/navigation/_HtmlAnchorMixin.js
This PR is a 2nd attempt at addressing https://issues.alfresco.com/jira/browse/AKU-923. The previous solution introduced vulnerabilities in other areas of Share. This solution ensures that the menu label is always encoded, but importantly ensures that the title attribute is not double encoded.
=> AKU-923: Further menu encoding updates

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/alfresco/services/DialogServiceTest.js, aikau/src/test/resources/config/Suites.js
This PR addresses [AKU-916](https://issues.alfresco.com/jira/browse/AKU-916) where opening a dialog scrolls the page. Have changed AlfDialog and updated associated tests. Also reset defaults in Suites.js
=> AKU-916: Dialog scrolls page

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/services/LightboxService.js, aikau/src/main/resources/lib/3rd-party/lightbox/0.1/lightbox.js, aikau/src/test/resources/alfresco/core/PageTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Page.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Page.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Page.get.js, aikau/src/test/resources/testApp/js/aikau/testing/services/ThrowsInitException.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-922 to ensure that the root Page module only decrements the registered services counters once when a service throws an exception on initialization. Updates have also been made to ensure that the LightBoxService will now always load the version of ligthbox.js from the same Aikau JAR. A unit tests has been added to prevent regressions in page behaviour.
=> AKU-922: Service failure handling and lightbox updates

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/lists/KeyboardNavigationSuppressionMixin.js, aikau/src/main/resources/alfresco/lists/views/ListRenderer.js, aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/ExpandableGalleryTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.js
This PR jointly addresses both https://issues.alfresco.com/jira/browse/AKU-920 and https://issues.alfresco.com/jira/browse/AKU-921 to ensure when form controls are present in the expanded area of a list or grid that they can be given focus and the cursor keys can be used as expected without controlling the item focused in the enclosing list. 
**FULL REGRESSION SUITE RUNNING - REVIEW DON'T MERGE!**
=> AKU-920, AKU-921: Expanded cell form control focus and cursor keys use

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/notifications/AlfNotification.js, aikau/src/main/resources/alfresco/notifications/css/AlfNotification.css, aikau/src/main/resources/alfresco/notifications/templates/AlfNotification.html, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/renderers/DateLinkTest.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/alfresco/renderers/PropertyLinkTest.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/test-selectors/alfresco/notifications/AlfNotification.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses [AKU-914](https://issues.alfresco.com/jira/browse/AKU-914) by adding the ability to configure widgets in notifications. A unit-test has been added and a full regression suite run successfully.
=> AKU-914: Add widgets to notifications

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.js
This is an update to the previous fix for https://issues.alfresco.com/jira/browse/AKU-920 that won't require any additional configuration, building on #981. Unit tests passing - good to merge if we're happy with the changes.
=> AKU-920: Improved fix

aikau/pom.xml, aikau/src/main/resources/extension-module/aikau-extension.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLib.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLib.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibBigData.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibNoHash.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibRawData.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/DocLibRawData.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.properties, aikau/src/test/resources/testApp/WEB-INF/surf.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-411 to make it possible to specify the version of Aikau that is in use by the application for WebScript library file imports (currently limited to a Document Library import). This can be used in both WebScript controller and properties files. The unit test pages have been updated to make use of this new capability. This will only work when used on 5.0.3 and above or on 5.1 and above (or the Surf 6.x).
=> AKU-411: Update to build to version lib files

aikau/src/main/resources/alfresco/forms/controls/utilities/ChoiceMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-777 to address an IE11 / Edge specific issue where deleting a previously selected choice results in the MultiSelectInput drop-down menu being displayed. This is a result of how dijit/focus handles pointer/touch events for those browsers. The fix here is to capture the event before dijit/focus can process it and change the target element (in fact it is necessary to stop the original event and replace it with a new one because the target attribute is read only). This results in the main widget being focused rather than the input field and means that the drop-down menu is not displayed.
=> AKU-777: IE11/Edge MultiSelectInput choice removal

aikau/src/main/resources/alfresco/html/Markdown.js, aikau/src/main/resources/alfresco/services/CommentService.js, aikau/src/main/resources/webscripts/defaults.get.js.ftl, aikau/src/main/resources/webscripts/sanitize-data.post.desc.xml, aikau/src/main/resources/webscripts/sanitize-response.get.desc.xml
This addresses #988 to ensure that errors are not displayed when refreshing WebScripts with multiple Aikau JARs in an application. This solves the problem going forwards, but will not fix occurrences where one of the JARs is 1.0.62.
=> Issue988_ResolveWebScriptClash

aikau/src/main/resources/alfresco/lists/AlfHashList.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-924 to ensure that the back button doesn't duplicate results when using an infinitely scrolling AlfDocumentList.
=> AKU-924: Infinite scroll DocLib browser support browser back

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SiteMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SiteTest/GetModeratedSite.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-930 to ensure that moderated site data is reflected correctly when editing sites.
=> AKU-930: Update SiteService to ensure moderated site data is shown correctly

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/lists/i18n/Paginator.properties, aikau/src/test/resources/alfresco/documentlibrary/PaginationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/Paginator.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-893 to provide additional configuration options for the alfresco/lists/Paginator widget:
- showPageSelector (true/false)
- currentPageLabelStyle ("NUMBER", "X_OF_Y")
- backLabel
- forwardLabel
Unit tests have been updated to verify the new options.
=> AKU-893: Paginator configuration updates

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/form-modelling.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/model-modeller.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ServiceFiltering.get.js
This fixes some of the unit test pages that were using the old approach to importing lib files.
=> Fix WebScript lib reference breakages

aikau/src/main/resources/alfresco/services/OptionsService.js, aikau/src/test/resources/alfresco/preview/ImagePreviewTest.js, aikau/src/test/resources/alfresco/services/OptionsServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/OptionsService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UserMockXhr.js
_This replaces #992 because a rebase was required._
This addresses [AKU-926](https://issues.alfresco.com/jira/browse/AKU-926) by ensuring that empty strings can be passed as the itemsAttribute value. A new test has been added, and existing optionsService tests have been tested successfully in all test-environments on BrowserStack. A full regression suite has been run successfully on Vagrant.
=> AKU-926: OptionsService issue

aikau/src/main/resources/alfresco/renderers/CommentsList.js
This addresses [AKU-927](https://issues.alfresco.com/jira/browse/AKU-927) by manually adding the correct `responseScope` to the `publishPayload` inside the `CommentsList` widget.
=> AKU-927: Comments delete scope

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/documentlibrary/_AlfCreateContentMenuItemMixin.js, aikau/src/main/resources/alfresco/services/ContentService.js, aikau/src/test/resources/alfresco/documentlibrary/CreateContentTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/CreateContent.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/CreateContentMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-928 to update the create content widgets and ContentService to improve the handling of content creation failure. Unit tests have been updated to verify the change and this has been tested manually on Share as well with scoped widgets.
=> AKU-928: Update content creation to fail gracefully

aikau/src/main/resources/lib/pdfjs/pdf.js, aikau/src/main/resources/lib/pdfjs/pdf.worker.js
to ensure YUI compressor does not cause issues with runtime code with Promise polyfill.
Tested with Share 5.2.
=> Changed to use array syntax for reserved function name 

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/main/resources/alfresco/renderers/i18n/Date.properties, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-934 to improve the output of the alfresco/renderers/Date widget when no user data is available. Unit tests have been updated.
=> AKU-934: Render Date with missing user data

aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/RemoveFavouriteSite.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-932 to ensure that menu title are localized correctly.
=> AKU-932: Ensure localized messages are retrieved for menu titles

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/notifications/AlfNotification.js, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js
This addresses [AKU-929](https://issues.alfresco.com/jira/browse/AKU-929), which is about being able to close a notification using a publication. A new test has been added.
=> AKU-929: Close notification by topic

aikau/src/main/resources/alfresco/forms/controls/SelectedListItems.js, aikau/src/test/resources/alfresco/forms/controls/SelectedListItemsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SelectedListItems.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-943 to ensure that the SelectListItems widget can have items selected even if the list is still being loaded. The unit tests have been updated to verify this as well as the ability to set via the setValueTopic configuration in a form
=> AKU-943: Support selecting items in loading SelectedListItems

aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/pickers/DocumentListPicker.js, aikau/src/test/resources/alfresco/lists/views/AlfListViewTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/AlfListView.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-933 and https://issues.alfresco.com/jira/browse/AKU-937 to ensure that it is possible to process view models on each rendering of a view. This approach is then used on the DocumentListPicker to ensure that proper cloning of the view model is done before rendering. A unit test has been added to prevent future regressions.
=> AKU-937, AKU-933: Added support for view modifiers as used in DocumentListPicker

aikau/src/main/resources/alfresco/core/PubQueue.js, aikau/src/main/resources/alfresco/dnd/DragAndDropTarget.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/forms/ControlRowTest.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/ControlRow.get.js
This is a follow up to PR #1014  to address https://issues.alfresco.com/jira/browse/AKU-938 / #999 that corrects the regression failures that were found:
> ...to ensure that ControlRow widgets behave in the same way regardless of whether or not they are placed in a dialog and whether or not the form they are in are assigned a value. This was quite a tricky problem to solve and a number of different options were explored. In the end it was determined that the best approach was always to assign the form a value (even if empty). This resulted in some other changes being necessary to form controls and existing tests that were written in a sub-optimal way. Also, it was found that it was necessary to rework the PubQueue singleton to ensure that all publications were truly made in the intended …
=> AKU-938: Control in control row in dialog with no value in form fix

aikau/src/test/resources/alfresco/CustomCommand.js, aikau/src/test/resources/intern_bamboo.js, aikau/src/test/resources/intern_bs.js
This addresses [AKU-950](https://issues.alfresco.com/jira/browse/AKU-950), where we need to change the port we use to access BrowserStack because it's being removed. Intern config updated and a couple of IE11-only errors fixed as well.
=> AKU-950: BrowserStack port change

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/main/resources/alfresco/forms/controls/PushButtonsControl.js, aikau/src/test/resources/alfresco/forms/controls/PushButtonsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js
This addresses issue [AKU-948](https://issues.alfresco.com/jira/browse/AKU-948) and adds a new `maxChoices` property to the `alfresco/forms/controls/PushButtons` widget, which should be set to `1` with `multiMode` set to true, in order to fulfil the desired use-case. A test has been added.
=> AKU-948: Possibility to deselect push button in non-multi-mode

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/renderers/_PublishPayloadMixin.js, aikau/src/main/resources/alfresco/services/_BaseUploadService.js, aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/test/resources/alfresco/services/FileUploadServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/FileUploadService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FileUploadMockService.js
This addresses issue [AKU-907](https://issues.alfresco.com/jira/browse/AKU-907) and permits removal of an item in the UploadMonitor widget. With each action, an `uploadId` will be included in the published payload, which can then be used with a publish to `alfresco/core/topics#UPLOAD_MODIFY_ITEM` to request removal of that row. Tests have been updated, and a couple of minor fixes put in.
=> AKU-907: Remove line in UploadMonitor

aikau/src/main/resources/alfresco/lists/AlfHashList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-949 to perform safe access to local storage. This is required because exceptions can be thrown by Firefox in Share when SSO is enabled with cookies disabled. Although not best practice generally to code by exception this is the suggested approach by Mozilla, see https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
=> AKU-949: Safe local storage detection.

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/test/resources/alfresco/forms/controls/ValidationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Validation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-951 to ensure that form controls will always display error messages even if they have no label. The unit tests have been updated to ensure this and an additional test has been added to ensure that error messages are shown in form dialogs (because currently the form dialogs have different layout)
=> AKU-951: Ensure that validation message is displayed when a form control has no label

aikau/src/main/resources/alfresco/lists/css/AlfList.css, aikau/src/test/resources/alfresco/forms/controls/SimplePickerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SimplePicker.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/SimplePicker.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-953 / #1012  to ensure that the SimplePicker works with a single item remaining in the list of items to pick. The solution is to ensure that the list loading message does not intercept point events as this was preventing adding the last item.
=> AKU-946: Prevent list loading message catching pointer events

aikau/src/main/resources/alfresco/forms/controls/PushButtonsControl.js, aikau/src/main/resources/alfresco/forms/controls/css/PushButtonsControl.css, aikau/src/test/resources/alfresco/forms/controls/PushButtonsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js
This addresses issue [AKU-947](https://issues.alfresco.com/jira/browse/AKU-947) and adds a title attribute to each push button and ensures that hidden text has an accompanying ellipsis. There is no specific test, however the visual layout has been confirmed in Chrome and FF.
=> AKU-947: PushButton display long text as tooltip

aikau/src/main/resources/alfresco/lists/SelectedItemStateMixin.js, aikau/src/test/resources/alfresco/renderers/SelectorTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Selector.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Selector.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Selector.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-953 to ensure that the SelectedItemStateMixin treats all values appropriately. A new unit test has been added to verify and prevent regressions.
=> AKU-953: SelectedItemStateMixin fix

aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/main/resources/alfresco/upload/css/UploadMonitor.css, aikau/src/test/resources/alfresco/CustomCommand.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/FileUploadService.get.js
This addresses issue [AKU-955](https://issues.alfresco.com/jira/browse/AKU-955) by adding a new property of `useEllipsisForLongFilenames` to `alfresco/upload/UploadMonitor`, which will ignore the `maxUploadNameLength` property and instead truncate any overly-long filenames. Also adds a helper `reload()` function to the custom Command object in Aikau.
=> AKU-955: Upload box - text misaligned when item name is to long  

aikau/pom.xml, aikau/src/main/resources/alfresco/experimental/ng2/Bootstrap.js, aikau/src/main/resources/extension-module/angular2-support-extension.xml, aikau/src/main/resources/extension-webscripts/dojo-bootstrap.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/angular2/angular2.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/angular2/angular2.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/angular2/angular2.get.js
This PR provides a prototype widget for allowing Angular 2 integration within an Aikau page model. A new support module is provided that can be deployed to request that the Angular 2 dependencies be loaded from CDN into the page. The widget can then be used to load a bootstrap Angular 2 Component and defined the initial DOM model to be parsed on bootstrapping. 
No unit tests are provided as this has been added to a new "alfresco/experimental" package with appropriate JSDoc commenting to indicate that it may be removed or changed between releases (unlike other widgets). A blog post will be published on release to demonstrate how this can be used in Share.
=> Prototype Angular 2 Bootstrap integration

aikau/src/main/resources/alfresco/editors/TinyMCE.js, aikau/src/main/resources/alfresco/forms/controls/TinyMCE.js, aikau/src/test/resources/alfresco/forms/controls/TinyMCETest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/editors/TinyMCE.get.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/CustomTinyMceEditor.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-952 to ensure that the TinyMCE form control is much more configurable. It now properly passes on configuration to the underlying editor widget and also supports the ability to swap in alternative editors. The unit tests have been updated.
=> AKU-952: TinyMCE editor updates

aikau/src/main/resources/alfresco/services/PreferenceService.js
This minor change ensures that localPreferences - if set via configuration like share-header.lib.js does - will be used as the current preferences and early-resolve the promise. This ensures that e.g. the LoggingService can retrieve the logging preferences of the user without waiting for an asynch getPreference call or a log menu publishing changes (which may not be included in the page), which means that LoggingService will correctly log messages from the beginning instead of potentially missing some initial page load log requests.
=> Eager-resolve preferences loaded when provided via config

aikau-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/config/web-application-config.xml
This PR addresses https://issues.alfresco.com/jira/browse/AKU-958 / #1033 to ensure that the AikauLoginController created by the Maven Archetype is configured with all the necessary beans to support login. This has been broken since we updated the Archetype to use Surf 6
=> AKU-958: Update Maven archetype to include bean for login controller

aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/css/CommentsList.css, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-956 to ensure that it is not possible to save empty comments. A further update has been made to ensure that the title bar is never showed for the comments dialog (a recent regression in style). Unit tests have been updated and improved to try and solve the intermittent failures that sometimes occur on Firefox.
=> AKU-956: Ensure empty comments cannot be saved

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js, aikau/src/test/resources/alfresco/documentlibrary/DocumentLibraryTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-954 to ensure that drag-and-drop upload highlighting is updated correctly based on user permissions for the location being displayed. Unit tests have been updated. 
**FULL REGRESSION TEST RUNNING - REVIEW DON'T MERGE**
=> AKU-954: Ensure drag-and-drop upload behaviour is updated appropriately

aikau/src/main/resources/alfresco/lists/AlfHashList.js
This PR is a 2nd attempt at resolving https://issues.alfresco.com/jira/browse/AKU-949 - additional try/catch blocks have been added around the other attempts to access local storage.
=> AKU-949: Additional local storage try/catch handling

aikau/src/main/resources/alfresco/renderers/EditableComment.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-957 to ensure that CommentsList refreshes when a comment is edited inline.
=> AKU-957: Ensure CommentsList refreshes on comment edit

aikau/ReleaseNotes.md, aikau/src/main/resources/alfresco/dialogs/AlfFormDialog.js
This PR addresses https://issues.alfresco.com/jira/browse/ALF-21614. It is no longer recommended to use the AlfFormDialog (and really should have been deprecated a long time ago). However, although Aikau no longer uses this module we will change as requested. No tests have been updated or added as this module will ultimately be removed.
=> ALF-21614: Update and deprecations

aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/test/resources/alfresco/renderers/PublishActionTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishAction.get.js
This PR addresses issue [AKU-966](https://issues.alfresco.com/jira/browse/AKU-966), which is about freeing up the customisation of the icon used in the `alfresco/renderers/PublishAction` widget. Tests have been updated, and a full suite run successfully.
=> AKU-966: PublishAction icon path hardcoded

aikau/src/main/resources/alfresco/services/_BaseUploadService.js
Identical parameter format to v0 API, but param in v1 is called 'renditions' instead of 'thumbnails'.
=> Added 'renditions' to Form POST for v1 upload API support

aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js
This minor change ensures that iconAltText is properly set (looking up in i18n resources) in one specific case of the _AlfMenuItemMixin postMixInProperties.
=> Add missing message call to iconAltText case

aikau/src/main/resources/alfresco/services/LoggingService.js
This minor change fixes a publication logging issue with pubSubScope / alfPublishScope being added as a redundant prefix to the already scoped alfTopic.
=> Avoid double pubSubScope-prefix in logged publications

aikau/src/main/resources/alfresco/forms/controls/TinyMCE.js, aikau/src/main/resources/alfresco/renderers/EditableComment.js, aikau/src/main/resources/alfresco/renderers/css/EditableComment.css, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-956 and https://issues.alfresco.com/jira/browse/AKU-961 (which is a duplicate) to ensure that the TinyMCE editor issues change events on key up to ensure that form buttons can be enabled/disabled on content change rather than a shift in focus. Additionally the edit as well as create comment requires data. Also, when cancelling editing a comment the original value is reset. Unit tests have been updated, unfortunately I've had to reintroduce sleep calls for reliability of testers.
=> AKU-956: Updated for handling TinyMCE change events

aikau/src/main/resources/alfresco/navigation/LinkClickMixin.js, aikau/src/test/resources/alfresco/CustomCommand.js, aikau/src/test/resources/alfresco/buttons/DropDownButtonTest.js, aikau/src/test/resources/alfresco/dnd/DndTest.js, aikau/src/test/resources/alfresco/dnd/MultiSourceTest.js, aikau/src/test/resources/alfresco/dnd/NestedConfigurationTest.js, aikau/src/test/resources/alfresco/documentlibrary/views/GalleryViewTest.js, aikau/src/test/resources/alfresco/forms/controls/CheckBoxTest.js, aikau/src/test/resources/alfresco/html/ImageTest.js, aikau/src/test/resources/alfresco/html/SVGImageTest.js, aikau/src/test/resources/alfresco/logo/LogoTest.js, aikau/src/test/resources/alfresco/menus/AlfMenuBarSelectTest.js, aikau/src/test/resources/alfresco/menus/MenuTests.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dnd/basic.get.js
Several small changes in this PR:
* Slight tidy-up of some button-clicking logic (while investigating another failing test) that seemed worthwhile including _(if you prefer, I'm happy to remove this?)_
* Fix some broken tests that were using `pressKeys(keys.TAB)` by replacing with `.tabToElement()` instead
* Update `CustomCommand.tabToElement()` to allow a `reverse` flag, and also update to use [_ES6 Destructuring Assignment_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#ES6_version) for the function parameters
* Update references to old signature of `tabToElement()` to instead use new signature
* Update references to `.deepPropertyVal()` to instead be `.propertyVal()` when deep property access isn't required
=> Fix broken tests

aikau/src/main/resources/alfresco/core/Page.js, aikau/src/main/resources/alfresco/core/PubQueue.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-965 to ensure that pagination preferences work - specifically when there are multiple Surf Components on a Page that are each rendering an Aikau "page". This example impacted is the Sites Manager page in Share but this issue could potentially impact other pages - especially Aikau dashlets. 
The fix is for each Page widget to register itself with the PubQueue singleton. Publications are only released when all the Page widgets have completed rendering.
=> AKU-956: Ensure paginator gets page size update

aikau/package.json, aikau/src/main/resources/alfresco/navigation/LinkClickMixin.js
This PR rollbacks the recent update to Intern (from 3.20 back to 3.1.1) as it was causing certain tests to fail. The LinkClickMixin has also been updated to reference the correct buttons.
=> Rollback Intern to resolve test failures

aikau/src/main/resources/alfresco/core/_PublishOrLinkMixin.js, aikau/src/test/resources/alfresco/html/ImageTest.js, aikau/src/test/resources/reporters/ConcurrentReporter.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Image.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/html/Image.get.js
This addresses [AKU-968](https://issues.alfresco.com/jira/browse/AKU-968) by allowing `clickBubbling` to be set to `false`. Tests have been added and a full regression suite run successfully.
=> AKU-968: PublishOrLinkMixin: Add support for preventing click bubbling

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/test/resources/alfresco/search/AlfSearchResultTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-975 to ensure that site folder links displayed via the AlfSearchResult have a consistent "/" prefix. The unit test has been updated.
=> AKU-975: Update AlfSearchResult to ensure forward slash prefix on folder location link

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-977 to fix a corruption in forms in dialogs layouts. This resolves a regressions introduced via #1021.
=> AKU-977: Fix forms display in dialogs

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/test/resources/alfresco/lists/views/ViewNoDataWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ViewNoDataWidgets.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-973 to swap out the use of the WidgetsCreator in the AlfListView and just use processWidgets (with a custom `processWidgetsId`). I've updated the existing test page to add a couple of widgets that should and shouldn't be rendered (via renderFilter that relies on the correct scope) and added tests to verify.
=> AKU-973: Update AlfListView to use process id instead of WidgetsCreator

aikau/src/main/resources/alfresco/forms/controls/utilities/ServiceStore.js, aikau/src/test/resources/alfresco/forms/controls/FilteringSelectTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FilteringSelect.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FilteringSelect.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FilteringSelect.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/UserMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-972 / #1057 to ensure that FilteringSelect widgets will preselect the assigned option from the available list of options based on the assigned value. The issue was a missing subscription from the ServiceStore. Unit tests have been added to prevent regressions.
=> AKU-972: FilteringSelect value

bin/setup_hooks.sh, hooks/pre-commit
This is an imperfect solution that should work on Linux and Mac, but does not work on Windows. It is also entirely optional, and will have no effect at all if the script is not run.
In order to use the hook, one should go to the root of the Aikau git working folder (not the `aikau` sub-directory), and run `bin/setup_hooks.sh`. This will then copy a __pre-commit__ hook to the `.git/hooks` directory. From then on, every single commit will have to pass a `grunt jshint` check prior to being allowed through.
This is not a negligible check, as it takes probably 5-10 seconds. If that's too much of a delay, do not use it (or remove the hook by running `rm .git/hooks/pre-commit`).
=> Add pre-commit hook

aikau/src/main/resources/alfresco/renderers/PublishAction.js, aikau/src/main/resources/alfresco/renderers/css/PublishAction.css, aikau/src/test/resources/alfresco/renderers/PublishActionTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/PublishAction.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-963 to provide onlyShowOnHover support for the PublishAction renderer. The unit tests have been updated. This replaces #1053
=> AKU-963: Support for onlyShowOnHover in PublishAction

aikau/src/main/resources/alfresco/renderers/Selector.js, aikau/src/main/resources/alfresco/renderers/css/Selector.css, aikau/src/test/resources/alfresco/renderers/SelectorTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Selector.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-959 to make it possible for a Selector to appear to be disabled. Unit tests have been added to verify the behaviour.
=> AKU-959: Selector disablement support

aikau/src/main/resources/alfresco/core/Page.js
This pull-request fixes [AKU-978](https://issues.alfresco.com/jira/browse/AKU-978), which was exhibiting as an action being unavailable. This was caused by an unhandled edge-case of no widgets being present in the component.
=> AKU-978: Classify action unavailable for documents

aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/FileUploadService.get.js
This pull-request re-addresses issue [AKU-955](https://issues.alfresco.com/jira/browse/AKU-955) and changes the default behaviour to be the _new_ auto-truncation of long names. Also, a bug with a reversed title attribute has been fixed. Upload regression tests all passing.
=> AKU-955: Upload box text misaligned when item name is too long

aikau/src/main/resources/alfresco/forms/controls/TinyMCE.js, aikau/src/main/resources/alfresco/renderers/CommentsList.js, aikau/src/main/resources/alfresco/renderers/EditableComment.js, aikau/src/test/resources/alfresco/renderers/CommentsListTest.js
This PR makes further enhancements for https://issues.alfresco.com/jira/browse/AKU-956
=> AKU-956: Support for additional TinyMCE empty content validator

aikau/src/main/resources/alfresco/node/DraggableNodeMixin.js
This addresses [AKU-979](https://issues.alfresco.com/jira/browse/AKU-979), which is a bug in a feature that was ported to Aikau but never fully implemented, specifically drag and drop within document library. To fix this, we will change the default for Thumbnails to not be draggable.
=> AKU-979: Icons stuck to mouse pointer

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentList.js
This PR addresses #1098 to set a more appropriate variable name in AlfDocumentList. The variable name used in the define callback/declare statement was not changed when the module was updated to extend AlfFilteredList instead of AlfSortablePaginatedList
=> 1098: Use appropriate module name for variable

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormWarningsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/FormWarnings.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-990 to ensure that form warnings work for both forms that have a configured pubSubScope and those that have a pubSubScope generated. The unit tests have been updated to reproduce the issue and verify that it's been fixed.
=> AKU-990: Fixed warnings for generated scope forms

aikau/src/main/resources/alfresco/services/NodePreviewService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-991 to provide a fallback option for locating a NodeRef of the Node to preview when it is not explicitly declared in the payload. I've not included a unit test change for this issue as it is a minor additive change and have verified the existing unit tests continue to work.
=> AKU-991: Added node.nodeRef fallback to NodePreviewService

aikau/src/main/resources/alfresco/forms/CollapsibleSection.js, aikau/src/test/resources/alfresco/forms/CollapsibleSectionTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/CollapsibleSection.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/CollapsibleSection.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/CollapsibleSection.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-989 to provide a new CollapsibleSection layout widget for forms. This is simply a Twister mixed with the LayoutMixin - however, the name represents the fact that we're likely to change implementation in the future and this is a more abstract name. Unit tests have been added to verify it works as expected (e.g. form data is passed back and forth through the layout control).
=> AKU-989: Added CollapsibleSection for form layout

aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/documentlibrary/AlfBreadcrumbTrailExample.get.desc.xml, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/documentlibrary/AlfBreadcrumbTrailExample.get.html.ftl, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/documentlibrary/AlfBreadcrumbTrailExample.get.js, aikau-sandpit-application/src/main/webapp/WEB-INF/classes/alfresco/site-webscripts/pages/documentlibrary/AlfBreadcrumbTrailExample.get.properties, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumb.js, aikau/src/main/resources/alfresco/documentlibrary/AlfBreadcrumbTrail.js, aikau/src/test/resources/alfresco/documentlibrary/BreadcrumbTrailTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/BreadcrumbTrail.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-992 to provide general support for publication configuration for breadcrumbs within an AlfBreadcrumbTrail. This change will allow the AlfBreadcrumbTrail to be used more effectively when showing the location of an individual Node (i.e. outside of the context of a Document Library). The unit test has been updated. A new page for the Sandpit has also been added to assist with education.
=> AKU-992: Breadcrumb trail publication updates

aikau/src/main/resources/alfresco/renderers/Indicators.js, aikau/src/test/resources/alfresco/renderers/IndicatorsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Indicators.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-981 to update the 'alfresco/renderers/Indicators' widget to automatically switch into legacyMode when the requested icon is not present in a whitelist of known icons. This should satisfy the problem of rendering Indicators configured in Share extensions (such as RM). It also doesn't impact backwards compatibility. A unit test has been added to verify the updated behaviour.
=> AKU-981: Indicators switch to legacyMode when icon not in whitelist

aikau/src/main/resources/alfresco/misc/AlfTooltip.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/misc/AlfTooltip.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-986 to provide additional orientation options for the AlfTooltip widget.
=> AKU-986: Tooltip configuration options

aikau/src/main/resources/alfresco/renderers/Indicators.js, aikau/src/test/resources/alfresco/renderers/IndicatorsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Indicators.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-982 and replaces #1113 (which was missing a unit test). It adds a configuration option to the Indicators renderer that will prevent any configured actions for the indicator being supported. A unit test has been added to verify this change.
=> AKU-982: Add support for disabling click actions in Indicators

tutorial/chapters/Tutorial11.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-994 / #1105  to remove the reference to hidePageSizeOnWidth as this configuration attribute is no longer supported
=> AKU-994: Remove hidePageSizeOnWidth reference in tutorial

aikau/src/main/resources/alfresco/layout/css/ClassicWindow.css, aikau/src/test/resources/alfresco/layout/ClassicWindowTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/ClassicWindow.get.js, tutorial/chapters/Tutorial13.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-995 / #1108 to update the ClassicWindow widget so that it supports an additionalCssClasses class called "no-margin" that removes the default margin of 10px from being added around a ClassicWindow. This style change was introduced after the tutorial was written and this creates confusion when describing how to create gaps between widgets in a horizontal layout (because it appears there is always a gap!). A new unit test has been added to verify the change and prevent regressions.
=> AKU-995: Layout tutorial and ClassicWindow updates

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1001 to ensure that the progress indicator is not shown on navigation when only the URL hash is being changed. A unit test has been added to verify the behaviour and prevent regressions.
=> Avoid showing progress indicator when setting hash parameters through NavigationService

aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-997 to add support to the alfresco/renderers/InlineEditProperty for editSubscriptionTopics that will toggle edit mode. A unit test has been added to verify this behaviour and prevent future regressions.
=> AKU-997: Edit toggling topic support for InlineEditProperty

aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This PR is a further update to https://issues.alfresco.com/jira/browse/AKU-983 to add configuration support for showing the progress indicator and the default has been updated to be false. Unit tests have been updated so verify the change.
=> AKU-983: Progress indicator off by default

aikau/src/main/resources/alfresco/notifications/css/ProgressIndicator.css, aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/main/resources/alfresco/services/actions/ManageAspectsService.js, aikau/src/test/resources/alfresco/services/actions/ManageAspectsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NotificationService.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/ManageAspects.get.js
This is a further update to AKU-983 and follows on from #1121 to ensure that the Manage Aspects action works when no NotificationService is present or when it is present but the progress indicator is disabled. This also removes the opacity and related transition to ensure that it always appears without the need for a timeout (which has been removed from the NavigationService).
=> AKU-983: Further update to remove opacity transition

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/notifications/ProgressIndicator.js, aikau/src/main/resources/alfresco/notifications/css/ProgressIndicator.css, aikau/src/main/resources/alfresco/services/NotificationService.js, aikau/src/test/resources/alfresco/services/NotificationServiceTest.js
This PR is related to [AKU-983](https://issues.alfresco.com/jira/browse/AKU-983) and tidies up the code after the removal of display transition, and restores the hide transition. The Notification and Navigation tests have been run and a failure corrected.
=> AKU-983: Update generic "processing" indicator

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/header/SetTitle.js, aikau/src/main/resources/alfresco/header/Title.js, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SetTitle.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1000 / #1112 to update the alfresco/header/SetTitle widget to support the ability to both change and hide the document prefix. The unit tests have been updated to verify this change.
=> AKU-1000: Add support to SetTitle for hiding and changing document prefix

aikau/src/main/resources/alfresco/core/Core.js, aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/test/resources/alfresco/core/AdvancedVisibilityConfigTest.js, aikau/src/test/resources/alfresco/core/VisibilityConfigTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/AdvancedVisibilityConfig.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/VisibilityConfig.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-988 / #1097 to add additional scoping capabilities to visibilityConfig and invisibilityConfig. Unit tests have been updates to verify the change (only invisibilityConfig is tested but both go through the same code path)
=> AKU-988: Update visibilityConfig to support scoping

aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/views/layouts/HeaderCell.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js, tutorial/chapters/Tutorial12.md
This PR addresses https://issues.alfresco.com/jira/browse/AKU-996 / #1107 to improve how menus can handle sorting information. The updates are to the Document Library lib file as well as the HeaderCell and AlfSortablePaginatedList. Unit tests have been updated to verify the changes and the tutorial has been modified to get better results in the sample application that is built.
=> AKU-996: Improve sorting menu widgets and update tutorial

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/test/resources/alfresco/lists/InfiniteScrollTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/InfiniteScroll.get.js, aikau/src/test/resources/testApp/js/aikau/testing/widgets/lists/BlockableSortablePaginatedList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1007 / #1131 to ensure that infinite scrolling paginated lists to not request another page of data (caused by scrolling) when a request is already in place. Unit tests have been updated (and indeed fixed!) to verify this change.
=> AKU-1007: Ensure that infinite scroll events are blocked when load in progress

aikau/src/main/resources/alfresco/lists/SortFieldSelect.js, aikau/src/main/resources/alfresco/lists/SortOrderToggle.js, aikau/src/test/resources/alfresco/lists/SortControlsTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/SortControls.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/SortControls.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/SortControls.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1009 to provide specializations of the AlfMenuBarSelect and AlfMenuBarToggle that are pre-configured to work with AlfSortablePaginatedLists (in much the same way that the Paginator is). This will make it much easier to add sorting controls to a list. Unit tests have been added to verify that they work as expected.
=> AKU-1009: Sort controls

aikau/src/main/resources/alfresco/core/CoreXhr.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/main/resources/webscript-libs/doclib/doclib.lib.js, aikau/src/test/resources/alfresco/documentlibrary/AlfDocumentListTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentList.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentList.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentList.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentList.get.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1010 to ensure that it is possible for AlfList to make an attempt to cancel an in-flight request (although this relies on the service supporting it) and for pending requests to be issued.
In particular this solves the issue of a breadcrumb trail being used when a document list is loading data. This is what the unit test has been set up to verify (using TDD I proved the unit test failed before fixing)
=> AKU-1010: Ensure that pending list requests are handled

aikau/src/main/resources/alfresco/lists/AlfList.js
This PR is an additional update on https://issues.alfresco.com/jira/browse/AKU-1010 ( #1137 ) which makes a small change so that the failure message is not displayed on a failed load when another request is pending. The unit test has not been updated because it is not possible to verify this in automated testing because the Sinon mock server does not support the ability to cancel in-flight requests.
=> AKU-1010: Don't show failure message when request is pending

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/main/resources/alfresco/header/css/SearchBox.css, aikau/src/main/resources/alfresco/header/templates/LiveSearchItem.html, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/SearchBox/site_docs_search.json
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-1011 and https://issues.alfresco.com/jira/browse/AKU-1013 to update the alfresco/header/SearchBox to fix overflow issues on long result names with no spaces and to provide a new configuration option for setting a height for the live search results. Unit tests have been updated to reflect the changes.
=> AKU-1011, AKU-1013: SearchBox fixes

aikau/src/main/resources/alfresco/renderers/PublishAction.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1018. I'm not sure why the original code was failing in Firefox (and only Firefox) but this does seem to fix the problem.
=> AKU-1018: Specific Firefox handling of click in PublishAction

aikau/src/main/resources/alfresco/services/NavigationService.js, aikau/src/test/resources/alfresco/services/NavigationServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/NavigationService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1017 to ensure that the progress notification isn't shown when using actions such as download or edit offline that use a special request parameter on the URL to trigger a download. A unit test has been added to verify the fix and prevent regressions.
=> AKU-1017: Prevent notifications being shown on download related actions

aikau/src/main/resources/alfresco/lists/ItemSelectionMixin.js, aikau/src/test/resources/alfresco/documentlibrary/InfiniteScrollDocumentListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/InfiniteScrollDocumentList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1019 to ensure that selection inversion works correctly. A unit test has been updated to verify the fix.
=> AKU-1019: Ensure selection inversion works

aikau/src/main/resources/alfresco/css/less/defaults.less
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1022 to ensure that the whole of AlfButton can be clicked - not just the inner span.
=> AKU-1022: Updated LESS defaults to make the whole of the button clickable

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/lists/views/AlfListView.js, aikau/src/main/resources/alfresco/services/CrudService.js, aikau/src/test/resources/alfresco/lists/ListItemFocusTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/ListItemFocus.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/ListItemFocus.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/ListItemFocus.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/DataMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1020 to provide support for item focus in lists (to typically address the use case of selecting an item that has just been created). A unit test has been updated to verify the change.
=> AKU-1020: Focus items on list load

aikau/src/main/resources/alfresco/forms/css/Form.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1025 to reduce the spacing between the form buttons when they are displayed inline. As this is a purely cosmetic change no tests have been updated.
=> AKU-1025: Reduce spacing of inline form buttons

aikau/src/main/resources/alfresco/css/less/defaults.less
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1024 to make the form field focus colour consistent with the button colour. This works in the same way as legacy buttons to ensure backwards compatibility of styling on Alfresco 5.0.x
=> AKU-1024: Updates to make focus colour consistent with button colour

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js
'enableContextLiveSearch' toggle added to ensure default is "off" for context switching feature
Updated test page
=> 'enableContextLiveSearch' toggle added to ensure default is "off"

aikau/src/main/resources/alfresco/css/less/defaults.less
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1026 to modify the PushButton select and hover colours following an XD review for RM
=> AKU-1026: Tweaks to PushButton selected/hover colours

aikau/src/main/resources/alfresco/lists/views/layouts/_MultiItemRendererMixin.js
This PR is a minor update for https://issues.alfresco.com/jira/browse/AKU-1020 to ensure that the _renderedItemsWidgets array is reset for each call to processedWidgets.
=> AKU-1020: Reset _renderedItemWidgets for each call to processedWidgets

aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1023 to define a minimum dialog height as directed by XD following an RM review
=> AKU-1023: XD specified min dialog height

aikau/src/main/resources/alfresco/dashlets/css/Dashlet.css, aikau/src/test/resources/alfresco/dashlets/DashletTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/dashlets/Dashlet.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1037 / #1151 to remove an unnecessary opacity style from the Dashlet CSS. The unit tests have been updated to verify this change.
=> AKU-1037: Remove unnecessary opacity styling from Dashlet.css

aikau/src/main/resources/alfresco/services/DialogService.js
This PR addresses (at least in part) #1161 to add some missing properties to the JSDoc for the DialogService form request payload.
=> 1161: Add missing DialogService event parameters to JSDoc

aikau/src/main/resources/alfresco/header/SearchBox.js, aikau/src/test/resources/alfresco/header/SearchBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/SearchBox.get.js
Changes as noted from QA testing:
- Site display label used instead of ID when building Site search toggle label
- Repository|Site context options made still visible to user if Site search produces no results - to ensure user can still select Repository for a wider search context.
Updated unit test page to test both changes.
=> SHA-1521 Ability to limit the Live search scope

aikau/src/main/resources/alfresco/renderers/css/PropertyLink.css
A PropertyLink instance won't use the defined hover color as there is a typo in the CSS. This PR corrects this typo.
=> Correct PropertLink CSS typo

aikau/src/main/resources/alfresco/forms/TabbedControls.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/TabsInForms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1043 to ensure that an alfresco/forms/TabbedControls widget will work properly within an alfresco/forms/CollapsibleSection. The unit test has been updated to verify this change.
=> AKU-1043: Update to support TabbedControls in CollapsibleSection

aikau/src/main/resources/alfresco/upload/UploadMonitor.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/upload/FileUploadService.get.js
This addresses issue [AKU-1042](https://issues.alfresco.com/jira/browse/AKU-1042) where upload filenames which are too long will display incorrectly if there are brackets in the filename. No tests have been updated, however this has been verified manually and the UploadMonitor and FileUploadService tests have been run successfully.
=> AKU-1042: Upload filename incorrect with brackets

aikau/src/main/resources/alfresco/forms/controls/FileSelect.js, aikau/src/main/resources/alfresco/html/FileInput.js, aikau/src/main/resources/alfresco/html/templates/FileInput.html, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FileSelect.get.js
New attribute in FileSelect control and FileInput widget to support "accept" attribute for <input> tag: http://www.w3schools.com/tags/att_input_accept.asp
P.S. Please don't be evil, it's my first pull request that is not about russian l10n. Also looks like my IDE updated some line breaks.
=> New attribute for FileSelect control to filter allowed file MIME-types

aikau/src/main/resources/alfresco/header/Title.js
Recreation of #1170 
This PR addresses some issues when trying to use the alfresco/header/Title module for customizing the title of the page. For one, the prefix and label for the browser title were previously not looked up before actually being used during page initialisation. This resulted in a message key being included in the browser title bar unless the "updatePageTitle" pubSub was triggered. Additionally, the HTML encoding of the prefix during postMixInProperties was redundant and caused character sequences like "Ä" to appear in the browser title bar when a German umlaut or other non-ascii/ansi characters are contained in the localized message.
=> Correct I18n/encoding handling of page title, esp. prefix

aikau/src/main/resources/alfresco/editors/TinyMCE.js
Recreation of #1168 
The languages supported by TinyMCE editor are maintained as two-letter country codes while the JS_LOCALE will typically be the combination of country and language code, i.e. de_DE. The current locale matching in the TinyMCE editor does not detect / select an available, generalized locale and essentially always falls back to English.
This PR adds locale generalization checks during in the locale match code of the TinyMCE editor.
=> Locale generalization so JS_LOCALE of de_DE results in use of de

aikau/src/main/resources/alfresco/renderers/Progress.js
Currently the Progress widget is only displaying/tracking any progress if at least one "item" (may not be used for file-based actions) has been "done". The simple truthy-check within a condition of renderUI eliminates 0 as a valid value despite it being perfectly valid for an initial progress update at the start of a long running operation.
This PR allows 0-values in renderUI by adapting the check to consider all non-negative integers as valid and explicitly checking for NaN.
=> Allow valid 0-value in renderUI of Progress widget 

aikau/src/main/resources/alfresco/renderers/_ActionsMixin.js
Recreation of #1174 
Any array of item-level actions, either explicitly define or loaded from a backend, must be respected by the alfresco/renderer/Actions module (or any of its derivatives). An empty array of item-level actions loaded from the Share data web script may be the result of a lack of permissions by the current user or simply an action set configured as empty by a developer / administrator in the Share configuration.
Currently, the ActionsMixin will fallback on the default "widgetsForActions" when
-mergeActions is set to false, and
-customActions is either not defined or an empty array, and
-currentItem.actions is either not defined or an empty array
The point of either configuring an explicit empty array for customActions or configuring Share actions in a way that may result …
=> Respect explicitly empty action arrays (i.e. lack of permissions)

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js, aikau/src/main/resources/alfresco/layout/css/AlfTabContainer.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/layout/AlfTabContainer.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1039 to re-instate the default borders around the panes of an AlfTabContainer. An optional configuration attribute has been provided for simple padding of content.
=> AKU-1039: Tab borders

aikau/src/main/resources/alfresco/renderers/_XhrActionsMixin.js, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FullDocLibMockXhr.js
When using the XhrActions module (as it is done in the faceted search page) some actions may not be listed as "available" if
- the  document / item is located within a site, and
- uses an evaluator based on "evaluator.doclib.action.groupMembership", and
- data is requested in a non-raw format
This is due to the fact that the code for handling XhrActions and retrieval of single document data is not handling the site of the document / item.
This PR addresses the issue above by adding site handling to the XhrActionsMixin and the DocumentService modules to ensure the call to the Share-tier data web script is passed the specific site of the document / item. Additionally, it allows a client module to request a specific view instead of the default "browse" (e.g. if actions are associated with a …
=> Use site for loading of actions via Xhr and allow client specifying view

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-945 to force a word break on long unbroken words used for form control labels in dialogs. I initially considered using an ellipsis and adding a title attribute, but as this is something of an edge case it makes more sense to just break the word.
=> AKU-945: Break words on form control labels in dialogs

aikau/src/main/resources/alfresco/forms/controls/Select.js, aikau/src/main/resources/alfresco/forms/controls/css/Select.css, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Select.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1040 to add a new `width` configuration option to `alfresco/forms/controls/Select`. This enables the width of the select value to be fixed regardless of the length of the option. A unit test has been added to verify this change.
=> AKU-1040: Update to support fixed widths on Select

aikau/src/main/resources/alfresco/services/PreferenceService.js, aikau/src/test/resources/alfresco/renderers/SocialRenderersTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/SocialRenderers.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SocialMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1050 to ensure that preferences are retrieved using the correct URL. The unit tests have been updated to verify the change.
=> AKU-1050: Update PreferenceService data retrieval

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/PushButtons.js, aikau/src/test/resources/alfresco/forms/controls/PushButtonsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1047 to ensure that PushButtons can't be used when they're in the disabled state. Unit tests have been updated to verify this change. This doesn't change the disabled appearance as this has been raised by a separate issue.
=> AKU-1047: Support disabled state in PushButtons

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/test/resources/alfresco/forms/LateFieldRegistrationTest.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LateFieldRegistration.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LateFieldRegistration.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LateFieldRegistration.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/TabsInForms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1049 to ensure that form fields that are late to register (in this case when added via TabbedControls that do not render immediately) that the form re-publishes all the other field values to give it the late registering field the opportunity to correctly evaluate any dynamic rules (for visibility, disablement and requirement). A unit test based on the real-world RM use case has been provided.
=> AKU-1049: Handle late form field registration

aikau/src/main/resources/alfresco/buttons/AlfDynamicPayloadButton.js, aikau/src/test/resources/alfresco/buttons/DynamicPayloadButtonTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/buttons/DynamicPayloadButton.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1052 (building on PR #1167) to support non-truthy values being set as the payload of an AlfDynamicPayloadButton. The original PR commit has been included along with unit test updates.
=> AKU-1052: Non truthy dynamic payload button values

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1044 to support additional form buttons that do not include the form value in the published payload. JSDoc has been updated to show the new option and unit tests have been added to verify the change and prevent future regressions.
=> AKU-1044: Support for additional form buttons without form values

aikau/src/main/resources/alfresco/lists/Paginator.js
When the pageBack and pageForward menu items of the Paginator are used, the payload is lacking the ```label``` attribute that the menu items in the page drop down include. This results in the ```value``` of the payload being used as the page label (briefly) until processLoadedDocuments corrects this again. This leads to an unstable layout as text grows / shrinks which users may perceive negatively. Additionally, it is technically possible for the user to trigger multiple pageBack / pageForward events before the first load request has been completed (and the pageBack/pageForward items can be disabled), which may cause the value of ```currentPage``` to exceed the valid value range / page count bounds.
This PR adds the precaclulated labels to pageBack / pageForward and a guard to avoid …
=> Paginator pageBack / pageForward is not setting page label via publication payload

aikau/src/main/resources/alfresco/lists/Paginator.js
While working on one performance aspect of #958 (overhead of paginator page selector menu update - https://github.com/AFaust/Aikau/tree/Paginator-pageSelectorRefreshPerformance) I noticed that the payload used during pageBack / pageForward in the Paginator module is missing the ```selected``` payload attribute that AlfCheckableMenuItem requires to be set to ```true``` to properly update an existing instance (see https://github.com/Alfresco/Aikau/blob/4529a6f41641378e54850285e6041696f793c75d/aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js#L235). The lack of the attribute does not affect the page selector menu right now as the menu items are currently always recreated - which is exactly the overhead an upcoming PR of mine will aim to eliminate (unless necessary).
This PR …
=> Add missing selected payload attribute for pageBack / pageForward

aikau/src/main/resources/alfresco/lists/Paginator.js, aikau/src/main/resources/alfresco/menus/AlfCheckableMenuItem.js
When (re-)loading a paginated list, there is significant overhead caused by the Paginator widget module which always destroys and re-creates all the page selection menu items. This is a side-issue found in my analysis preluding #958 that can be addressed without any refactoring around the core widget processing.
This PR adds lazy initialisation and re-use of existing menu items to the page selector menu. When the user clicks the page selector drop down in order to select another page, the hook will check which page menu items have already been created and instantiates the missing remainders. Existing page menu items are only invalidated / destroyed when either the ```documentsPerPage``` setting has changed or the page an item refers to no longer exists or its upper bound has changed (i.e. …
=> Lazy initialisation and re-use of page selector menu items (Paginator)

aikau/src/main/resources/alfresco/renderers/GalleryThumbnail.js, aikau/src/main/resources/alfresco/search/SearchGalleryThumbnail.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1067 to ensure that both the GalleryThumbnail and the Selector that it uses are consistent in their configuration of updateOnSelection.
=> AKU-1067: Ensure GalleryThumbnail gets highlight on selection

aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1068 to update the messages displayed when copy/move actions fail. The actions can actually be reported by the API as being a success (e.g. HTTP 200) despite nothing actually being copied or moved. Also, the messages now take into account multiplicity for selected items action handling, and partial failure message no longer attempt to report the individual failures due to a lack of available data on the XHR response.
=> AKU-1068: Update copy/move failure messages

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectDocumentListItems.js, aikau/src/main/resources/alfresco/lists/SelectedItemStateMixin.js, aikau/src/main/resources/alfresco/menus/AlfMenuBarSelectItems.js, aikau/src/test/resources/alfresco/documentlibrary/SelectedItemsMenuTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SelectedItemsMenu.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1063 to ensure that the SelectedItemStateMixin always publishes an empty array rather than just `null`. This ensures that the 
AlfSelectedItemsMenuBarPopup will have it's state properly initialised. The unit tests have been updated to reproduce the original failure and ensure it has been fixed.
This PR has also been updated to address https://issues.alfresco.com/jira/browse/AKU-1064 as it builds upon the same test page changes.
=> AKU-1063: Update SelectedItemStateMixin to publish empty array instead of null selected items

aikau/src/main/resources/alfresco/documentlibrary/AlfDocumentActionMenuItem.js, aikau/src/main/resources/alfresco/services/ActionService.js, aikau/src/test/resources/alfresco/documentlibrary/AlfDocumentActionMenuItemTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentActionMenuItem.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentActionMenuItem.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/AlfDocumentActionMenuItem.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1061 to update the `alfresco/documentlibrary/AlfDocumentActionMenuItem` to also filter on supported file type (or "asset" as it is called). A new unit test has been added to verify the filtering based on the specific use-case that generated the bug.
=> AKU-1061: Updates to bulk action filtering to support file types

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/FilePicker.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/main/resources/webscripts/forms-runtime-tester.get.js, aikau/src/test/resources/alfresco/forms/controls/FilePickerTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FilePicker.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1070 to provide the ability for forms to provide added and removed values instead of a single value. This is required in order to support the mapping of controls required for supporting the Share forms runtime. Unit tests have been added for the FilePicker (for which this is predominantly required).
=> AKU-1070: Support for added/removed values in form controls

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/test/resources/alfresco/forms/controls/PushButtonsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/PushButtons.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1071 to update how form controls are displayed in dialogs. In particular it ensures that the control itself cannot flow underneath the label. A unit test has been added to verify this change.
=> AKU-1071: PushButtons in dialog width

aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/main/resources/alfresco/renderers/_ItemLinkMixin.js, aikau/src/main/resources/alfresco/renderers/css/InlineEditProperty.css, aikau/src/main/resources/alfresco/renderers/i18n/InlineEditProperty.properties, aikau/src/main/resources/alfresco/renderers/templates/InlineEditProperty.html, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyLinkTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/test-selectors/alfresco/renderers/InlineEditProperty.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditPropertyLink.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FolderNodeMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FolderNodes/Folder1.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1069 to provide the ability for the InlineEditPropertyLink widget to make a request for the latest metadata for the current item. This is required because changing the name of a folder results in the location metadata changing which cannot be refreshed manually safely. The most reliable approach is to support the ability to reload the data after saving so the most recent changes are displayed on the client. This ensures that linking is correct. The unit tests have been updated to support this change.
=> AKU-1069: Folder links request updated node metadata

aikau/src/main/resources/alfresco/lists/views/layouts/Grid.js, aikau/src/test/resources/alfresco/lists/views/ExpandableGalleryTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/views/ExpandableGallery.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1054 to ensure that expanded panels remain expanded (or at least are re-expanded) following re-rendering of data following resize event of the browser window. Unit tests have been updated to verify this change.
=> AKU-1054: Ensure that expanded panels remain expanded on Grid resize

aikau/src/main/resources/alfresco/forms/LayoutMixin.js, aikau/src/test/resources/alfresco/forms/LayoutRulesTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/test-selectors/alfresco/forms/controls/BaseFormControl.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LayoutRules.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LayoutRules.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/LayoutRules.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1053 to provide support for the visibility, requirement and disablement rules on form layout widgets (like ControlRow). This means that a single rule can be applied to all the child widgets within it. Unit tests have been added to support the change.
=> AKU-1053: Support form control rule grouping

aikau/src/main/resources/alfresco/forms/controls/Picker.js
Working on my JavaScript Console Aikau-ification project I encountered a reference error in the getValue function of the Picker module. This PR adds a simple guard for the initialisation of the pickedItemsWidget, which is already checked in a similar way in setValue
=> Picker - fix for null reference error

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/forms/controls/FilePicker.js, aikau/src/main/resources/alfresco/layout/AlfTabContainer.js
The FilePicker shows redundant vertical scrollbars when the content of the currently active tab exceeds the dynamically calculated height of the dialog content panel. This is the result of incorrect calculation of heights (the content panel is larger than it should actually be based on dialog height and buffer for dialog title + toolbar) and a missing parameter when creating the FilePicker dialog to tell the AlfDialog module that the content (FixedHeaderFooter) already handles any overflow.
This PR addresses this layout issue. It:
- adds the handleOverflow parameter to the dialog payload for FilePicker (value: false)
- adds a missing resize watch on the AlfTabContainer (which might be resized either due external constraints, changes in tab contents or addition / removal / activation of …
=> Fix redundant vertical scrollbars in FilePicker (and likely other dialogs with handleOverflow=false)

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/test/resources/alfresco/forms/controls/ValidationTest.js, aikau/src/test/resources/test-selectors/alfresco/dialogs/AlfDialog.properties, aikau/src/test/resources/test-selectors/alfresco/forms/controls/BaseFormControl.properties, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Validation.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1072 to provide configuration options for hiding the validation indicators and messages for form controls. The use case here is when no label attribute is required (the exact use case being where a SimplePicker is the sole form control in a form dialog) and we want to avoid the requirement asterisk, invalid field indicator being displayed, etc. This is an opt-in feature meaning that all existing implementations should not be impacted. Unit tests have been provided to verify this change.
=> AKU-1072: Support options for hiding validation in form controls

aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/main/resources/alfresco/header/SearchBox.js
Added support for "paste" event into SearchBox component and the TextBoxValueChangeMixin.
Tested in IE10/11, Chrome and FireFox via the following unit test pages by manual "right click + paste" operation in text fields:
SearchBox
TextBox
Doesn't appear to be a way to add a specific automated test for this operation (CTRL+paste in automated test does not help, as there is already a keypress event to handle this).
=> AKU-1079 - CLONE - Search button disabled when pasting a search term using Mouse right click + Paste in Share Search

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/main/resources/alfresco/lists/utilities/FilterSummary.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1077 to provide support for mapping filter values to labels. The unit tests have been updated to verify this works.
=> AKU-1077: Add support for filter summary label mapping

aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1076 to ensure that it is not necessary to explicitly configure the filteringTopics array for an AlfFilteredList. It was not necessary to add an existing unit test - the existing tests failed when the filteringTopics configuration is removed from the current test page - updating the code resolved those failures.
=> AKU-1076: Ensure filteringTopics do not need to be configured for AlfFilteredList

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/test/resources/alfresco/services/FormsRuntimeServiceTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FormsRuntimeService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormsRuntimeMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FormsRuntime/Authorities.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FormsRuntime/CreateWorkflow.json, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FormsRuntime/CreateWorkflowSuccess.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1081 to add the ability to include additional data into the submission of forms generated from the FormsRuntimeService. This use case solves the ability to set custom scopes in the form submission. Unit tests have been added for this specific requirement.
=> AKU-1081: Add support for payload mixins into forms runtime

aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/main/resources/alfresco/lists/AlfFilteredList.js, aikau/src/test/resources/alfresco/forms/controls/DateTextBoxTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateTextBox.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1082 to ensure that the valueChange publication for a DateTextBox contains the correct formatted value. The unit test has been updated to ensure the behaviour is correct.
=> AKU-1082: Ensure correct DateTextBox value is published on change

aikau/src/main/resources/alfresco/forms/controls/Select.js, aikau/src/test/resources/alfresco/forms/controls/SelectTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1083 to ensure that the Select form control supports options with the empty string as a value. The unit tests have been updated to reflect the change.
=> AKU-1083: Update Select to support empty string value option

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/FilePicker.js
Currently the FilePicker always exposes an array of (removed/added) values, even though the picker may be configured to only allow a single selection. For single-valued fields it is common (and expected) that the value is provided as a simple value and not wrapped inside a "dummy" array of a single element. This PR adds special handling for the case that multipleItemSelection is configured to false, yielding only the value of the itemKey without a wrapping array as the (added/removed) value of the field.
This PR also moves code that was specific to FilePicker from the BaseFormControl module (where it didn't belong) to the FilePicker itself.
Additionally it addresses a minor bug found during testing that could result in forms not being initialized correctly: calls to publishValue providing …
=> Expose simple value for FilePicker in "single selection" mode

aikau/pom.xml, aikau/src/main/resources/alfresco/menus/_AlfMenuItemMixin.js, aikau/src/main/resources/alfresco/patches/touch.js, aikau/src/main/resources/extension-module/aikau-extension.xml, aikau/src/main/resources/patches/dojo-bootstrap.get.html.ftl, aikau/src/test/resources/alfresco/header/HeaderWidgetsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/header/HeaderWidgets.get.js
This PR addresses both https://issues.alfresco.com/jira/browse/AKU-1085 and https://issues.alfresco.com/jira/browse/AKU-1086 to address issues with IE11 and Edge to ensure that middle wheel and control left clicks open only a new tab (not a new tab plus changing the current tab) and that right clicks aren't treated left clicks.
=> AKU-1085: Mouse click consistency

aikau/src/main/resources/alfresco/pickers/ContainerPicker.js, aikau/src/main/resources/alfresco/pickers/Picker.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1084 to ensure that the "Recent Sites" item in the ContainerPicker is displayed when the Copy/Move action dialog is displayed. The unit test has been updated to verify this change.
=> AKU-1084: Ensure that "Recent Sites" is pre-selected in Copy/Move pickers

aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/actions/CopyMove.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1075 to ensure that the copy/move action dialog title is correct for bulk actions when only one item is selected and that item has a missing file name. The unit tests have been update to verify the change.
=> AKU-1075: Ensure copy/move dialog title is always correct

aikau/src/main/resources/alfresco/renderers/User.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/main/resources/webscript-libs/tasks/tasks.lib.js, aikau/src/test/resources/alfresco/renderers/UserTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Actions.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/User.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/User.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/User.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1036 to provide the alfresco/renderers/User widget that is then mapped against the taskowner.ftl component in the FormsRuntimeService. Unit tests have been added.
=> AKU-1036: Added Users renderer to map to taskowner.ftl

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/Transitions.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FormsRuntimeService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormsRuntimeMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FormsRuntime/EditTask.json
This is another update to the Forms Runtime mapping support. This provides a new control for mapping transitions when editing tasks.
=> AKU-1014: Added mapping for transitions

aikau/src/main/resources/alfresco/core/CoreWidgetProcessing.js, aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/forms/controls/Password.js, aikau/src/main/resources/alfresco/forms/controls/i18n/Password.properties, aikau/src/main/resources/alfresco/lists/AlfList.js, aikau/src/main/resources/alfresco/renderers/Toggle.js, aikau/src/main/resources/alfresco/services/BaseService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/main/resources/webscript-libs/pages/people.lib.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Password.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Password.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Password.get.js
This PR provides more updates to the people.lib.js file. It is now possible to get sites that the user is a member of and for the current user the activity feed state will be merged into the results. The ability to enable and disable activity feeds for a site is now supported. A new comparator for renderFilter is provided to allow a simple check against the current user id. Finally the ability to change the password is added to the page model generated and enhancements to the Password widget have been made to support this - namely the ability to confirm a match against another password field.
=> People Lib Updates

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/test/resources/alfresco/forms/FormsTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/Forms.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1088 to ensure that the setValueTopic value can be subscribed to on the local pubSubScope of the Form. A new unit test has been added to verify this using form reset as a use case.
=> AKU-1088: Ensure Form setValueTopic is scoped correctly

aikau/src/main/resources/alfresco/renderers/Date.js, aikau/src/test/resources/alfresco/renderers/DateTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Date.get.js
This PR makes an update to the Date renderer to provide support for custom formats as provided via TemporalUtils. A unit test has been added to verify this works.
=> Support for custom format in Date renderer

aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1090 to change the way that error messages are reported. The original implementation was based on the mistaken assumption that a partial success actually partially succeeded. Whereas actually although the REST API response reports that some actions have been successful, none have been applied. The unit tests have been updated.
=> AKU-1090: Update copy/move error messages

aikau/src/main/resources/alfresco/search/css/AlfSearchResult.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1091 to make a minor style update to the AlfSearchResult widget to ensure that browser focus highlighting on some browsers (Chrome, Firefox, Safari on Windows - oddly not IE and Edge) is not cropped.
=> AKU-1091: Minor search result style update

aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js
This PR makes another update to the Copy / Move failure message to make it more generic. The associated unit test has been updated.
=> AKU-1094: Updates to copy/move error message

aikau/src/main/resources/alfresco/services/SiteService.js
This is an update to https://issues.alfresco.com/jira/browse/AKU-1092 to correct the localization string used for the "private" site option
=> AKU-1092: Updated SiteService use the right description for "private"

aikau/src/main/resources/alfresco/menus/AlfMenuBarToggle.js, aikau/src/test/resources/alfresco/menus/AlfMenuBarToggleTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/menus/AlfMenuBarToggle.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1096 which resolves a problem with the AlfMenuBarToggle to ensure that URL hashing works properly.  The unit tests have been updated both to use current best practices and add new tests for the fix.
=> AKU-1096: Fix hashing on AlfMenuBarToggle

aikau/src/main/resources/alfresco/forms/controls/DateRange.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js, aikau/src/main/resources/alfresco/forms/controls/css/DateRange.css, aikau/src/main/resources/alfresco/forms/controls/i18n/DateRange.properties, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/test/resources/alfresco/forms/controls/DateRangeTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateRange.get.desc.xml, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateRange.get.html.ftl, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/DateRange.get.js
This PR is relates to https://issues.alfresco.com/jira/browse/AKU-1014 to provide a mapping for the daterange.ftl FormsRuntime renderer to a new Aikau DateRange widget. Unit tests have been added to verify the date range behaviour.
=> AKU-1014: Added DateRange widget mapping

aikau/src/main/resources/alfresco/services/actions/CopyMoveService.js, aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties
This PR is a further update to the previous changes made for https://issues.alfresco.com/jira/browse/AKU-1094. It makes more updates to how copy/move error messages are displayed
=> AKU-1094: Further updates to the copy/move error messages

aikau/src/main/resources/alfresco/lists/AlfList.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1098 to ensure that the failure message is hidden on lists when a new loading message is displayed.
=> AKU-1098: Ensure failure message is hidden when loading

aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/DateRange.js, aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/main/resources/alfresco/services/FormsRuntimeService.js, aikau/src/main/resources/alfresco/services/i18n/FormsRuntimeService.properties, aikau/src/main/resources/webscripts/forms-runtime-tester.get.js, aikau/src/test/resources/alfresco/forms/controls/AutoSetTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/AutoSet.get.js
This PR relates to https://issues.alfresco.com/jira/browse/AKU-1014 and makes additional updates to the FormsRuntimeService to ensure that it is possible to reconfigure the form submission button label and publish topic. It also sorts MIME types and switches to the FilteringSelect to make it easier to find a MIME type.
=> AKU-1014: Further updates to FormsRuntimeService

aikau/src/main/resources/alfresco/forms/controls/FormControlValidationMixin.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/forms/controls/ValidationTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/Validation.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormControlValidationTestService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1099 to re-introduce backwards compatibility on "validationTopic" form validation. For the Site create/edit updates we had previously introduced scoped validation responses (to prevent cross-pollution of validation data) without realising that RM was dependent upon the previous implementation. This PR re-introduces backwards compatibility but provides an "opt-in" configuration of "scopeValidation" that allows validation to be scoped (which would be recommended). Unit tests have been updated.
=> AKU-1099: Re-introduce backwards compatibility for validationTopic

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/renderers/css/Property.css
This is a further update to https://issues.alfresco.com/jira/browse/AKU-1097 to ensure that the mark element background colour is fully themeable. The default colour has also been toned down a little
=> AKU-1097: Made mark element colour for highlighting themeable

aikau/src/main/resources/alfresco/css/less/defaults.less
This PR is a minor update to https://issues.alfresco.com/jira/browse/AKU-1097 to change the default highlight colour after an update from the XD team
=> AKU-1097: Update mark element colour

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1106 to ensure that when editing the details of a site that the user is redirected to the appropriate location (namely the home page for that site). Effectively it no longer defaults to "dashboard". Unit tests have been updated.
=> AKU-1106: Update SiteService so that navigation on edit is correct

aikau/src/main/resources/alfresco/services/actions/i18n/CopyMoveService.properties, aikau/src/test/resources/alfresco/services/actions/CopyMoveTest.js
This is minor change to the label on the "Create ink" button in copy/move dialogs (was formally "Create a link")
=> Create Link label update

aikau/src/main/resources/alfresco/renderers/MoreInfo.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1105 to remove the unicode characters used to delineate the position of highlighted content in search term highlighting results as displayed in the title of a MoreInfo widget.
=> AKU-1105: Remove unicode characters from tooltip of MoreInfo

aikau/src/main/resources/alfresco/core/topics.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1108 to ensure that sites are favourited by default when created (through the SiteService). The unit tests have been updated to verify this change. I've also made a minor change related to https://issues.alfresco.com/jira/browse/AKU-1106 to make use of the "userHomePage" configuration attribute to ensure the SiteService can be used for creating sites on versions of Alfresco Share prior to 5.2
=> AKU-1108: Ensure site is favourited by default when created

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1107 to ensure that site names and titles are trimmed prior to validation and submission. A new "trimValue" has been added to BaseFormControl to support trimming of values when requested to achieve this. The unit tests have been updated.
=> AKU-1107: Ensure that site names and titles get trimmed

aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/search/SearchThumbnail.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1114 to remove the search term highlighting prefix and postfix characters from thumbnail titles.
=> AKU-1114: Remove search highlighting delineation from thumbnail

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1115 to resolve an introduce that was previously introduced to ensure that site home and user home are independently configured. The unit tests have been updated and this has been verified on Share.
=> AKU-1115: Site service fixes

aikau/src/main/resources/alfresco/buttons/AlfButton.js, aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/forms/Form.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1116 to add support for form dialogs being submitted on enter key presses. In particular this adds support for create and edit site form dialogs to be submitted on enter (if the form is in a valid state). The unit tests have been updated.
=> AKU-1116: Confirm dialog on enter

aikau/src/main/resources/alfresco/services/SiteService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1108 to ensure that requests to favourite sites are completed before navigating to the newly created site.
=> AKU-1108: Ensure favouriting completes on site creation before navigation

aikau/src/main/resources/alfresco/services/i18n/SiteService.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1117 to add in missing error message for failure to create sites.
=> AKU-1117: Added additional message for site creation failure

aikau/src/main/resources/alfresco/header/SearchBox.js
Prevent event from changing # url parameters. Fixes issue SHA-1896.
=> AKU-1120 - CLONE - User is redirected to site Document Library when clicking on any of the Live Search scope options

aikau/src/main/resources/alfresco/buttons/css/AlfButton.css, aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1121 to ensure that the asynchronous validation checking of a form does not cause the button confirmation button to flash (as it goes to disabled state as soon as validation commences and if the response is fast the button appears to flash). This has been resolved by ignoring non-change key strokes and setting a transition delay on the button.
=> AKU-1121: Prevent button enablement from "flashing"

aikau/src/main/resources/alfresco/navigation/PathTree.js, aikau/src/test/resources/alfresco/navigation/PathTreeTest.js, aikau/src/test/resources/config/Suites.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/navigation/PathTree.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1118 to update the PathTree to be more tolerant of missing "/" prefixes when handling path change publications. The unit test has been updated to verify the change.
=> AKU-1118: Update PathTree to be more tolerant of missing "/" prefix

aikau/src/main/resources/alfresco/forms/controls/css/BaseFormControl.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1123 to provide some additional padding before the first form control in dialog forms. This has been added to ensure that OSX highlights are not clipped.
=> AKU-1123: Add "breathing room" for OSX highlighting in dialog forms

aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1119 to improve the configuration options for site presets in the create site dialog. It is now possible to replace the default options, add to the default options or remove from default and added options. Unit tests have been added to verify all the various configuration options.
=> AKU-1119: Improve SiteService preset configuration options

aikau/src/main/resources/alfresco/documentlibrary/AlfSelectDocumentListItems.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1125 to ensure that the AlfSelectDocumentListItems menu is disabled when there are no options to select from (additional check against -1 results as well as 0 results).
=> AKU-1125: Ensure AlfSelectDocumentListItems is disabled on -1 reported results

aikau/src/main/resources/alfresco/search/AlfSearchList.js, aikau/src/test/resources/alfresco/documentlibrary/SearchListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/documentlibrary/SearchList.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1111 / #1240 to support the inclusion of additional query parameters in search requests via simple configuration on the AlfSearchList widget. A new unit test has been added to verify the update.
=> AKU-1125: Add support for including additional search query parameters in AlfSearchList

aikau/src/main/resources/alfresco/forms/controls/FilePicker.js, aikau/src/test/resources/alfresco/forms/controls/FilePickerTest.js, aikau/src/test/resources/alfresco/services/FormsRuntimeServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/FormsRuntimeService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/FormsRuntimeMockXhr.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/responseTemplates/FormsRuntime/EditDataListItem.json
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1112 / #1270 to ensure that FilePicker widgets that are configured to be required do not disable a form when a value is provided. The unit tests have been updated to verify this change.
=> AKU-1112: FilePicker requirement validation fix

aikau/src/main/resources/alfresco/forms/controls/BaseFormControl.js, aikau/src/main/resources/alfresco/forms/controls/ComboBox.js, aikau/src/main/resources/alfresco/forms/controls/FilteringSelect.js, aikau/src/main/resources/alfresco/forms/controls/MultiSelectInput.js, aikau/src/main/resources/alfresco/forms/controls/utilities/UseServiceStoreMixin.js, aikau/src/test/resources/alfresco/forms/controls/ContainerPickerTest.js, aikau/src/test/resources/alfresco/forms/controls/SelectedListItemsTest.js, aikau/src/test/resources/alfresco/forms/controls/SitePickerTest.js, aikau/src/test/resources/alfresco/lists/FilteredListTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/ContainerPicker.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1128 (and part of #1295) to ensure that only a single XHR request for options is made for FilteringSelect (and other form controls that use the ServiceStore module). A unit test has been added to verify the improvement (along with some tweaks to other tests to improve reliability)
=> AKU-1128: Only request options for form controls once

aikau/src/main/resources/alfresco/forms/controls/ComboBox.js, aikau/src/main/resources/alfresco/forms/controls/FilteringSelect.js, aikau/src/test/resources/alfresco/forms/controls/FilteringSelectTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/FilteringSelect.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1129 and #1295 to provide a new configuration option that makes it possible for FilteringSelect and ComboBox widgets to support the ability to show all available options when their drop-down menus are revealed by clicking on the open icon (rather than through typing). The default behaviour is retained for backwards compatibility, but the `showAllOptionsOnOpen` can be configured to be true to support showing all options.
=> AKU-1129: Added config for showing all options in FilteringSelect

aikau/src/main/resources/alfresco/services/SiteService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1108 to fix the problem of the SiteService not favouriting sites that it had created (this was only showing on Firefox on Windows). The problem was because I'd foolishly failed to remove the old code in the previous fix!
=> AKU-1108: Ensure SiteService favourites created sites

aikau/src/main/resources/alfresco/core/WidgetsOverrideMixin.js, aikau/src/main/resources/alfresco/services/DialogService.js, aikau/src/main/resources/alfresco/services/SiteService.js, aikau/src/test/resources/alfresco/renderers/TagsTest.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/SiteService.get.js, aikau/src/test/resources/testApp/js/aikau/testing/mockservices/SiteMockXhr.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1130 to make it possible to customize the create and edit site dialog models in the SiteService through configuration. This capability is provide by a new WidgetsOverrideMixin module (intended for use in other widgets/services). Unit tests have been added to verify the capabilities.
=> AKU-1130: Improved create/edit site dialog customization options

aikau/src/main/resources/alfresco/forms/controls/utilities/TextBoxValueChangeMixin.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1132 to ensure that the create and edit site dialogs can be submitted via the "OK" button without having lost focus on the fields. Unit tests updated
=> AKU-1132: Fix blur issue on form dialog validation

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/main/resources/alfresco/dialogs/css/AlfDialog.css, aikau/src/main/resources/alfresco/services/SiteService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1133 to try to improve the initial rendering of the Create Site dialog (provided by the SiteService). There was previously some "jumping" as the dialog resized once displayed. To mitigate this problem a fixed width has been provided (the width and height have also been made configurable on the service) and the opacity of the dialog is set to 0 until it has been given focus. This allows for initial resizing to occur unseen by the user.
=> AKU-1133: Improve initial rendering of create site dialog

aikau/src/main/resources/alfresco/renderers/MoreInfo.js, aikau/src/main/resources/alfresco/renderers/css/MoreInfo.css
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1136 to make some improvements to the MoreInfo widget. The cursor has been corrected as have the size of the the thumbnails (to take into account the unknown image size) and scrollbars are hidden.
=> AKU-1136: MoreInfo styling improvements

aikau/src/main/resources/alfresco/css/less/defaults.less, aikau/src/main/resources/alfresco/header/css/Title.css
This PR moves the LESS default for the Share header title to the defaults.less file where it should have been all along.
=> Move LESS variable to correct location

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/main/resources/alfresco/search/AlfSearchResult.js, aikau/src/main/resources/alfresco/services/SearchService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1135 to provide better options for configuring the search term highlighting through the SiteService. This means that it will be easy to tweak the settings via an extension module applied to the faceted search page in Share. The Property renderer and AlfSearchResult have also been tweaked to support trimming of whitespace.
=> AKU-1135: Search term highlighting configuration options

aikau/src/main/resources/alfresco/forms/controls/MaskingTextBox.js, aikau/src/test/resources/alfresco/services/SiteServiceTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1137 to ensure that the MaskingTextBox used for the site shortName value in the Create Site dialog has it's validation error shown appropriately when it has a value derived from the site title field **before** the user has focused on it. The validation is only displayed when an actual value (i.e. not the empty string) is set. The unit tests have been updated.
=> AKU-1137: Ensure MaskingTextBox validation error displays on value

aikau/src/main/resources/alfresco/renderers/Property.js
This PR is an update to the previous changes made for https://issues.alfresco.com/jira/browse/AKU-1135 (see #1316). This additional change swaps the "\&nbsp;" character for a normal whitespace to enable normal trimming to work.
=> AKU-1135: Improved Property trim

aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Performance.get.js
This PR extends the performance test to showcase scaling issues with more complex widget configurations. All the properties being set are non-functional for the widget but current handling (most prominently the inherited _applyAttributes from Dojo/Diji _WidgetBase) adds significant overhead.
=> Demonstrate overhead of multiple widget config properties

aikau/src/main/resources/alfresco/lists/views/layouts/Cell.js, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Performance.get.js
Aikau widget configurations can contain an arbitrary number of configuration attributes. The way these are handled currently includes them in the "param" object which _applyAttributes in Dijit _WidgetBase processes. This is meant to apply any attributes that can be mapped to DOM or a widget-internal setXY operation, which does not apply for 99+% of Aikau attributes. All the lookup / looping over Aikau properties can introduce significant overhead for non-trivial widgets.
This PR adds extra handling to postMixInProperties and postCreate of Row, Cell and Property modules to avoid such overhead. For some reason it was not possible to simply override _applyAttributes to achieve the same.
It is not ideal that this is added in the "leaf" widget modules but unfortunately Aikau does not really …
=> Avoid _applyAttributes overhead by "hiding" complex Aikau widget configuration

aikau/src/main/resources/alfresco/search/SearchThumbnail.js, aikau/src/main/resources/alfresco/search/SearchThumbnailMixin.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1141 to ensure that all search thumbnails will have properly encoded tooltips. The previous fix was moved to the appropriate mixin module.
=> AKU-1141: Moved search thumbnail tooltip fix to appropriate mixin module

aikau/src/main/resources/alfresco/renderers/css/Progress.css, aikau/src/main/resources/alfresco/services/DocumentService.js, aikau/src/test/resources/alfresco/services/actions/DownloadAsZipTest.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1139 to improve the rendering of the Download as ZIP action dialog to ensure that no scroll bars are displayed.
=> AKU-1139: Improve download as zip dialog rendering

aikau/src/main/resources/alfresco/preview/PdfJs/PdfJs.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1138 to improve the height calculations for the PDF.js previewer in dialogs to ensure that horizontal scrollbars are not clipped at all.
=> AKU-1138: Improve PDF.js previewer height calculations for dialog

aikau/src/main/resources/aikau/core/BaseWidget.js, aikau/src/main/resources/alfresco/core/BaseWidget.js, aikau/src/main/resources/alfresco/debug/WidgetInfo.js, aikau/src/main/resources/alfresco/lists/views/layouts/Cell.js, aikau/src/main/resources/alfresco/lists/views/layouts/Row.js, aikau/src/main/resources/alfresco/renderers/ActivitySummary.js, aikau/src/main/resources/alfresco/renderers/Boolean.js, aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/alfresco/renderers/BooleanTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/core/Performance.get.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Boolean.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1145 and https://issues.alfresco.com/jira/browse/AKU-1147 to define a more performant approach for building widgets that removes the overhead of the _applyAttributes function and provides a new life-cycle function to be used to build the widget DOM natively (but still support extending widgets to provide templates). Although this doesn't tackle all Aikau widgets, it addresses the main widgets in the performance test page to try to demonstrate a path forwards that provides a rendering boost.
@AFaust I'd appreciate you taking a look at this.
=> AKU-1145, AKU-1147: Performance update pattern

aikau/src/main/resources/alfresco/services/SiteService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1150 to improve the handling of loading the legacy edit-site resources from the SiteService. The resource is now only loaded on demand and only when it hasn't previously been loaded before and the correct production/debug version is loaded.
=> AKU-1150: Better handling of legacy edit-site resource loading

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1152 to ensure that multiple classes set in the `renderedValueClass` attribute of the Property renderer will be honoured. This property shouldn't really be used like this but an example was added to CMM using this so we need to ensure it continues to work for backwards compatibility. The issue was introduced with the rendering performance improvements.
=> AKU-1152: Handle white space in renderedValueClass

aikau/src/main/resources/alfresco/renderers/InlineEditProperty.js, aikau/src/test/resources/alfresco/renderers/InlineEditPropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/InlineEditProperty.get.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1155 to fix a regression introduced into 1.0.83 that impacts the Search Manager page in Share. The dependency callback for Deferred was mapped to the wrong variable which causes saves to fail when `refreshCurrentItem` was configured to be `true`. I've also take then time to add better testing and fixes for value maps which also was working sub-optimally in Share.
=> AKU-1155: InlineEditProperty fixes for value maps, boolean values and dependency callbacks

aikau/src/main/resources/alfresco/services/i18n/SiteService.properties
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1154 to update the error message that is displayed via a dialog when attempting to create a site with an existing shortName. The dialog is only displayed as a result of eventual consistency causing the validator to not find the duplicate. This only occurs if the user attempts to create the duplicate site immediately after just creating it (which is an unlikely eventuality).
=> AKU-1154: Updated duplicate site id dialog error message

aikau/src/main/resources/alfresco/services/SearchService.js
This PR addresses https://issues.alfresco.com/jira/browse/AKU-1156 to remove the default configuration for max analyzed characters from the search term highlighting configuration.
=> AKU-1156: Remove default for STH max analyzed chars

aikau/src/main/resources/alfresco/services/SiteService.js
Based on the [last blog post on create and edit site customization](https://community.alfresco.com/community/ecm/blog/2016/11/23/create-and-edit-site-customization) I started to implement such customization for [Acosix/alfresco-site-hierarchy](https://github.com/Acosix/alfresco-site-hierarchy) for compatibility with 5.2 / 201612 GA. While the widgetsForCreateSiteDialogOverrides are applied the same call for widgetsForEditSiteDialogOverrides is missing.
This PR adds the missing 2nd call to applyWidgetOverrides.
=> Actually apply the editSiteDialog overrides

aikau/src/main/resources/alfresco/forms/controls/SitePicker.js
Currently the widgetsForControl structure is initialised in the postMixInProperties function which prevents any customisation of the structure by simple JSON model configuration. The current initialisation can be moved to a simple prototype override, allowing configuration. This PR does just that.
=> Allow widgetsForControl configuration in SitePicker

aikau/src/main/resources/alfresco/dialogs/AlfDialog.js, aikau/src/test/resources/alfresco/services/ContentServiceTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/ContentService.get.js
This issue addresses https://issues.alfresco.com/jira/browse/AKU-1162 to resolve a bug in Chrome that is causing the footer in the AlfDialog to be rendered at the minimum body height in dialogs for deleting content (when there is a large amount of content). This issue has been resolved by toggling the display of the footer on resize (and waiting for an animation frame in which to re-show it). This fixes the issue. A unit test has been added, but unit testing on Vagrant (with an earlier Chrome version installed) showed that this is definitely a recent Chrome rendering bug.
=> AKU-1162: Chrome rendering issue on dialog footer placement

aikau/src/main/resources/alfresco/logging/DebugLog.js
I am currently tracking down an issue with infinite scrolling on an AlfFilteredList in an Aikau-ified Surf component (not a hybrid or full page web script - in this case I am replacing the people-finder component in the page of that name via a sub-component) using the InfiniteScrollingService. During debugging I noticed that immediately after the initial page load and a single scroll action, the PubSubLog was extremely slow to open. Looking for ALF_EVENTS_SCROLL revealed that the payload published contains a reference to the window object which is currently not detected in the sanitation code. As a result, the entire window object and all the data accessible through it have been recursively processed. This even included data from localStorage, which - among other data - contained a very …
=> Improve DebugLog data sanitation

aikau/src/main/resources/alfresco/renderers/Property.js, aikau/src/test/resources/alfresco/renderers/PropertyTest.js, aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/renderers/Property.get.js
This addresses https://issues.alfresco.com/jira/browse/AKU-1166 to add support for a "title" attribute on the Property widget. The unit tests have been updated to verify this and prevent future regressions.
=> AKU-1166: Add support for title on Property

aikau/src/main/resources/alfresco/menus/AlfMenuBarPopup.js
This fixes https://issues.alfresco.com/jira/browse/AKU-1170
=> AKU-1170: Change popup menu item image role from "presentation" to "button"

aikau/src/main/resources/alfresco/renderers/Thumbnail.js
-Rework else if to test for the case when results do not contain a node object.
-Rework logic to use the nodeRef property of the item when a node object is not present on the item.
-This allows newer versions of Aikau to work with Aikau supported versions of Alfresco older than 5.2 to display generated thumbnails in Advanced Search.
-IDE automatically cleaned up spaces it didn't like in the file
=> [AKU-1171] Generated thumbnails in advanced search are not shown

aikau/src/main/resources/alfresco/core/TemporalUtils.js, aikau/src/main/resources/alfresco/forms/controls/DateTextBox.js
DateTextBox was displaying dates differently depending on user's browser's locale settings (as per default Dojo config) - I've changed it so it now uses the standard Alfresco date formatting strings (respecting our locale behaviour).
I've also had to add an extra temporalUtil method to convert between the Dojo date format and the Alfresco one. See comments for details.
=> RM-6273: Fix DateTextBox to use Alfresco dateFormat mask

tutorial/chapters/Tutorial1.md
The current maven archetype plugin does not support remote catalogs any longer. Instead it falls back to its internal catalog resulting in the person trying to get through the tutorial being stuck.
This proposed change is explicitly calling an older version of the archetype plugin which still accepts remote catalogs.
Fixes #1364
=> Update Tutorial1.md to get over issue with recent version of maven archetype module

aikau/src/main/resources/alfresco/services/DialogService.js
This PR adds a new configuration property to payloads for DialogService pubSub events to create dialog instances to specify ```destroyOnHide``` semantics.
Currently, all dialogs created via the DialogService will remain technically alive and active until the next dialog with the same ```dialogId``` is created and any previous instance is properly destroyed. For complex dialogs that include widgets with active pubSub interactions this means these widgets may continue to publish or react to events. E.g. in the OOTBee Support Tools addon there is a [dialog](https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/share/src/main/amp/config/alfresco/site-webscripts/org/orderofthebee/support-tools/console/support-tools/log4j-settings.get.js#L97) to display and contiuously reload the …
=> Add destroyOnHide for DialogService pubSub payloads

aikau/src/main/resources/alfresco/documentlibrary/_AlfDocumentListTopicMixin.js, aikau/src/main/resources/alfresco/lists/AlfSortablePaginatedList.js, aikau/src/main/resources/alfresco/lists/SortFieldSelect.js, aikau/src/main/resources/alfresco/lists/SortOrderToggle.js, aikau/src/main/resources/alfresco/lists/views/layouts/HeaderCell.js
Resolves #1352
This PR addresses the points I reported in #1352. I have update all relevant references to topics.SORT_LIST to use an instance-configurable property instead which is by default initialised to the value of the topic constant, thus keeping backwards compatibility. In one instance I also corrected an incorrect use of the topics.UPDATE_LIST_SORT_FIELD constant when a relevant instance-level property already existed. For the SortOrderToggle module I had to move the ```onConfig```/```offConfig``` default override into a new ```postMixInProperties``` to deal with the configurable ```selectionTopic``` so users of this module are not forced to override/configure those two properties just because they configured a different ```selectionTopic```.
=> Make hard-coded topics for sort requests / field selection configurable
